### ISSUE TITLE
Repeat last change does not repeat insertion

### ISSUE THREAD

**Issue by mveres** [atom/vim-mode#1010]
- go to insert mode
- type 'hello'
- go to normal mode
- navigate do a different row
- press "."
Expected: 'hello' is inserted again
Actual: it isn't

**Comment by movestill** [comment]
Probably related, trying to repeat a change word command (cw) only deletes the current word but does not do the subsequent insert of text.

Atom 1.7.1
vim-mode 0.65.0
Windows 7

**Comment by psifertex** [comment]
Looks like a dupe of #1006

**Comment by haasDev** [comment]
+1

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
I have the same issue.

Atom 1.7.1
vim-mode 0.65.0
ubuntu 14.04

**Comment by sandman21dan** [comment]
+1 using command CIW then repeating with "." doesn't re-add the word, just deletes.

**Comment by snkutlu** [comment]
Have the same issue for "Insert" and for "change-word". 

Atom 1.7.3
vim-mode 0.65.0 
MacOS ElCapitan 10.11.4

**Comment by gjngeldenhuis** [comment]
+1

**Comment by gregz67** [comment]
+1

Same atom and vim-mode versions. Mac Yosemite.

**Comment by BinaryMuse** [comment]
Fixed by #1020
