### ISSUE TITLE
Exit insert mode

### ISSUE THREAD

**Issue by guiwp** [atom/vim-mode#1012]
I can't exit with the `CTRL+[`, just with `ESC`.

Atom 1.7.2, Windows 10 Home Single Language, 10.0.10586 N/A compilation 10586.

**Comment by guiwp** [comment]
The [keyboard-localization](https://atom.io/packages/keyboard-localization ) solved the problem.

**Comment by 50Wliu** [comment]
Glad to hear it @guiwp.
