### ISSUE TITLE
"." not working

### ISSUE THREAD

**Issue by andianderson522** [atom/vim-mode#1019]
I am doing things like cw change esc    then moving to next instance and typeing . but it is just deleteing the word. I am using version 0.65.0

this was working before

**Comment by jskopek** [comment]
Looks like you're seeing the same issue as #1006

**Comment by andianderson522** [comment]
yes looks that way. I have tried vim-mode-plus but with a lack of the ex commands its a no go for me

**Comment by 50Wliu** [comment]
Closing in favor of #1006.
