### ISSUE TITLE
Clipboard replaced using "x" or "cw"

### ISSUE THREAD

**Issue by scottp** [atom/vim-mode#1059]
VIM will put into clipboard a "dd" or cut selection for pasting again later. With Atom if I even press "x" or "cw" my clipboard is replaced with that single character. This means that there is never a way to copy from another application except for insert new. Cut characters, start insert, switch apps, copy, then back to atom to paste.

Could argue that this is normal behaviour and expected - maybe it is - but it is not the same as VI/VIM.

However, I think this bug is more related due to the fact that ATOM shares the real clipboard. So in VI/VIM if you "x" or "cw" or "dd" you use the VI buffer, and cut/paste from either GUI VIM or Command Line still has the operating system clipboard. ie. they are separate. ATOM has just one - the operating system clip board.

**Comment by snkutlu** [comment]
+1 to have a seperate buffer for VI mode buffer and system clipboard.

**Comment by jacekkopecky** [comment]
Have you tried the "Use Clipboard As Default Register" setting?

In VIM and in Atom, I often use `xp` to switch two characters, e.g. in a typo like "foten" for "often".

**Comment by plbowers** [comment]
In vim a delete within a line (`x`, `dw`, `2dw`, `d$`, etc.) does not update the numbered registers but instead goes into the "- register (also called the "small register"). Maybe this (applied to the clipboard) should be an option if you have chosen "Use Clipboard As Default Register"...  Thus line-oriented deletes or changes would go into the clipboard but intra-line deletes or changes would not. Presumably any use of yank implies the desire to put it in a register and so `yw` and `y$` should probably update the clipboard.

Another alternative would be to not update the clipboard until the end of the change command, so `c2w^v<ESC>` would change the next 2 words to whatever was in the clipboard and then replace the clipboard with those 2 words *afterwards*.

Another alternative is to train people in the use of the `"_` register -- if you don't want your deleted/changed text to be recorded in a register then prepend it with `"_`. So if I wanted to replace the next 2 words with the clipboard I could type `_2c^v<ESC>`.

**Comment by discobean** [comment]
+1 `cw` should not copy what is removed into the clipboard, this is not how existing gvim works.  Having said that changing "Use Clipboard As Default Register" resolves this specific problem, thanks @jacekkopecky

**Comment by nadim** [comment]
`Don't update register on change or substitute` is the setting I had to enable for this to stop happening. `Use clipboard as default register` was checked by default I believe, and not doing it for me.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
