### ISSUE TITLE
Implement numbered registers to retrieve previously copied text

### ISSUE THREAD

**Issue by plbowers** [atom/vim-mode#1061]
http://vimdoc.sourceforge.net/htmldoc/change.html#registers

Currently vim-mode does not implement numbered buffers and the small buffer (#2 and #3 on that reference above).

I have implemented this on my system but am having difficulty getting a pull request to go through here.

**Comment by plbowers** [comment]
I have this working with the commits I have done. I am unfamiliar with the spec system, but I am trying to learn how it works. 

What is the next step?

**Comment by 50Wliu** [comment]
> What is the next step?

Can you elaborate on what you mean by this?

**Comment by plbowers** [comment]
I made the changes to the code and got it working, but I don't know what the process is to get my changes into the pipeline for whatever change management process you have before changes get actually implemented in the official vim-mode.

**Comment by plbowers** [comment]
OK, I'm starting to realize I'm going about this wrong. This is my first github project (although I've used several other source-code-mgmt tools). When I couldn't create a new branch or upload a new file I went ahead and forked so I could contribute over on my system. I assumed that would allow others to do a code-review and a merge, but I'm starting to realize that's not right - it seems I've created a completely independent fork.

So I have a coded (and now spec'd) change with a feature request implemented. What do I need to do to contribute this to the project? Is there some documentation somewhere explaining the steps needed? Do I need to be authorized somehow? Is there a vetting process before being authorized?

**Comment by 50Wliu** [comment]
> So I have a coded (and now spec'd) change with a feature request implemented

You have to create a pull request: https://github.com/atom/vim-mode/pulls -> New Pull Request.  Or I think you can do that directly from your fork.

**Comment by plbowers** [comment]
Great - that was exactly what I needed to understand. I didn't realize I could generate a pull request between the primary repository (here) and my fork.

Now I see that if there are no conflicts I can actually merge my PR back into the master myself (at least it looks like it - I haven't clicked on the "merge" button to test it). That's a little scary since I could be anybody - is there any type of peer review system that is used first?

**Comment by 50Wliu** [comment]
> That's a little scary since I could be anybody - is there any type of peer review system that is used first?

I don't believe you can - make sure you didn't create the PR on your own fork.

**Comment by plbowers** [comment]
You're right. I had closed the previous PR so I just created a new one and got to the point where before it allowed me to merge and it now tells me only people with write access can merge. So obviously I must have been doing it on my own fork.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
