### ISSUE TITLE
Spacebar broken in beta

### ISSUE THREAD

**Issue by DavidLGoldberg** [atom/vim-mode#1071]
The spacebar functionality is broken in Atom Beta.

I have a similar problem with my package jumpy breaking.  It seems they both just don't get notified of the key press!

cmd + . for key resolver shows nothing happening!

This is an issue in Atom core (beta) right?

**Comment by pirminis** [comment]
spacebar is definately not working in keymaps file anymore.

snippet that was working in atom-beta < 1.12
```
"atom-text-editor.vim-mode.normal-mode":
  "space a": "vim-mode:insert-after-end-of-line"
```

**Comment by DavidLGoldberg** [comment]
about to create an issue in core

**Comment by 50Wliu** [comment]
This has already been fixed.  See atom/atom-keymap#150.
