### ISSUE TITLE
Parentheses randomly disappear

### ISSUE THREAD

**Issue by revoxx5** [atom/vim-mode#1072]
So lets say we have a function in java
public int test(Stuff here){

Now when I start to delete stuff here and get to like the stuff keyboard or something with $ representing the cursoe
public int test(Stuf$){
the closing parentheses randomly disappears
public int test(stuf${
I'll post a gify of it happening later tonight

**Comment by 50Wliu** [comment]
Does this happen in safe mode (`atom --safe`)?

**Comment by revoxx5** [comment]
So I managed to re-create the issue several times and figured out what's going on
The issue is if you have a parentheses like (stuff here()).
It goes something like this ($ representing the cursor that is deleting stuff)
(stuff here()$)
(stuff here($)
(stuff here$
The issue is if you delete an inner parentheses next to an outer, it will delete both of them instead of just the inner.
