### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by Fuffi** [atom/vim-mode#1073]
Has development stopped? I know there's a vim-mode-plus but what happened to this one?

**Comment by Ben3eeE** [comment]
https://github.com/atom/vim-mode/issues/1045#issuecomment-250221562

[We're trying to control the amount of Issues that we have to triage and track](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For general questions, [the Atom message board](https://discuss.atom.io) is where you'll be able to find answers faster.
