### ISSUE TITLE
Go File command

### ISSUE THREAD

**Issue by denqxotl** [atom/vim-mode#1076]
Hi. Vim as default has `gf` combination that allows to open file

For example I have 
```ruby
require_relative '../user.rb'
```
in my current file. when  I put my cursor on `../user.rb` and press `gf` combination it should open this file if it exists.

**Comment by bronson** [comment]
Install https://atom.io/packages/open-this and copy the example keymap into yours.

vim-mode is meant to just handle text editing.  To get the full Vim experience you'll need a few more packages.  Right now I'm using cursor-history, paner, project-find-navigation, vim-mode-plus, and vim-mode-plus-ex-mode.

**Comment by denqxotl** [comment]
@bronson gotcha. thanks
