### ISSUE TITLE
End of line with $ not working on Swedish keyboard

### ISSUE THREAD

**Issue by jacwah** [atom/vim-mode#1078]
Until recently, I was using the keyboard-localization package, which had resolved mapping issues in past. When I realized "|" (alt-7) had stopped working, I went to the package's repository to find that it had been deprecated as Atom now supports handling of non-US keyboard layouts. Yay! I disabled the package and typing "|" started working again.

However, I found a regression. Now the "$" (alt-4) end of line motion in vim-mode doesn't work anymore. This problem seems specific to this package as pressing the key binding in insert mode correctly inserts a dollar sign.

Similar issues have been reported before: #222, #260. This difference to this one is that those were reported before Atom started to support more layouts in core and both threads end with the advice to install keyboard-localization. Since that package is discontinued and contains bugs, the pipe character in my case, I don't think that solution is applicable anymore.

The key binding resolver (cmd-.) resolves alt-4 as is, both in insert and command mode.

Operating system: OS X 10.12.1
Atom: 1.11.2
vim-mode: 0.65.1

**Comment by 50Wliu** [comment]
> Atom: 1.11.2

Atom 1.11.x doesn't contain the keyboard layout fixes - you'll need to install Atom 1.12-beta for that.
