### ISSUE TITLE
Deprecated selector in `vim-mode/styles/vim-mode.less`

### ISSUE THREAD

**Issue by xiongxiong** [atom/vim-mode#1079]
In `vim-mode/styles/vim-mode.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor.vim-mode.normal-mode::shadow .cursor,
atom-text-editor.vim-mode.operator-pending-mode::shadow .cursor,
atom-text-editor.vim-mode.visual-mode::shadow .cursor,
atom-text-editor.vim-mode.normal-mode .cursor,
atom-text-editor.vim-mode.operator-pending-mode .cursor,
atom-text-editor.vim-mode.visual-mode .cursor` => `atom-text-editor.vim-mode.normal-mode.editor .cursor,
atom-text-editor.vim-mode.operator-pending-mode.editor .cursor,
atom-text-editor.vim-mode.visual-mode.editor .cursor,
atom-text-editor.vim-mode.normal-mode .cursor,
atom-text-editor.vim-mode.operator-pending-mode .cursor,
atom-text-editor.vim-mode.visual-mode .cursor`

* `atom-text-editor.vim-mode.normal-mode.is-focused::shadow .cursor,
atom-text-editor.vim-mode.operator-pending-mode.is-focused::shadow .cursor,
atom-text-editor.vim-mode.visual-mode.is-focused::shadow .cursor,
atom-text-editor.vim-mode.normal-mode.is-focused .cursor,
atom-text-editor.vim-mode.operator-pending-mode.is-focused .cursor,
atom-text-editor.vim-mode.visual-mode.is-focused .cursor` => `atom-text-editor.vim-mode.normal-mode.is-focused.editor .cursor,
atom-text-editor.vim-mode.operator-pending-mode.is-focused.editor .cursor,
atom-text-editor.vim-mode.visual-mode.is-focused.editor .cursor,
atom-text-editor.vim-mode.normal-mode.is-focused .cursor,
atom-text-editor.vim-mode.operator-pending-mode.is-focused .cursor,
atom-text-editor.vim-mode.visual-mode.is-focused .cursor`

* `atom-text-editor.vim-mode.visual-mode::shadow .cursor.hidden-cursor,
atom-text-editor.vim-mode.visual-mode .cursor.hidden-cursor` => `atom-text-editor.vim-mode.visual-mode.editor .cursor.hidden-cursor,
atom-text-editor.vim-mode.visual-mode .cursor.hidden-cursor`

* `atom-text-editor.vim-mode.replace-mode::shadow .cursor,
atom-text-editor.vim-mode.replace-mode .cursor` => `atom-text-editor.vim-mode.replace-mode.editor .cursor,
atom-text-editor.vim-mode.replace-mode .cursor`

* `atom-text-editor.vim-mode.replace-mode.is-focused::shadow .cursor,
atom-text-editor.vim-mode.replace-mode.is-focused .cursor` => `atom-text-editor.vim-mode.replace-mode.is-focused.editor .cursor,
atom-text-editor.vim-mode.replace-mode.is-focused .cursor`

* `atom-text-editor.vim-mode.replace-mode.is-focused::shadow .cursors.blink-off .cursor,
atom-text-editor.vim-mode.replace-mode.is-focused .cursors.blink-off .cursor` => `atom-text-editor.vim-mode.replace-mode.is-focused.editor .cursors.blink-off .cursor,
atom-text-editor.vim-mode.replace-mode.is-focused .cursors.blink-off .cursor`

* `atom-text-editor.vim-mode.operator-pending-mode::shadow .cursor,
atom-text-editor.vim-mode.operator-pending-mode .cursor` => `atom-text-editor.vim-mode.operator-pending-mode.editor .cursor,
atom-text-editor.vim-mode.operator-pending-mode .cursor`

* `atom-text-editor.vim-mode.operator-pending-mode.is-focused::shadow .cursor,
atom-text-editor.vim-mode.operator-pending-mode.is-focused .cursor` => `atom-text-editor.vim-mode.operator-pending-mode.is-focused.editor .cursor,
atom-text-editor.vim-mode.operator-pending-mode.is-focused .cursor`

* `atom-text-editor.vim-mode.operator-pending-mode.is-focused::shadow .cursors.blink-off .cursor,
atom-text-editor.vim-mode.operator-pending-mode.is-focused .cursors.blink-off .cursor` => `atom-text-editor.vim-mode.operator-pending-mode.is-focused.editor .cursors.blink-off .cursor,
atom-text-editor.vim-mode.operator-pending-mode.is-focused .cursors.blink-off .cursor`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by biffster** [comment]
Seeing this issue on Atom 1.13.0 x64 on OS X El Capitan.

**Comment by as-cii** [comment]
I have just merged a pull request that should make the deprecation go away in the next update. However, as mentioned in the README, we recommend switching to [vim-mode-plus](https://github.com/t9md/atom-vim-mode-plus) as this package is no longer maintained.
