### ISSUE TITLE
Just not working.

### ISSUE THREAD

**Issue by classLfz** [atom/vim-mode#1086]
I don't know where is the problem:

- ubuntu@16.10 64
- atom@1.13.1
- vim-mode@0.66.0

and it just change the cursor, but not working. I guess maybe is the vim-mode@0.66.0 is incompatible? so I uninstall vim-mode and use `apm install vim-mode@0.65.0`(or some other previous version), but still not work. Does anyone have the same problem? :sob:

**Comment by 50Wliu** [comment]
vim-mode is deprecated.  Please install vim-mode-plus instead.

**Comment by classLfz** [comment]
@50Wliu Oh, THX!
