### ISSUE TITLE
Enable us the command-line mode

### ISSUE THREAD

**Issue by jtr109** [atom/vim-mode#1088]
Please add a feature to enable us to use `:` to enter the command-line mode of vim. So we can use the command as `:s`, `:w`, `:x`, .etc by vim-mode.
Thanks a lot!

**Comment by 50Wliu** [comment]
Check out [vim-mode-plus](https://atom.io/packages/vim-mode-plus) and [ex-mode](https://atom.io/packages/ex-mode).
