### ISSUE TITLE
search word under cursor with *

### ISSUE THREAD

**Issue by zenhob** [atom/vim-mode#109]
In command mode, `*` over a word should jump to the next instance of that word in the buffer. I _think_ this can piggyback on top of built-in search and replace without much trouble.

**Comment by robru** [comment]
@zenhob using the `atom-macros` package I was able to define a couple macros that do exactly this:

```
@findNextWordUnderCursor = ->
    dispatchEditorCommand 'editor:select-word'
    dispatchEditorCommand 'find-and-replace:use-selection-as-find-pattern'
    dispatchEditorCommand 'find-and-replace:find-next'

@findPreviousWordUnderCursor = ->
    dispatchEditorCommand 'editor:select-word'
    dispatchEditorCommand 'find-and-replace:use-selection-as-find-pattern'
    dispatchEditorCommand 'find-and-replace:find-previous'
```

I think this behavior is more true to vim's `*` than the `select-next` command.

**Comment by jacekkopecky** [comment]
@robru, in #561 I have some fixes for * and # – is this related?

**Comment by robru** [comment]
@jacekkopecky eh, define "related" ;-)

The above code achieves the desired behavior only if you install another package to enable it. It's basically just a workaround, not really relevant to vim-mode directly, no.
