### ISSUE TITLE
After key 's' in visual mode, selection block not canceled

### ISSUE THREAD

**Issue by MewX** [atom/vim-mode#1093]
I'll use `[]` to present cursor in normal mode, and `|` in insert mode, to simulate the reproducing procedure.

Originally:
```
some text;
[d]ist = a;
pastNodes = b;
```

Then press `c-v`, select:

```
some text;
[dist] = a;
[past]Nodes = b;
```

Then press `s`:
```
 some text;
| = a;
 Nodes = b;
```

Then press `esc`:
```
[s]ome text;
[ ]= a;
Nodes = b;
```

See, **the selection block are not canceled**, if I press `esc` again, it becomes normal:
```
some text;
[ ]= a;
Nodes = b;
```

**Comment by 50Wliu** [comment]
This package is deprecated.  You may be interested in installing [vim-mode-plus](https://atom.io/packages/vim-mode-plus) instead.

**Comment by MewX** [comment]
Oh, thanks, I was using `vim mode plus`!
