### ISSUE TITLE
Uncaught NotFoundError

### ISSUE THREAD

**Issue by sh2z** [atom/vim-mode#1094]
Uncaught NotFoundError: Failed to execute 'remove' on 'Element': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
C:\Users\BF100400\AppData\Local\atom\app-1.18.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:854
Show Stack Trace
The error was thrown from the vim-mode package. This issue has already been reported.

**Comment by rsese** [comment]
Thanks for the report!  Closing since this package has been deprecated in favor of [vim-mode-plus](https://atom.io/packages/vim-mode-plus):

https://github.com/atom/vim-mode#current-status---deprecated-in-favor-of-vim-mode-plus

You may want to give that package a try.
