### ISSUE TITLE
Problem mapping jj to activate-command-mode

### ISSUE THREAD

**Issue by mpolden** [atom/vim-mode#128]
Mapping 'jj' to escape is pretty common when using vim.

If 'jj' is mapped to activate-command-mode, then 'jj' will enter command mode, but it's no longer possible to type a single 'j' when in INSERT mode.

I'm using this mapping:

``` coffeescript
'.vim-mode.insert-mode:not(.mini)':
  'j j': 'vim-mode:activate-command-mode'
```

**Comment by liyaodong** [comment]
`init.coffee`

```
atom.commands.add 'atom-text-editor', 'custom:wait-key-press', (e)->
  oe = e.originalEvent
  char = String.fromCharCode(oe.which)
  char = char.toLowerCase() unless oe.shift
  atom.workspace.getActivePaneItem().insertText(char)
```

`keymap.cson`

```
'atom-text-editor.vim-mode.insert-mode':
  'j': 'custom:wait-key-press'

'.vim-mode.insert-mode:not(.mini)':
  'j j': 'vim-mode:activate-command-mode'
```

worked for me , atom version `0.207.0`

**Comment by eventualbuddha** [comment]
Works for me too! Doesn't work in version `0.206.0`, so make sure you're fully updated if you're trying this out.

**Comment by beardedprojamz** [comment]
[liyaodong's solution](https://github.com/atom/vim-mode/issues/128#issuecomment-110577352) worked for me as well! Thanks :+1:

**Comment by adinapoli** [comment]
Worked for me as well! (Version `1.0.2`)

**Comment by vv13** [comment]
I'm 1.8.0, i use
```
'atom-text-editor.vim-mode.insert-mode':
  'j': 'custom:wait-key-press'

'.vim-mode.insert-mode:not(.mini)':
  'j j': 'vim-mode:reset-normal-mode'
```
