### ISSUE TITLE
NERDTree commands for Project Tree?

### ISSUE THREAD

**Issue by eob** [atom/vim-mode#131]
It would be fantastic if keyboard commands supported:
-   Switching between the active pane and the project tree (an improvement over vim could be made here because the tree could be made a special entity rather than just another pane. You could swap directly to and back from it rather than cycling between panes)
-  Toggling folders
-  Opening, moving, creating files

**Comment by damassi** [comment]
@dougblack, that sounds great; I'll indeed go that route.  Thanks for the fast response everyone!

**Comment by pgericson** [comment]
*For all the people that get this thread as the top result when you search*

Here is a whole thread of bind copy&paste snippets about toggle navigation:
https://discuss.atom.io/t/only-allowing-keybind-to-be-triggered-when-in-command-mode-vim-mode/15496

The following snippet toggles focus between project tree and the editor
```
'atom-text-editor.vim-mode:not(.insert-mode), .tree-view':
  ', n': 'tree-view:toggle-focus'
```
