### ISSUE TITLE
'j j' mapping and similar bindings are rested!

### ISSUE THREAD

**Issue by arnm** [atom/vim-mode#147]
I have mapped 'j j' in insert mode to activate command mode and it works fine except for the fact that I can't type words beginning with the letter 'j' now. I saw that in the default mappings 'g g' was mapped to something and I have no problem typing in words that begin with 'g'. 

I have also tried this with other key bindings which are similar to 'j j' ( they require multiple key presses in order to call an action ) and had similar results. 

I am very accustomed to my vim configuration and being able to pretty closely match it with Atom would be amazing.

Here is my keymap.cson ( please don't make fun of my weird mappings :) lol )

'body':
  ', h': 'pane:split-down'

'.vim-mode.insert-mode:not(.mini)':
  'j j': 'vim-mode:activate-command-mode'

'.vim-mode.visual-mode:not(.mini)':
  'j': 'vim-mode:select-left'
  'k': 'vim-mode:move-down'
  'l': 'vim-mode:move-up'
  ';': 'vim-mode:select-right'

'.vim-mode.command-mode:not(.mini)':
  'j': 'vim-mode:move-left'
  'k': 'vim-mode:move-down'
  'l': 'vim-mode:move-up'
  ';': 'vim-mode:move-right'

**Comment by liyaodong** [comment]
`init.coffee`

```
atom.commands.add 'atom-text-editor', 'custom:wait-key-press', (e)->
  oe = e.originalEvent
  char = String.fromCharCode(oe.which)
  char = char.toLowerCase() unless oe.shift
  atom.workspace.getActivePaneItem().insertText(char)
```

`keymap.cson`

```
'atom-text-editor.vim-mode.insert-mode':
  'j': 'custom:wait-key-press'

'.vim-mode.insert-mode:not(.mini)':
  'j j': 'vim-mode:activate-command-mode'
```

worked for me , atom version `0.207.0`
