### ISSUE TITLE
Soft wrap breaks line navigation key bindings

### ISSUE THREAD

**Issue by stickel** [atom/vim-mode#156]
They movement key bindings seem to break when “soft wrap at preferred line length” is enabled. I can navigate up and down the document with key bindings but as soon as I hit a wrapped line it won't advance passed the wrapped line.

**Comment by izuzak** [comment]
Just tried reproducing this with various examples using soft wrap and wasn't able to. I believe this was fixed in #406, so I'm closing the issue. If anyone can still reproduce in Atom 1.0.11 -- let me know and please provide an example.
