### ISSUE TITLE
Add support for macros

### ISSUE THREAD

**Issue by lamielle** [atom/vim-mode#161]
One of my favorite features in vim is macros.  Recording with q+letter, executing the commands you want recording, then hitting q again.

Having this feature in Atom would be awesome!

**Comment by rbraley** [comment]
+1

**Comment by danilomiranda** [comment]
+1

**Comment by jeffschwartz** [comment]
+1

**Comment by joowh85** [comment]
+1

ctrl+alt+l 
  'Convert space to tabs'
  'Toogle soft tabs'

This is what I want to.

**Comment by jeffschwartz** [comment]
+1

**Comment by DarrylD** [comment]
+1

In the process of making a few atom plugins which could easily be macros.

**Comment by andrewpcone** [comment]
+1

**Comment by kebertx** [comment]
Not to pop in just to say "+1," but...

**+1!**

**Comment by boyvinall** [comment]
+1

**Comment by DrBones** [comment]
Whohoo..umm..
+1

**Comment by mverardo** [comment]
+1

**Comment by cshanes** [comment]
+1

**Comment by arcseldon** [comment]
+10 :D  Atom is already awesome, as is VIM. But without Macros support, still regularly need to switch between the two text editors. With macros support, Atom would reach a point where for most day to day needs Vim is no longer required.

**Comment by walterheck** [comment]
+1

**Comment by mleeds95** [comment]
Based on [this](http://vim.wikia.com/wiki/Macros) I compiled a list of features that should be included in this fix:

- ability to record command sequences to registers <a-z> using 
```
q<letter><commands>q
```
- ability to replay macros using
```
<number>@<letter>
```
where number is optional
- ability to execute the last used macro again using
```
@@
```
- ability to run a single-line macro on each line of a visual selection using
```
:normal @<letter>
```
- ability to view all 26 registers' contents using
```
:registers
```
or
```
:reg
```
- ability to view one or more registers' contents using
```
:reg <letter><letter>...
```
- ability to save macros for use in a subsequent vim session
- ability to disable saving macros or control their length using
```
:set viminfo=...
```
- ability to read macros from a vimrc file in the format
```
let @<letter>='<commands>'
```
(or using that syntax at runtime)
- ability to append to an existing macro using
```
q<capital-letter><commands>q
```
- ability to insert the contents of a register using
```
<Ctrl-R><Ctrl-R><letter>
```

**Comment by mleeds95** [comment]
However, I don't see how many of them would work if Atom doesn't let you see commands as you type them like Vim does. Are there any plans to include this feature?

**Comment by tony612** [comment]
:+1:

**Comment by kzaher** [comment]
+1

**Comment by Phylodome** [comment]
+:100: 

Without macros atom vim-mode is severely hamstrung :(

**Comment by gmondada** [comment]
+1

**Comment by romgrk** [comment]
To package maintainers:

I have written a personnal Macro package, not published because it is not production-level, but it still works as I expect it to work.
I would like to know if you would be open to a PR on this.
The implementation consists of a KeyboardEvent listener, which is activated upon corresponding command; it listens for events on `<atom-workspace>`. Once command is called again, it removes the listener and transform the KeyboardEvents in a string of keys (vim-notation). The string is then stored for further usage.

**Comment by maxbrunsfeld** [comment]
@romgrk I would be open to a PR for this, but since it is a big change, I'd prefer that you maintain it as a separate package for a little while. Is your package published? If so, maybe some people participating in this thread would like to give it a try, or help you develop it!

**Comment by jacekkopecky** [comment]
Yes, I'd like to have a look, @romgrk ; can't promise to do anything quickly though. Is it in any way related to, or similar to, https://atom.io/packages/atom-macros (which I also have yet to look at)?

**Comment by kebertx** [comment]
Looking at [atom-macros](https://atom.io/packages/atom-macros), it's definitely *not* what any vim user is thinking about when you mention an editor macro. With vim, you start recording a sequence of actions, so you can repeat the same editor commands multiple times.

With the atom-macros package, you have to write coffeescript in `.atom/macros.coffee` ahead of time to be able to run a command from the command pallette. To be honest, I'm not sure how that's different than just defining a function in `init.coffee`, but whatever. It's not what we're looking for at all.

**Comment by jacekkopecky** [comment]
Oh, how mistaken I've been about that package! Yes, I'd like to have a look at yours.

**Comment by romgrk** [comment]
Ok, it might take a week or two; it's not actually a package, but a set of files I require from my `init.coffee`. A real mess, but it works; I'll put some order in there first.

**Comment by kebertx** [comment]
On the one hand, I can really see how macros are something that atom should support outside of vim-mode - it's useful to you even if vim isn't. On the other hand, it *doesn't* have macros anywhere right now, so if vim-mode can make it happen it's still sort of a win.

I can see a lot of far future-reorganization happening though - one day pulling `ex-mode` into this package (Insha'Allah), and another pulling `vim-macros` out :)

**Comment by jacekkopecky** [comment]
Yes, macros should be more general, not specific to vim-mode. I can imagine that the recording and replay functionality would be quite generic; the only real ties between macros and vim-mode would be key bindings, and the fact that in vim-mode, the macro should be recorded in a register, while without vim-mode, it's possible a macro package would need to replicate some form of registers.

Oooh, cool, how about we spin off vim registers into a separate package? When, oh when, will we have package sets to make this possible? :grinning:

**Comment by PandaWhisperer** [comment]
+10? :smile:

**Comment by jacekkopecky** [comment]
@PandaWhisperer, does it mean you have a team of ten, waiting for this
feature?

**Comment by rhelsing** [comment]
Need this!

**Comment by adamprescott** [comment]
:+1:

**Comment by ringate** [comment]
+1

**Comment by ntdef** [comment]
+1

**Comment by occamin** [comment]
+1

**Comment by cdpetty** [comment]
+1

**Comment by markrichards** [comment]
+1

**Comment by Ramblurr** [comment]
+1

**Comment by Luisss** [comment]
+1

**Comment by weavenoise** [comment]
+1!

**Comment by RVMendoza** [comment]
+1

**Comment by axelduch** [comment]
+1

**Comment by caiocutrim** [comment]
+1

**Comment by jtheoof** [comment]
Any progress on this?

**Comment by olivoil** [comment]
+1

**Comment by masics** [comment]
+1

**Comment by arcseldon** [comment]
It is evident this is a very popular feature request. I already voted back on 1st July :)

@jacekkopecky - sorry, I didn't understood whether the comments you have made above are a commitment to providing this feature. Please may I ask directly - Are any contributors from atom/atom or atom/vim-mode actively working on providing macros / vim register support for a generic macros solution in Atom?

In any case, keep up the excellent work, and thanks for everything provided to date.

**Comment by jacekkopecky** [comment]
@arcseldon I don't know of anybody working on this, but I've been occuppied by my day job since October and can't spend any time on vim-mode at all, so I could easily have missed it. I expect to do more vim-mode work (which could include macros) in the spring and summer, so don't hold your breath. 8-)

**Comment by arcseldon** [comment]
@jacekkopecky Thank you for your reply and clarifying status. Appreciate everyone is doing what they can and when they can afford the time etc. Wish I could offer to help out too, but just not possible right now either for much the same reasons  :(   Cheers.

**Comment by provolot** [comment]
+1

**Comment by stavinopolis** [comment]
+1

**Comment by HappyTepid** [comment]
+1

**Comment by wild-ki-ll** [comment]
+1

**Comment by jrpredes** [comment]
+1

**Comment by Daxez** [comment]
+1

**Comment by qiaomuf** [comment]
+1

**Comment by crazy4groovy** [comment]
+1

**Comment by brujo696** [comment]
+1

**Comment by sunjay** [comment]
+1

**Comment by sevenskull** [comment]
That would be awesome! I use notepad++ for macros when i need, but i use linux, so wine is needed.

**Comment by igagen** [comment]
+1

**Comment by karlfloersch** [comment]
+1

**Comment by jeremiahkonkle** [comment]
+1

**Comment by sayingandparsing** [comment]
+1

**Comment by palatok** [comment]
+1

**Comment by lime-green** [comment]
+1

**Comment by JunSuzukiJapan** [comment]
Hi, all.

I've tried to make keyboard macro package, but this is or become useless?

[atom-keyboard-macros-vim](https://atom.io/packages/atom-keyboard-macros-vim)

I usually use emacs key-bindings, so I'm not familiar about the vim.

**Comment by sarojkh** [comment]
+1

**Comment by palatok** [comment]
+1

**Comment by thomasjo** [comment]
As it stands, all the +1's are only adding noise and causes 62+ people to get notified. Therefore I'm locking this issue for the time being.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
