### ISSUE TITLE
gq to reflow/hard-wrap

### ISSUE THREAD

**Issue by lloeki** [atom/vim-mode#186]
gq<movement | object>: reflow

Examples:

gq2j reflow two lines down
gqq reflow line
<selection>gq reflow selection

Existing non-vim shortcut: alt+cmd+q

**Comment by paulcsmith** [comment]
This would be so helpful

**Comment by wil93** [comment]
:+1:

**Comment by jeffschwartz** [comment]
+1

**Comment by piohhmy** [comment]
+1

**Comment by AsaAyers** [comment]
How can we simply get `gq` to do the built in reflow for now? I tried but there's something I'm missing in the selector as I couldn't type words with `g`s.

**Comment by AsaAyers** [comment]
This doesn't work

```
'atom-text-editor.vim-mode:not(.insert-mode)':
  'g q': 'autoflow:reflow-selection'

'atom-text-editor.vim-mode.operator-pending-mode, atom-text-editor.vim-mode.visual-mode':
  'g q': 'autoflow:reflow-selection'
```

**Comment by codykrieger** [comment]
+1

**Comment by AsaAyers** [comment]
I updated my comment above to the keymap that I'm using. I think I was wrong when I said it didn't work because I think it's the same.

**Comment by codykrieger** [comment]
@AsaAyers Thanks! That gets closer to the behavior I'm used to—one case that still doesn't work is `v g q` (i.e. with a selection within a line), but I guess that's probably a problem with [autoflow](https://github.com/atom/autoflow). `V g q` works as expected.

**Comment by AsaAyers** [comment]
The one problem I found with V g q is that the cursor is technically in the
first column of the next line, so it gets included.

g q seems to be smart enough on comments to reflow multi line comments
without having to select all the lines

**Comment by codykrieger** [comment]
Yeah, that behavior is super annoying.

**Comment by wmayner** [comment]
+1

**Comment by maxbrunsfeld** [comment]
This one gets a :+1: from me too.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
