### ISSUE TITLE
Start a new line at last indent

### ISSUE THREAD

**Issue by yeison** [atom/vim-mode#199]
A feature request to start every new line at the last indent location.

**Comment by bronson** [comment]
Atom already does this, doesn't it?  Can you give some steps to show where Atom gets this wrong?

**Comment by guywald1** [comment]
Any news on this?

**Comment by bronson** [comment]
It already does.  To reproduce: cmd-n to create a new file, hit tab, then hit return.  Your new line is at the same indent as the previous.  I also see this working in JS and Ruby.

Can you describe steps to reproduce a failure?

**Comment by bronson** [comment]
There was this issue, but it was quite a while ago: https://github.com/atom/atom/issues/8013

**Comment by guywald1** [comment]
Apologies, a new user to this Package and the problem was on my end. Thanks for the quick reply, amazing work regardless.

**Comment by bronson** [comment]
You're welcome, glad it was an easy answer.

And, really, someone could close this issue.  :)
