### ISSUE TITLE
Prevent selection of line-returns in command mode

### ISSUE THREAD

**Issue by mcolyer** [atom/vim-mode#2]
In vim, you can only select line returns when in insert mode, as specified in this spec https://github.com/atom/vim-mode/blob/v0.1.0/spec/vim-mode-spec.coffee#L50-L59

I'm not exactly sure the best way to handle this given the current editor API. @probablycorey or @nathansobo any ideas on how to approach this?

**Comment by bronson** [comment]
Does this issue need to be fixed?  It seems like vim-mode is currently doing a great job of not allowing the cursor to ever reach the newline.  Do we need another layer of defense?

**Comment by bronson** [comment]
aha, clicking can place the cursor over the newline.  Very few vimmers will notice.  :)  Anything else?

**Comment by jacekkopecky** [comment]
I have noticed and it's annoying, it's on my list but nowhere near the top.
