### ISSUE TITLE
Cursor movement "l" key stop working when the cursor enters  double bracket blocks

### ISSUE THREAD

**Issue by RDash20** [atom/vim-mode#203]
Cursor movement "l" key stop working when the cursor enters  double bracket blocks.
```
"l" key works here
{{ "l" key doesn't work here }}
```

**Comment by izuzak** [comment]
I just tried reproducing this with various examples using hard tabs, and wasn't able to. I believe this was fixed in https://github.com/atom/vim-mode/pull/406, so I'm closing the issue. If anyone can still reproduce in Atom 1.0.11 -- let me know and please provide an example. :v: :doughnut:
