### ISSUE TITLE
Splits documentation is 404

### ISSUE THREAD

**Issue by creatovisguru** [atom/vim-mode#212]
https://github.com/atom/vim-mode/blob/master/docs/splits.md

This returns a 404 currently.

**Comment by bronson** [comment]
It was replaced by windows.md: https://github.com/atom/vim-mode/commit/6166a4ceaa2e8d94667ab5cbbf78340b3af63353

Does anything link to splits.md anymore?  I don't see anything when grepping the repo.

**Comment by kevinsawicki** [comment]
Closing this out since the doc has been removed, please comment if you know of places linking to it that still need to be updated.
