### ISSUE TITLE
arpeggio key combinations? (for 'jk' smash escape)

### ISSUE THREAD

**Issue by docwhat** [atom/vim-mode#221]
I use [Arpeggio](http://www.vim.org/scripts/script.php?script_id=2425) to implement a reliable 'jk' smash escape: `Arpeggio inoremap jk  <Esc>`

I tried the usual:

    inoremap jk <esc>
    inoremap kj <esc>

...but I kept running across variables/words that had `jk` and `kj` in them which would totally kill my concentration (and randomly change things :grinning: ).

I have to use a smash escape because the escape key on my mac book pro was causing me massive wrist pains.

**Comment by neiled** [comment]
Just to note for the original request, j j for me works like:

`'atom-text-editor.vim-mode:not(.command-mode, .visual-mode)':`
`  'j j': 'vim-mode:activate-command-mode'`

**Comment by drbraden** [comment]
Here is a currently working method of exiting insert mode with "jj" (or the more common "jk" with a minor edit to the keymap.cson change):

```coffee
#init.coffee
atom.commands.add 'atom-text-editor', 'exit-insert-mode-if-proceeded-by-j': (e) ->
  editor = @getModel()
  pos = editor.getCursorBufferPosition()
  range = [pos.traverse([0,-1]), pos]
  lastChar = editor.getTextInBufferRange(range)
  if lastChar != "j"
    e.abortKeyBinding()
  else
    editor.backspace()
    atom.commands.dispatch(e.currentTarget, 'vim-mode:activate-command-mode')

#keymap.cson
'atom-text-editor.vim-mode.insert-mode':
  'j': 'exit-insert-mode-if-proceeded-by-j'
```
Credit for this goes to babygau and his gist @ https://gist.github.com/babygau/ada61d690942ffaf345a

**Comment by lambdaburrito** [comment]
@drbraden Thanks for the code snippet! I wanted to map 'jj' to escape in Atom and you've saved me a lot of time :+1:

**Comment by drbraden** [comment]
@lambdaburrito Glad to hear it!  I've spent way too much time chasing down a solution for this, or finding a new one after a breaking upgrade, so I was hoping I could save others the time :smile:

**Comment by AriaMinaei** [comment]
Thanks @drbraden! Here is a one-line modification of your code snippet, using `editor.buffer.undo()` instead of `editor.backspace()` to preserve selections:
```coffeescript
#init.coffee
atom.commands.add 'atom-text-editor', 'exit-insert-mode-if-proceeded-by-j': (e) ->
  editor = @getModel()
  pos = editor.getCursorBufferPosition()
  range = [pos.traverse([0,-1]), pos]
  lastChar = editor.getTextInBufferRange(range)
  if lastChar != "j"
    e.abortKeyBinding()
  else
    editor.buffer.undo()
    atom.commands.dispatch(e.currentTarget, 'vim-mode:activate-command-mode')

#keymap.cson
'atom-text-editor.vim-mode.insert-mode':
  'j': 'exit-insert-mode-if-proceeded-by-j'
```

**Comment by AriaMinaei** [comment]
Looks like `editor.buffer.undo()` undoes keystrokes in batch, so, ignore my last comment :)

**Comment by maxbrunsfeld** [comment]
We've fixed this bug. In the next Atom release, you'll just have to do this:

```coffee
'atom-text-editor.vim-mode.insert-mode':
  'j j': 'vim-mode:activate-normal-mode'
```

**Comment by SurenderLohia** [comment]
+1
