### ISSUE TITLE
Linux—Keybindings using shift don't work

### ISSUE THREAD

**Issue by MattWindsor91** [atom/vim-mode#222]
Not sure if this is a problem with vim-mode or with atom itself, but I'll file it here first.

Any key-bindings vim-mode has that use shift don't seem to work on Linux, or at least not on my installation.  I haven't yet tried to reproduce on other systems and it could be a peculiarity to my setup (Gentoo x64 with xmonad).

Looking at the key binding resolver, this is because they are being unpacked as ‘shift-(unshifted key)’, whereas the bindings in vim-mode are of the form ‘(shifted key)’.  For example, vim-mode:outdent is bound to ‘<’, but doesn't work because when I type < it gets interpreted as ‘shift-,’.  Manually rebinding it to ‘shift-,’ in the user keybindings works.

I'm new to atom, so I'm not sure what the best way of fixing this would be if it is indeed a vim-mode issue.  Could there just be another set of key-bindings in terms of ‘shift-(unshifted key)’ added alongside the ‘(shifted key)’ ones?

**Comment by ipuustin** [comment]
I'm seeing this issue with Finnish keyboard layout (on Windows though). Some keys work properly with shift and some do not. It might have to on how they happen to match the keys on US keyboard layout. The indentation (less than, greater than) keys, star (*) and the braces are not working, while % is working. I think none of the keys that use AltGr (like AltGr-4 needed for $) are working. The Finnish keyboard layout looks like this: http://en.wikipedia.org/wiki/QWERTY#/media/File:KB_Finnish_Multilingual.svg

**Comment by jduval** [comment]
Same issue on Ubuntu with a french keyboard layout.
![kbd_french](https://cloud.githubusercontent.com/assets/1597299/7255501/03ca38cc-e84a-11e4-92e9-98871d21a034.gif)

For example, `$` doesn't work but `shift + 4` works to move to last character of line.
It seems that vim's bindings work only with US keyboard layout.

**Comment by markrendle** [comment]
Just figured out that the reason pressing `~` to toggle case isn't working is that in vim normal mode, that key on my UK keyboard is resolving to `"`. For some reason, in not-insert mode, all the keys are resolving using US layout.

**Comment by Kannen** [comment]
@markrendle Try to install the package keyboard-localization. This is an atom bug.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
