### ISSUE TITLE
error with Soft Wrap 

### ISSUE THREAD

**Issue by dark-lbp** [atom/vim-mode#231]
when enable 'soft wrap' & 'Soft wrap at Preferred Line length' ，if the line be wrapped。'vim mode' raise this error 'Uncaught TypeError: Cannot read property 'length' of undefined'

**Comment by izuzak** [comment]
Just tried reproducing this with various examples using soft wrap and wasn't able to. I believe this was fixed in #406, so I'm closing the issue. If anyone can still reproduce in Atom 1.0.11 -- let me know and please provide an example.
