### ISSUE TITLE
'Uncaught TypeError' when autocomplete-plus package enabled

### ISSUE THREAD

**Issue by jasper-fu** [atom/vim-mode#255]
When I using 'df', 'cf', even 'f' command, the console will appear to show 
```shell
Uncaught TypeError: Object #<Input> has no method 'execute'
```
![screen shot 2014-05-17 at 12 02 13 pm](https://cloud.githubusercontent.com/assets/233379/3004106/0f702728-dd78-11e3-842e-af96664b958b.png)

**Comment by izuzak** [comment]
Just tried reproducing this and wasn't able to. Also, the autocomplete-plus package replaced the default autocomplete package and lots of issues were fixed, so I'm guessing this was fixed at some point. 

Let me know if anyone can still reproduce the problem and please provide an example.
