### ISSUE TITLE
Motion for end of line ($)

### ISSUE THREAD

**Issue by pengux** [atom/vim-mode#260]
The dollar sign to move the cursor to the end of line doesn't seems to be working/implemented yet

**Comment by LudwikJaniuk** [comment]
Two years later, i'm having the same issue. Note that I'm on a sweish keyboard, so ($) is done by pressing (alt-4) if that's relevant. I tried disabling that defualt keybinging but it did not help. Pls fix.

**Comment by LudwikJaniuk** [comment]
Oh this is interesting. vim-mode-plus seems to be interpreting shift-4 as ($), and then is works. But this is not how I type ($)!

**Comment by LudwikJaniuk** [comment]
A solution for anyone who finds this in the future: install the [keyboard-localization](https://atom.io/packages/keyboard-localization) package. Fixed my problem completely. So this is all probably not vim-mode's fault.
