### ISSUE TITLE
Selection in visual mode skips a character when selecting to the left.

### ISSUE THREAD

**Issue by abijr** [atom/vim-mode#261]
Cursor at `A`:
![screenshot from 2014-05-21 13 36 29](https://cloud.githubusercontent.com/assets/102641/3045640/5ca7fe08-e11f-11e3-8958-dbe7b2bf4789.png)
Move right:
![screenshot from 2014-05-21 13 36 48](https://cloud.githubusercontent.com/assets/102641/3045641/5cabf0da-e11f-11e3-8fc5-ee5b429ce565.png)
Move left:
![screenshot from 2014-05-21 13 37 10](https://cloud.githubusercontent.com/assets/102641/3045642/5cb03988-e11f-11e3-9b7d-35d02b8d89ef.png)

I expect the visual-mode to select the `A` in `Atom`.

**Comment by maxbrunsfeld** [comment]
I believe this is fixed. Please report if it's still a problem.

**Comment by james147** [comment]
Working as expected here, thanks.
atom: 0.168.0 
vim-mode: 0.25.0
