### ISSUE TITLE
Ctrl + [ clashes with editor:outdent-selected-rows on Win32

### ISSUE THREAD

**Issue by mcnicholls** [atom/vim-mode#263]
The win32 keymap maps Ctrl + [ to `editor:outdent-selected-rows` on win32. This mapping is specified in the win32 keymap.

This is my preffered way of escaping insert mode, but I'm not certain about how to fix it.
Maybe just make the vim keymap selector more specific than the win32 one?

The vim selector is `.vim-mode:not(.command-mode)`

The win32 selector is `.workspace .editor:not(.mini)`

**Comment by dukedave** [comment]
I just installed Atom today for the first time, on Ubuntu, and I am having a similar issue:

![selection_214](https://cloud.githubusercontent.com/assets/48232/14512701/32b3438e-0196-11e6-8b75-d6f7671767e7.png)

Can someone confirm that these are related, before I open another issue?
