### ISSUE TITLE
Paste text on to new line

### ISSUE THREAD

**Issue by carlosdcastillo** [atom/vim-mode#285]
Today I ran into this:
`this is a line of text`
-I stood on the `a` and hit <kbd>D</kbd>, then <kbd>o</kbd> and <kbd>escape</kbd> and <kbd>p</kbd>. It would not paste. I then started again
-I stood on the `a` and hit <kbd>v</kbd><kbd>$</kbd> <kbd>d</kbd> <kbd>o</kbd> <kbd>escape</kbd> <kbd>p</kbd>. It would not paste. I then tried again.
-I stood on the `a` and hit <kbd>v</kbd><kbd>$</kbd> <kbd>y</kbd> <kbd>o</kbd> <kbd>escape</kbd> <kbd>p</kbd>. It would not paste.
-I stood on the `a` and hit <kbd>y</kbd><kbd>y</kbd> <kbd>o</kbd> <kbd>escape</kbd> <kbd>p</kbd>. It would not paste.

The only way I was able to work around it was by hitting <kbd>o</kbd> first (i.e. having the destination line be there before I copied on to the clipboard) and then standing on `a` then using any method to copy, and finally not using <kbd>o</kbd> to create a new line, but hitting <kbd>escape</kbd> and <kbd>j</kbd>, and finally pasting.

**Comment by maxbrunsfeld** [comment]
I believe this has been fixed. Please let me know if you're still having issues with these commands. Thanks!
