### ISSUE TITLE
when in visual characterwise mode, doing shift-G should only start selecting from the cursor position and not the whole line

### ISSUE THREAD

**Issue by erwinmombay** [atom/vim-mode#291]
Atom
![](https://i.imgflip.com/98ftk.gif)

vs

Vim

![](https://i.imgflip.com/98fuf.gif)

it should also stop at the first word of the last row when selecting. (the current implementation also doesn't do this, it currently stops at the last column of the last row)

**Comment by maxbrunsfeld** [comment]
I believe this is fixed via #477.
