### ISSUE TITLE
Insert multi-cursor from visual mode

### ISSUE THREAD

**Issue by TEugen** [atom/vim-mode#297]
I have setup `'ctrl-f': 'find-and-replace:select-next'`

In visual mode I select a word when I press `ctrl-f` it selects 2 separate words. When I press `i` it adds a caret only after the last selection, could it be possible to insert multiple carets?

![screen shot 2014-06-03 at 10 49 48](https://cloud.githubusercontent.com/assets/147790/3157412/b24f4036-eaf3-11e3-9f24-8c90277b9a44.png)

What I've noticed is when 2 separate words are selected and I press `backspace` in visual mode, it adds 2 carets that are in visual mode, so I can move around and select with `hjkl`, but when I press `i` it removes a caret and puts the last on in insert mode.

**Comment by maxbrunsfeld** [comment]
I believe this was fixed by #477.
