### ISSUE TITLE
Vim-Mode Cursor Missing

### ISSUE THREAD

**Issue by pretzelmaker** [atom/vim-mode#300]
While in vim-mode the cursor is completely missing which provides no way of knowing where you're at without looking at your position coordinates. I'm running Atom 0.100.0 with vim-mode 0.10.1.

**Comment by maxbrunsfeld** [comment]
Can you upgrade to the latest Atom and `vim-mode` and report whether or not this problem still occurs?

**Comment by pretzelmaker** [comment]
I am no longer using Atom actively and I suspect that the issue has likely been remedied in subsequent releases. Sorry I couldn't provide more information.
