### ISSUE TITLE
Idea: Add [linux] [windows] [mac] labels to help find system-specific issues

### ISSUE THREAD

**Issue by fotanus** [atom/vim-mode#305]
The title is self-explicative. :-)

**Comment by bronson** [comment]
@probablycorey is this really an enhancement?  I thought the ehhancement label referred to vim-mode features, not other github issues labels.  :)

That said, there don't seem to be many platform-specific bugs with vim-mode.

**Comment by fotanus** [comment]
Yeah, this post is way to old. If you say that isn't platform-specific bugs any longer, I'm happy closing it!
