### ISSUE TITLE
'dd' should leave cursor at first non whitespace character

### ISSUE THREAD

**Issue by trkoch** [atom/vim-mode#315]

**Comment by bronson** [comment]
Vim doesn't do this so I don't see why vim-mode should.

**Comment by bronson** [comment]
I'm wrong, default vim does exactly this.  Apparently one of my vim plugins changed it.  No desire to figure out which one, but a much stronger desire to lighten up my .vimrc....

So, I agree :+1: let's fix this :muscle:

**Comment by bronson** [comment]
Fix was easy, ready to merge.

**Comment by trkoch** [comment]
Thanks! :beers: Also a very readable diff to learn from.
