### ISSUE TITLE
commands as keybinds?

### ISSUE THREAD

**Issue by fotanus** [atom/vim-mode#319]
hi,

What about simply add a keybind like this:

    ': w enter': 'core:save'

While I understand this is not the best, it might "fill a hole" for now.
I have been using and is very effective for me. I even add `:n`, `:p` and `:A`.

**Comment by bronson** [comment]
Ha, very cool.  Luckily this isn't necessary anymore: https://github.com/lloeki/ex-mode

Well, ex-mode doesn't currently support :n, :p, or :A...  But it's very new.  How hard could it be?  :)

**Comment by fotanus** [comment]
Right, lets close this
