### ISSUE TITLE
r (replace) throws Uncaught Type Error

### ISSUE THREAD

**Issue by ptrckbrwn** [atom/vim-mode#320]
Whenever I use r to replace a character vim-state throws Uncaught Type Error.

![screen shot 2014-06-18 at 8 24 12 am](https://cloud.githubusercontent.com/assets/4147775/3313460/a1d5b248-f6e3-11e3-945a-595867e18a0c.png)

OS: OSX 10.9.3
Atom: 0.103.0
Vim-mode: 0.11.0

**Comment by jacekkopecky** [comment]
is this bug still there?

**Comment by nicolas-dular** [comment]
no, haven't noticed it for the last 1-2 months :)

**Comment by izuzak** [comment]
Just tried reproducing this and wasn't able to, and seems like other folks haven't seen this problem for a few months at least. Also, the autocomplete-plus package replaced the default autocomplete package and lots of issues were fixed, so I'm guessing this was fixed at some point.

Let me know if anyone can still reproduce the problem and please provide an example.
