### ISSUE TITLE
'd' with 'G' motions are not deleting the correct lines

### ISSUE THREAD

**Issue by daveenguyen** [atom/vim-mode#325]
`d` with `G` motions are also not working correctly.

**End of File**
dG (atom)
![dg-atom](https://cloud.githubusercontent.com/assets/2568174/3396346/2293fcc6-fd0d-11e3-8936-ef0fe1f9ef4d.gif)

dG (vim)
![dg-vim](https://cloud.githubusercontent.com/assets/2568174/3396348/2c1c69f4-fd0d-11e3-914a-38e808a7d5e1.gif)

**Going backward**
d2G from line 4 (atom)
![backward-d2g-atom](https://cloud.githubusercontent.com/assets/2568174/3396442/b624a84a-fd0e-11e3-92cb-81a0aaae0360.gif)

d2G from line 4 (vim)
![backward-d2g-vim](https://cloud.githubusercontent.com/assets/2568174/3396444/c007fda8-fd0e-11e3-9fe0-50ea2e2c8a07.gif)

**Going Foward**
d5G from line 3 (atom)
![forward-d5g-atom](https://cloud.githubusercontent.com/assets/2568174/3396456/e2f9db4c-fd0e-11e3-9a70-c87e7bbcb58c.gif)

d5G from line 3 (vim)
![forward-d5g-vim](https://cloud.githubusercontent.com/assets/2568174/3396458/e629d2b8-fd0e-11e3-8d13-68b150c33e92.gif)

**Same Line**
d4G from line 4 (atom)
![sameline-d4g-atom](https://cloud.githubusercontent.com/assets/2568174/3396462/fd2f747c-fd0e-11e3-8448-07c91a490625.gif)

d4G from line 4 (vim)
![sameline-d4g-vim](https://cloud.githubusercontent.com/assets/2568174/3396464/008228d6-fd0f-11e3-9adc-de57e2245209.gif)

**Comment by maxbrunsfeld** [comment]
Can you upgrade to the latest Atom and vim-mode and try again? If there is still a problem, can you open a new issue describing it specifically. I'm going to close this since the original issue is fixed. Thanks!
