### ISSUE TITLE
Control-v does not select a block of text it selects whole lines

### ISSUE THREAD

**Issue by jamescarniglia** [atom/vim-mode#327]
In vim control-v puts you in "visual block" mode allowing you to select multiple lines in a block.  in vim-mode control-v on multiple lines it does not select a block of text rather it selects whole lines.

**Comment by maxbrunsfeld** [comment]
Closing in favor of #468. Visual block mode is not yet implemented.

**Comment by sudostack** [comment]
any plans to implement this supremely useful feature?
