### ISSUE TITLE
Next/Prev paragraph { and } broken on files with dos line endings

### ISSUE THREAD

**Issue by chrisguilbeau** [atom/vim-mode#333]
Open a file with dos line endings, try to go to the next paragraph. Goes to the end of the line instead.

**Comment by geoffharcourt** [comment]
In files with non-dos line endings, I can't get the `{` to move up at all. '}` does move down by paragraph, but it behaves unpredictably (sometimes to the last character of the paragraph, sometimes to an empty line beneath. (Using 0.29)

**Comment by paulcbetts** [comment]
@geoffharcourt This seems to be a regression on the latest vim-mode, where it's now happening on both Mac and Windows, but only sometimes. On my machine, if I close the file and reopen it, it works again

**Comment by geoffharcourt** [comment]
@paulcbetts, I had the same problem on 0.27 yesterday, so I think the issue might be a less recent regression. Thanks for the heads-up.

**Comment by blablatros** [comment]
Any update on this issue? I'm using vim-mode v.0.61 on Windows, and `}` motion moves to the end of the line. When I convert the file to LF line endings, `{` and `}` work as expected.

**Comment by paulcbetts** [comment]
This bug kills me in the soul

**Comment by maxbrunsfeld** [comment]
I think this is fixed via atom/atom#9937. It will be out in Atom versions 1.4.0 and 1.4.0-beta0.

**Comment by paulcbetts** [comment]
Bless u @maxbrunsfeld, bless u
