### ISSUE TITLE
Always doubling the action

### ISSUE THREAD

**Issue by bhgames** [atom/vim-mode#338]
Whenever I delete or paste, it seems to paste twice or delete twice(i.e. the line I intended and the line below it.) This just happened with my recent upgrade from 0.8.1 to 0.11. something

**Comment by maxbrunsfeld** [comment]
I believe this was fixed via 33ec1f55a7e6f678ab059c8249e8197edbf7f736. There is still an issue on upgrading `vim-mode`, but this is captured in a more specific issue, #480.
