### ISSUE TITLE
It is very slow to close a tab using ctrl-w

### ISSUE THREAD

**Issue by shafreeck** [atom/vim-mode#352]
It takes about 3 or more seconds to close a tab with `ctrl-w`, but with mouse is OK

**Comment by langri-sha** [comment]
Thank you all for the clarification. The powerhouse behind `ctrl+w <key>` looks amazing. Unfortunately, the 3 second wait when pressing `ctrl+w` led me to believe something was broken with `atom/vim-mode`.

**Comment by ssfrr** [comment]
Seems like this can be closed, though I'm glad the discussion was here because I was wondering why it was happening as well, and now it makes sense.

It's funny because I also commonly use the ctrl-w <key> shortcuts for moving around in splits and my brain didn't even connect that they were related. :smile:

**Comment by Valve** [comment]
What if I still want the tab to be closed immediately with Ctrl-w? I cannot get it to work.
Here is my bindings file: 
```
'atom-text-editor.vim-mode:not(.insert-mode)':
  'ctrl-c': 'core:copy'
  'ctrl-v': 'core:paste'
  'ctrl-a': 'core:select-all'
  'ctrl-w': 'core:close'
```

**Comment by ssfrr** [comment]
you'll need to disable any of the other keybinding sequences that start with `ctrl-w`

**Comment by lemongrassnginger** [comment]
This works for me:

```
# ctrl-w close vim-mode waiting for ctrl-w <key> before closing
'atom-text-editor.vim-mode:not(.insert-mode)':
  'ctrl-w left': 'unset!' #'window:focus-pane-on-left'
  'ctrl-w right': 'unset!' #'window:focus-pane-on-right'
  'ctrl-w up': 'unset!' #'window:focus-pane-on-up'
  'ctrl-w down': 'unset!' #'window:focus-pane-on-down'
  'ctrl-w h': 'unset!' #'window:focus-pane-on-left'
  'ctrl-w l': 'unset!' #'window:focus-pane-on-right'
  'ctrl-w k': 'unset!' #'window:focus-pane-on-up'
  'ctrl-w j': 'unset!' #'window:focus-pane-on-down'
  'ctrl-w w': 'unset!' #window:focus-next-pane
  'ctrl-w p': 'unset!' #window:focus-previous-pane
  'ctrl-w v': 'unset!' #pane:split-right
  'ctrl-w s': 'unset!' #pane:split-down
  'ctrl-w c': 'unset!' #pane:close
  'ctrl-w q': 'unset!' #pane:close
  'ctrl-w ctrl-h': 'unset!' #'window:focus-pane-on-left'
  'ctrl-w ctrl-l': 'unset!' #'window:focus-pane-on-right'
  'ctrl-w ctrl-k': 'unset!' #'window:focus-pane-on-up'
  'ctrl-w ctrl-j': 'unset!' #'window:focus-pane-on-down'
  'ctrl-w ctrl-w': 'unset!' #window:focus-next-pane
  'ctrl-w ctrl-p': 'unset!' #window:focus-previous-pane
  'ctrl-w ctrl-v': 'unset!' #pane:split-right
  'ctrl-w ctrl-s': 'unset!' #pane:split-down
  'ctrl-w ctrl-c': 'unset!' #pane:close
  'ctrl-w ctrl-q': 'unset!' #pane:close
```

**Comment by AsaAyers** [comment]
The keymap approach didn't work for me. Maybe I'm just not finding all of the combinations I need to `unset!`.

https://atom.io/docs/api/v1.10.2/KeymapManager the `.keyBindings` property isn't documented here, so I assume it isn't intended to be part of the public API and I shouldn't be messing with it. And with that out of the way, I added this to my `init.coffee` and now `ctrl-w` closes the tab immediately.

```coffee
atom.keymaps.keyBindings = atom.keymaps.keyBindings.filter(
  ({keystrokes}) -> not keystrokes.match(/ctrl-w\s/)
)
```

**Comment by lemongrassnginger** [comment]
Yeah, that's a much neater way :)

**Comment by webberwang** [comment]
@AsaAyers thanks been looking for this solution all over the web

**Comment by DavidGretzschel** [comment]
@samlambert 
oh this finally makes sense! Thank you!
Is there any reason, though, that this (or any) shortcut is shown for close tab,
when searching for it in the command palette or is that a bug, I should report (and where should I report it)?

**Comment by bevinhex** [comment]
New update to the vim plus almost ruined my day, it was really annoying to close tabs
@AsaAyers  thanks for saving my atom.
