### ISSUE TITLE
{ and } do not scroll in linewise visual mode

### ISSUE THREAD

**Issue by jspahrsummers** [atom/vim-mode#374]
**Version:** Atom 0.120.0, vim-mode `v0.12.0-7-g02e1a0a`
**Steps:**

 1. Enter visual mode with Shift-V
 1. Starting from the middle of a scrollable buffer, repeatedly select blocks of text with `{` or `}`

**Expected:**
Scroll position moves as the selection expands.

**Actual:**
Selection continues off-screen. This doesn't affect characterwise visual mode or normal mode.

**Comment by maxbrunsfeld** [comment]
I think this was fixed via #477.
