### ISSUE TITLE
Quote text objects are naive

### ISSUE THREAD

**Issue by benmccormick** [atom/vim-mode#379]
I was trying out vim-mode today, and it seems much further along than last I tried it.  Good work!  One issue that did trip me up coming from Vim:

With a chunk of code like this:

```javascript
var x = "example",
      y = "example2";
```

in Vim if my cursor is resting on the `y` character and I type `ci"` to change the text in the nearest quote object, it will move me inside the "example2" string and empty it. 
When testing on Atom, it seems to naively seek out the nearest quote in each direction, resulting in

```javascript
var x = "example1""example2";
```

The original Vi/Vim behavior seems to make more sense, or at least do nothing if you're not currently inside a quote block.  Deleting between unrelated quotes seems wrong.

**Comment by maxbrunsfeld** [comment]
Closing this since it was fixed by @benmccormick's own PR, #419.
