### ISSUE TITLE
gg (move to start) is not working.

### ISSUE THREAD

**Issue by yz0075** [atom/vim-mode#389]
OS: Ubuntu 14.04LTS
Atom: 0.124.0
vim-mode: 0.14.0

I've built Atom from source onto Ubuntu 14.04LTS, installed vim-mode with apm, and tried using `gg` to go to the 1st line and `# gg` to go to a line # and neither worked.  `shift+g`, however, works for me.

**Comment by maxbrunsfeld** [comment]
I believe this currently works; I don't know when it was fixed though. Please let me know if there are still problems with it.

**Comment by gepoch** [comment]
gg is working! I suspect there are some other issues in the key resolver, but I'll make a seperate ticket with more specific details :)
