### ISSUE TITLE
L key not working - Cause related to tab characters

### ISSUE THREAD

**Issue by ecnahc515** [atom/vim-mode#391]
When a line starts with tabs, the L key will not go to the end of the line. It will short stop at a distance relative to the number of tabs at the beginning of the line.

If you use spaces, this behavior disappears.

**Comment by bronson** [comment]
This appears fixed.  Close perhaps?

**Comment by DavidLGoldberg** [comment]
This has long been fixed.  I submitted a pull request, and @nathansobo was ultimately the author of the fix, this should be closed to my knowledge.

**Comment by nathansobo** [comment]
Appreciate the ping.

**Comment by DavidLGoldberg** [comment]
:+1:
