### ISSUE TITLE
Repeat (.) while matching completion is enabled can lead to erroneous inserts

### ISSUE THREAD

**Issue by greg-hellings** [atom/vim-mode#392]
I was replacing a word of text with a method invocation in a PHP file. To do this, I was in command mode and press "c-w", then enter the text which involved both a method invocation and a string literal, for example:

method('mystring')

I then moved to another place where I wished to make the same substitution and pressed ".". The resulting text was

method()''mystring

PHP is configured to auto-close parentheses and quotation marks, likely leading to this strange behavior.

**Comment by peterjeliot** [comment]
I'm experiencing the same bug with quotation marks in ruby.

**Comment by maxbrunsfeld** [comment]
I believe this was fixed by #712.
