### ISSUE TITLE
Improvement: Visual Notification between modes similar to vim flight

### ISSUE THREAD

**Issue by cocodrino** [atom/vim-mode#402]
Hi..is hard know when I'm in edit mode or normal mode, I need check the little cursor for that...would be great if you could implement some kind of notification like vim flight...thank you!!...

**Comment by maxbrunsfeld** [comment]
There's the status bar indicator that switches from `Insert` to `Command`. Would it help if this thing changed color?

**Comment by michaellenahan** [comment]
Hi, I'm using atom/vim-mode on Ubuntu Linux 14.04.
I can't see any Insert or Command in the status bar.
Unless I'm missing something, I can't see any indicator of the mode I am in.
Anything would help! :) At the moment I usually just 
![atom-vim-mode-no-indicator](https://cloud.githubusercontent.com/assets/219397/6430810/b5a50516-c01a-11e4-8af5-d1f2ed865d2a.png)
type 'j' and see what happens. :)

**Comment by maxbrunsfeld** [comment]
@michaellenahan you're using a pretty old version of Atom. Try upgrading to 0.184.

**Comment by michaellenahan** [comment]
@maxbrunsfeld thanks, hadn't realised how out of date my Atom was. Upgraded it from https://github.com/atom/atom/releases.

As far as distinguishing insert and command mode, the fat cursor in command mode is all the help I, personally, need.

![atom-vim-mode-fat-cursor](https://cloud.githubusercontent.com/assets/219397/6432361/a9b36e1c-c04e-11e4-8d2e-b5d1abfd2d07.png)

Sorry for diverting the thread.

**Comment by jacekkopecky** [comment]
Hi, should this issue be marked closed?

**Comment by maxbrunsfeld** [comment]
Yeah, haven't heard back from @cocodrino or @bradleyflood. We can reopen if this is still a problem for you two.
