### ISSUE TITLE
Move through the autocomplete using ^J/K

### ISSUE THREAD

**Issue by Industrial** [atom/vim-mode#415]
Hi.

I'd love to move through the auto complete list using CTRL+J/K or CTRL+N/P. Is this possible?

gr,

Tom

**Comment by maxbrunsfeld** [comment]
You can do in your own personal config. Add this to your `config.cson`:

```coffee
'.autocomplete atom-text-editor[mini]':
  'ctrl-j': 'core:move-down'
  'ctrl-k': 'core:move-up'
```

**Comment by Industrial** [comment]
Thanks!

**Comment by asfktz** [comment]
this one works with atom 1.8.0

```cson
'.autocomplete-active':
  'ctrl-j': 'core:move-down'
  'ctrl-k': 'core:move-up
```

**Comment by BohanHsu** [comment]
Hi guys, I figure out the hack way to do that. I'm using the vim-mode-plus plugin, and have to following config

'.autocomplete-active':
  'ctrl-n': 'core:move-down'
  'ctrl-p': 'core:move-up'

'atom-text-editor.vim-mode-plus.insert-mode:not(.autocomplete-active)':
  'ctrl-n': 'autocomplete-plus:activate'
  'ctrl-p': 'autocomplete-plus:activate'
