### ISSUE TITLE
Change inner tag not working

### ISSUE THREAD

**Issue by isaachess** [atom/vim-mode#418]
`cit` and `dit` should work with vim tag-blocks, but are not implemented.

**Comment by bradleyflood** [comment]
+1 for `cit` and `dit` which I use very frequently as a front-end dev.

**Comment by jeffschwartz** [comment]
+ 1

**Comment by joshmedeski** [comment]
+1!

**Comment by jeffschwartz** [comment]
+1

**Comment by neiled** [comment]
:+1:

**Comment by maxbrunsfeld** [comment]
This has been implemented in #547. It doesn't exactly match vim's behavior but it's pretty good.

**Comment by bradleyflood** [comment]
Excellent thank you

**Comment by isaachess** [comment]
@maxbrunsfeld No offense, but I greatly disagree -- currently implementation of change-inner-tag is basically useless, doesn't work like vim at all. I would rather have it not implemented than its current state, where the behavior feels pretty unpredictable.

Either way, I think we should still have an open issue for this, to get it to match vim's actual feature.

**Comment by maxbrunsfeld** [comment]
@isaachess sounds great. Feel free to open an issue.

**Comment by collegeimprovements** [comment]
:+1:  for `cit` and `dit`. It would also be great if for `ruby` files, you can implement method navigation `]m` and selection `vim` bindings.
