### ISSUE TITLE
Using dd doesn't copy end of line on single line

### ISSUE THREAD

**Issue by monokrome** [atom/vim-mode#421]
When using dd in Vim, newlines are copied even on single lines. In an empty file, this Vim macro can be used to demonstrate the issue: `iThis is a test.<ESC>dduppp`

**NOTE:** *&lt;ESC&gt; should be replaced with the escape key, which can not be rendered by GitHub's font in this case.*

In Vim, the output is as follows:

```
This is a test.
This is a test.
This is a test.
This is a test.

```

In Atom with vim-mode, however, it is this:

```
This is a test.This is a test.This is a test.This is a test.
```

**Comment by monokrome** [comment]
Thanks for looking into this. I feel like these types of basic concerns are essential to the Vim experience, and are an expectation for a lot of common tasks performed by Vim users. I think that just forgetting this would be a bit too sad, but writing a custom undo/redo system seems a bit messy. I wonder if Atom should (or maybe already does?) expose more flexible APIs for working with undo/redo?

**Comment by jacekkopecky** [comment]
I can't replicate the bug - is it still there?

**Comment by monokrome** [comment]
@jacekkopecky Thanks for looking into this. It looks like this was fixed recently along with another issue. I'll close the issue for now. Thanks! :)
