### ISSUE TITLE
Command mode view causes errors

### ISSUE THREAD

**Issue by rstacruz** [atom/vim-mode#429]
Pressing `r` or `/` gives off this error:

    Uncaught TypeError: undefined is not a function 
    vim-command-mode-input-view.coffee:63

It seems like `@editorContainer` is not available in *vim-command-mode-input-view.coffee*.

[source](https://github.com/atom/vim-mode/blob/master/lib/view-models/vim-command-mode-input-view.coffee#L63)

**Comment by maxbrunsfeld** [comment]
@rstacruz can you upgrade to the latest Atom and `vim-mode` and report whether or not this still happens? Thanks.

**Comment by izuzak** [comment]
Closing since this is super old, there were no reports from other users as far as I can tell, and no new information was provided in more than 6 months after we asked. 

@rstacruz Let us know if you can still reproduce this in Atom 1.0.11
