### ISSUE TITLE
Instead of emulating Vim...

### ISSUE THREAD

**Issue by trusktr** [atom/vim-mode#436]
I'd recommend starting up a headless instance of [neovim](http://neovim.org) and letting Atom's text area be a view controlled by both neovim and Atom.

Send all keystrokes to neovim and let neovim decide what needs to happen to the text buffer from those keystrokes, then receive neovim's view update and update Atom's text area. When a combination is not recognized by or mapped in neovim, neovim can send that back and Atom can take over (for example, command+c can be sent back to Atom, and Atom can send neovim a `y` or `yy` depending on the mode, etc. Or, if the keystroke combo comes back to Atom and would do a normal Atom operation, then do the operation on the Atom's text area, then send the the update to neovim.

One of neovim's main goals is to make a clean separation of core and view, so that anyone can easily integrate part or all of neovim's text-manipulation functionality into their own GUIs. But even though that's not finished yet, it's still possible to subscribe to neovim's (vim's) old GUI mechanism just like Gvim, MacVim, and several Qt-based vim GUIs do.

I've tried each and every vim emulation out there and I cannot leave vim for any of them. Emulators cannot compete with the customizations of my vimrc.

It would be so much awesome if you guys decided to support neovim's movement. As you said, this vim emulation is "far from finished (Vim wasn't built in a day)", and from what I've observed of every other emulation attempt, it might remain far from finished. Adopting neovim will get you closer to the end result faster, ultimately.

I'm not familiar with how Atom's plugin system works. Is it flexible enough to allow neovim integration as an Atom plugin?

**Comment by maxbrunsfeld** [comment]
I'm going to close this; I think it could be interesting, but should definitely be a separate package.
