### ISSUE TITLE
Selecting lines using Shift V # Shift G is broken

### ISSUE THREAD

**Issue by jeffschwartz** [atom/vim-mode#459]
**Problem behavior** : Depending on if # is greater or less than the currently selected line the results are different but both are broken. For instance, when # is greater than the currently selected line it is removed from the resulting selection. For example if my cursor is on line 12 and I select the line using Shift V and then I enter 15 Shift G the result is that lines 13 through 15 are selected.

**Expected behavior**: The currently selected line is included. Using my example from above, lines 12 through 15 are selected.

These are normal expectations when using Vim.

OS: Mac 10.10.1

**Comment by maxbrunsfeld** [comment]
I believe this is fixed as of 0.23. Let me know if you are still having issues.

**Comment by jeffschwartz** [comment]
Yes!!! Most gratefully it has and thank you. It had been a major PITA iynwim :)
