### ISSUE TITLE
triple fingers to select word then show dictioanay help not shown under OSX 10.10?

### ISSUE THREAD

**Issue by urmyfaith** [atom/vim-mode#463]
triple fingers to select word then show dictioanay help not shown under OSX 10.10?

**Comment by maxbrunsfeld** [comment]
How does this relate to `vim-mode`?

**Comment by izuzak** [comment]
Closing since no information was provided for over 6 months and it's not clear how this is related to vim-more. @urmyfaith -- please feel free to clarify.
