### ISSUE TITLE
Implement visual block mode

### ISSUE THREAD

**Issue by gosukiwi** [atom/vim-mode#468]
I can't seem to find an answer to this so sorry if it's duplicated, but I'd like to know if visual block mode is implemented, I tried setting a `ctrl-q` key binding to `blockwise-visual-mode` but I just get regular visual mode activated.

``` cson
'.editor.vim-mode.command-mode':
  'ctrl-v': 'vim-mode:activate-blockwise-visual-mode'
```

**Comment by maxbrunsfeld** [comment]
No, visual block mode is not currently implemented. It should be coming soon.

**Comment by cpadilla** [comment]
How soon is soon? Any updates?

**Comment by sudostack** [comment]
+1

**Comment by jeffschwartz** [comment]
+1

**Comment by ahmadseleem** [comment]
+1

**Comment by irrationalistic** [comment]
Hey, thought I'd link to this other package that seems to be pretty close to this feature. Not sure if there's any collaboration that can happen! https://github.com/k-yamada/block-selection-mode

**Comment by fbob** [comment]
To me this is the killer feature which prevent me to switch full time to atom
Anyway, great job guys :)
Thanks !

**Comment by paulcsmith** [comment]
I also would love to see this :+1:

**Comment by femueller** [comment]
+1

**Comment by rtsolv** [comment]
:+1:

**Comment by pthrasher** [comment]
I've got a basic (read: incomplete) implementation started here: #658 

I'd love to get some feedback / possible collaboration.

**Comment by t9md** [comment]
Here is dirty hack to emulate visual-block-mode using multi-cursor.
Not perfect solution, but this cover basic visual-block use case for me.

https://gist.github.com/t9md/736291fd22260b5c7de0

**Comment by ahmadseleem** [comment]
This is the best I found so far:
https://atom.io/packages/column-select

Still missing a toggle like your solution...
hopefully this could be ported to vim-mode here...

**Comment by t9md** [comment]
After I put above gist, I just started developing package and just released now.

https://atom.io/packages/vim-mode-visual-blockwise

This is dirty hack of about 4 hour, there must be a lot of improvement but now I'm sleepy...

Anyway, I haven't checked or used `column-select`, will check afterward.

**Comment by rodmax** [comment]
"""
To me this is the killer feature which prevent me to switch full time to atom
Anyway, great job guys :)
"""
 nothing more to add
+1

**Comment by shemerey** [comment]
+1 for this feature

**Comment by jacekkopecky** [comment]
You can try this, it works pretty well for me, most of the time:
#### Remap cmd-up and cmd-down to add a cursor 
init.coffee:
```
atom.commands.add "atom-text-editor", "my:add-cursor-down", ->
  addCursorInDirection(1)

atom.commands.add "atom-text-editor", "my:add-cursor-up", ->
  addCursorInDirection(-1)

addCursorInDirection = (dir) ->
  editor = atom.workspace.getActiveTextEditor()
  cursor = editor.getLastCursor()
  coords = cursor.getBufferPosition()
  newcoords = { column: cursor.goalColumn || coords.column, row: coords.row + dir }
  newcursor = editor.addCursorAtBufferPosition(newcoords)
  newcursor.goalColumn = cursor.goalColumn || coords.column
```
and in your keymap:
```
'atom-text-editor':
  'cmd-down': 'my:add-cursor-down'
  'cmd-up': 'my:add-cursor-up'
```
Press `esc` to remove all but the last cursor.
Copy&paste will only select the last selection, not all of them, so it doesn't do block text manipulation, but it works well for some tasks with columns.

**Comment by coolicer** [comment]
+1 for this feature

need it

**Comment by jackcasey** [comment]
:+1:

**Comment by barock19** [comment]
+1

**Comment by melevine** [comment]
+1 won't use atom without it

**Comment by RobertMaloney** [comment]
+1

**Comment by wolftune** [comment]
For reference, though not identical, just do Alt-Shift with the up arrow or down arrow in Atom to get multiple cursors, and that will work as you want for the example you do above. In many ways the multi-cursor mode in Atom is superior to Vim's rectangle selection (although both have some value). The multi-cursor thing works alongside Vim-mode already.

**Comment by jacekkopecky** [comment]
@wolftune can you please check for me what the Key binding resolver (toggled with `cmd-.` or in the Packages menu) shows when you press `alt-shift-up`? Thanks!

**Comment by wolftune** [comment]
@jacekkopecky editor-add-selection-above atom-workspace atom-text-editor:not([mini]) /usr/share/atom/resources/app.asar/keymaps/linux.json

**Comment by jacekkopecky** [comment]
Thanks @wolftune, that helps - I didn't know these commands were there. Still, I find the *multi-cursor* package enhances on the add selection functionality.

**Comment by wolftune** [comment]
I note that the operation we want is fully doable already, just do alt-shift up or down arrows to get all the lines, and then enter visual mode and move left and right.

The issue here that remains is basically the fact that visual block mode doesn't work as Vim users would expect because it fails to respond to normal up and down motions and create a rectangle. If Visual Block mode successfully added cursors, it would be, IMO, fine that only hard character-based movement commands keep true rectangles while other commands may end up with other shapes.

So, operations are doable without weird extra mapping. This request should be summarized as: make Visual Block mode actually work via adding extra cursors when moving up or down.

**Comment by wolftune** [comment]
Oops, I realize my assertion that things matched up wasn't as accurate as I thought. In Visual Block mode in Vim, I can skip past an empty line or a shorter line to get to a later thing in the same column. That skipping only works for empty lines in *regular* Atom multiple cursors and is glitchy for shorter lines, and such skipping doesn't work even for empty lines using the multi-cursor package operations.

**Comment by jacekkopecky** [comment]
Yes, VIM block mode is different from multiple cursors in several ways. We want block selection mode even if many of its uses can be done with multiple cursors instead. To get a real vim-like block selection mode, we'd need changes in Atom I think because currently it doesn't allow us to put a cursor or selections after the end of the line.

And then there's the fun of copy/paste with multiple cursors (likely in scope of #855) and copy/paste with block selections.

Yeah, if this isn't solved by next spring (when I'll next have a big chunk of free time), I just might take a stab. :smile:

**Comment by lexfrei** [comment]
+1

**Comment by t9md** [comment]
I'm the author of vim-mode-visual-block package, for the people who interest to built-in visual-block to vim-mode natively.

I built-in this feature with minor improvement into my [vim-mode-plus](https://atom.io/packages/vim-mode-plus) (forked vim-mode) package released this week.
NOTE: This package includes many experimental feature not natively supported in Vim and break some compatibility with vim-mode(e.g. command-name, selector-scope etc..).

**Comment by nic** [comment]
+1

**Comment by rkmarks** [comment]
+1

**Comment by femueller** [comment]
Thanks a lot! @t9md 
[vim-mode-plus](https://atom.io/packages/vim-mode-plus) and [vim-mode-plus-ex-mode](https://atom.io/packages/vim-mode-plus-ex-mode) are super helpful and fixed for me personally this issue.
Your contributions made Atom really valuable and for me personally it's now possible to replace it with vim.

**Comment by dragonxlwang** [comment]
wondering will vim-mode-plus and vim-mode-plus-ex-mode merged into atom's vim-mode any soon?

**Comment by feluxe** [comment]
+1

**Comment by lonre** [comment]
+1

**Comment by martin-svk** [comment]
+1

**Comment by zhangruiqian001** [comment]
https://atom.io/packages/vim-mode-visual-block

**Comment by dragonxlwang** [comment]
that one is deprecated

**Comment by trusktr** [comment]
As a vim user, I always felt like Atom/Sublime had advantages in their multi-cursor mode (and vice versa).

Is anyone here a wizard in both Vim and Atom (I'm am brand new to Atom) that can describe or show what interesting things can be one with VISUAL BLOCK mode that can't be done with multi-cursor mode, and vice versa?

**Comment by trusktr** [comment]
> that one is deprecated

Deprecated, but still works!

**Comment by sudostack** [comment]
@trusktr I recently switched to Spacemacs (Emacs with EVIL mode and some niceties) which has complete Vim emulation sans the plugin ecosystem. When I was using ST3, I had the Vintageous plugin that combined the power of visual-block selection and insert-mode. It allowed me to do things a bit quicker than in Vim using visual-block selection and substitutions.

**Comment by oddlyfunctional** [comment]
+1

**Comment by Silox** [comment]
👍

**Comment by dndln** [comment]
+1

**Comment by hyacinthus** [comment]
+1

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
