### ISSUE TITLE
Am I typing something to make my h, j, k, and d and arrow keys move by 2 lines or 2 characters instead of 1?

### ISSUE THREAD

**Issue by QuillyT** [atom/vim-mode#478]
This has been consistently happening after prolonged used of atom.
I'm not sure if I typed something for this to happen or if it's vim-mode or atom being weird.
I have been restarting Atom to set it back...

So I guess the first question is: **Am I typing a hot-key that causes this change?**
If so... does anyone know what it is or is there a log somewhere that I can view?
If not... what other information can I offer to help solve this problem?

**Comment by maxbrunsfeld** [comment]
@QuillyT, I haven't seen this yet. Does it happen in insert mode, or only in command and visual modes? Also, is it just `h`, `j`, `k`, `l` and the arrow keys, or are other motions like `b`, `w` etc affected also?

**Comment by maxbrunsfeld** [comment]
Also, are you using the latest Atom and the latest vim-mode? If not, can you try upgrading and report whether you still see this?

**Comment by joshuata** [comment]
I have seen this bug as well. All commands are performed twice, such as `d`, `x` and all of the movement commands. Restarting atom fixes the problem. Each time I have seen it has been following a vim-mode update.

**Comment by QuillyT** [comment]
Oh whew, I got click happy and started updating before I could check on `b`, `w`, and other keys. Just updated both atom and vim-mode. Will continue to report when this happens.

@joshuata when you say "following a vim-mode update" do you mean when you specifically go to update vim-mode from the settings/packages page? Or is vim-mode updating on it's own without me doing anything? If it's automatically happening how can I monitor that?

**Comment by QuillyT** [comment]
It just happened again. Still didn't catch exactly what I did immediately before though... 
But this time it's only happening on one file (before it was every file that was open).

`h`,`j`,`k`,`l` and arrow keys are messed up.
`b`, `e`, `w`, `d`, `x` are all doubling
`yw` then `p` posts 2 of the word that was yanked (doesn't yank 2 words... yanks the same word twice?)
`yy` then `p` posts 2 of the same lines (doesn't tanke 2 lines)
`/` brings up the search bar but any letters I enter just exist the search bar
`r` brings up a search bar, also can't enter any letters (can enter `.` though).

This is all happening in "Command" mode (or whatever it displays in the footer to the left of UTF-8.
I pressed `v` for Visual mode and it looked normal at first. But after pressing `esc` I pressed `v` again and now it highlights 2 lines with every vertical directional key that I press.

Closing the file and opening it again fixed the problem.

**Comment by QuillyT** [comment]
I found what's doing it.

When I move a file from one split pane window to another, it adds one "repeat" of each key. As in...
Move file from one pane to another, `j` takes me from line 1 to line 3
Move file back to original pane, `j` takes me from line 1 to line 4
Move file to other pane again, `j` takes me from line 1 to line 5

It has a similar effect on all the other keys as well.

Let me know if there is anything else I can do to help.

**Comment by maxbrunsfeld** [comment]
@QuillyT thanks a lot for investigating. I see it now; I'll fix it asap.

**Comment by maxbrunsfeld** [comment]
@QuillyT this is fixed on master. I'll release again today. Thanks a lot for your help.

**Comment by QuillyT** [comment]
@maxbrunsfeld happy to help and thanks for the fix!

**Comment by QuillyT** [comment]
Wanted to note that @joshuata's point still happens.
Duplicate VimStates are still being created when vim-mode is updated.
It happens for all files even after closing and re-opening them.

I'll create another issue for this :)

**Comment by maxbrunsfeld** [comment]
:+1:
