### ISSUE TITLE
Indent and Outdent no working 2

### ISSUE THREAD

**Issue by MrLeeh** [atom/vim-mode#479]
Unfortunatly I have to reraise issue #345. 

Actually if I use Atom on my Mac everything is fine. But under Windows Indent and Outdent is not working. I have a German keyboard layout. In **insert mode** I can write *>* and *<* with no problems. So it seems to me somehow that under Windows *Atom* always uses the English keyboard layout for *commands* and *shortcuts*.

**Comment by maxbrunsfeld** [comment]
@MrLeeh, I think this may be an issue with Atom-core, not this package. What happens if you add this to your `keymap.cson` and then type a `>`?

```coffee
'*':
  '>': 'application:about'
```

**Comment by MrLeeh** [comment]
I tried your proposed modification of *keymap.cson*. So when typing `>` the About dialog is not showing. Actually it is just writing `>`. If I use the *Key Binding Resolver* and press `>` it shows me the key `â`. So this actuallly seems like a *Atom-Core* problem to me now as well. Also it seems like no solution exists.

**Comment by maxbrunsfeld** [comment]
Ok, sorry about this. Would you mind opening an issue on [atom-keymap](https://github.com/atom/atom-keymap), stating that you can't bind the `>` key on windows with your German keyboard layout? Thanks!

**Comment by MrLeeh** [comment]
OK, anyway thanks for your help :)
