### ISSUE TITLE
'caw' command misbehaving

### ISSUE THREAD

**Issue by Fuffi** [atom/vim-mode#483]
Try to place your cursor just before the _ character in this text:
'some_whatever'

typing caw should start insert mode by deleting the text while keeping the special characters, what it does instead is to delete until next line and then start insert mode.

**Comment by jeffschwartz** [comment]
I've noticed that in general some of the motion commands (e.g. i,a,...) are still somewhat kind of janky.

**Comment by maxbrunsfeld** [comment]
Thanks @Fuffi, this is definitely a regression. @jeffschwartz, if you notice bugs in the other text-objects, could you post additional specific issues?

**Comment by jeffschwartz** [comment]
Will do.
