### ISSUE TITLE
loosing cursor when saving a file

### ISSUE THREAD

**Issue by wenlock** [atom/vim-mode#486]
Hi, I was wondering if anyone else is experiencing this problem or has a workaround.  Can't seem to find any similar issues.

Problem:

When editing a file, I save the file with ctrl-s, and the cursor which shows up as a block initially disappears.  I can still navigate with vim style navigation, but then i don't see where my cursor really is anymore.  Clicking on the window makes the block come back, so i can see where the cursor is again, but if i save the file again, the cursor reverts to a mode that appears like it's in insert mode, but I'm not really in insert mode.

This wasn't occurring in older versions of the vim plugin.

Packages installed:
/home/eraigosa/.atom/packages (28)
├── atom-copy-on-select@1.1.0
├── atom-lint@0.20.1
├── autocomplete-jedi@1.2.0
├── coffee-compile@0.8.4
├── coffee-lint@0.7.3
├── color-picker@1.2.6
├── execute-as-ruby@0.1.1
├── file-icons@1.4.4
├── git-plus@4.3.1
├── git-review@0.1.3
├── javascript-snippets@1.0.0
├── language-docker@1.1.2
├── language-javascript-semantic@0.1.0
├── language-puppet@0.10.0
├── linter@0.9.1
├── linter-flake8@1.2.0
├── linter-jscs@1.4.9
├── linter-puppet-lint@0.2.3
├── linter-rubocop@0.2.1
├── linter-ruby@0.1.4
├── merge-conflicts@1.2.8
├── minimap@3.5.4
├── node-debugger@0.2.3
├── npm-docs@0.2.0
├── project-manager@1.14.1
├── ruby-test@0.9.3
├── script@2.16.0
└── vim-mode@0.26.0

**Comment by wenlock** [comment]
update:  i've also tried this with all packages disabled, and just enabling vim-mode by itself.  Seems to give me the same behavior.

**Comment by maxbrunsfeld** [comment]
Can you open the key-binding resolver (`Key Binding Resolver: Toggle`) and report what it shows when    you are saving the file and the cursor is disappearing? Also, are you using the latest Atom? If not, can you update to the latest Atom and try again?

**Comment by wenlock** [comment]
Using atom 0.172.0 from http://ppa.launchpad.net/webupd8team/atom/ubuntu ppa on trusty

Here is what i see when i hit the toggle key binding

http://goo.gl/BaaYBK

I can probably figure out how to install 0.174.0 but that would require rebuilding atom and dropping the ppa, i was hoping to be able to keep that ppa.  Hoping it's not the ppa thats the issue.
https://launchpad.net/~webupd8team/+archive/ubuntu/atom

**Comment by maxbrunsfeld** [comment]
So the cursor disappears when you save the file with `ctrl-s` right? Is that screenshot what you see when you type `ctrl-s`? It looks from that like you are typing `escape` there.

**Comment by wenlock** [comment]
@maxbrunsfeld The mouse cursor doesn't disappear.   Here is a short little web clip on what i see.
http://goo.gl/e09cHy

Steps im using

1) hit i to go into insert mode, type some test
2) hit escape, open another line, more text
3) hit ctrl-s , and the file saves, but the blinking cursor does not return.

**Comment by wenlock** [comment]
Here is another screen capture with keybinding toggled on.  http://goo.gl/HFRl8U

**Comment by wenlock** [comment]
It came across a little hard to read on my side... trying it again with resized window http://goo.gl/e9LJAG

**Comment by Industrial** [comment]
I am also having this issue, however it doesn't get triggered on save but rather when I focus another window and go back to atom the block cursor disappears. Clicking with the mouse in the document makes it appear again.

**Comment by wenlock** [comment]
Today i've re-installed my OS , and thus also re-installed atom and all my plugins.   I'm no longer able to reproduce or see this issue using 0.174.0.    Unless someone else can provide some way to reproduce it, I think for me the issue is closed.

**Comment by deiwin** [comment]
Could be related to atom/atom#3622 (@Industrial's issue definitely is). There's also a [workaround for vim-mode](https://github.com/atom/atom/issues/3622#issuecomment-75369143) in that thread.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
