### ISSUE TITLE
Regression with '%' matching

### ISSUE THREAD

**Issue by gittyupagain** [atom/vim-mode#487]
The '%' key no longer jumps to matching braces, brackets, and parentheses that occur on different lines as of the a6ea0dd (Clean up search motions) commit from v0.27.0.

**Comment by jeffschwartz** [comment]
I can confirm this.
+1

**Comment by maxbrunsfeld** [comment]
Thanks guys. I didn't actually know that vim did this, and we were missing tests for this case.
