### ISSUE TITLE
shift $ while in visual mode selects beyond end of line error

### ISSUE THREAD

**Issue by jeffschwartz** [atom/vim-mode#491]
Place editor into visual mode
![atomvim1](https://cloud.githubusercontent.com/assets/271288/5823943/d4cddf66-a0ae-11e4-9b3a-69d185c944a6.png)

shift $ to select to end of line - goes beyond end of line
![atomvim2](https://cloud.githubusercontent.com/assets/271288/5823947/dd7dbd48-a0ae-11e4-8e7f-b24c3c23d074.png)

**Comment by maxbrunsfeld** [comment]
This is the expected behavior. In vim's visual mode, the `$` motion moves the cursor beyond the end of the line, highlighting the newline. In Atom, selections that extend beyond the end of a line are displayed like this. To display them differently would require implementing an alternative selection system, which I don't think makes sense for this package. Functionally though, this behavior is the same as vim's. The difference is only cosmetic.

**Comment by maxbrunsfeld** [comment]
Let me know if you have any suggestions for how to improve this. Currently though, I don't see a good way.

**Comment by jeffschwartz** [comment]
I believe you are wrong about that. I've never seen that in vim. Here a pic of vim in the terminal with the same file:

![vim](https://cloud.githubusercontent.com/assets/271288/5828356/1bebfc6c-a0d1-11e4-99a7-7fcea0ce2411.png)

Big difference between real vim and atom. Atom extended the selection past the eol character, vim does not.

**Comment by maxbrunsfeld** [comment]
I'm pretty sure that in your screenshot, the selection extends beyond the end of the line. To test this:

1. Open a file with this text

```
line-1
line-2
line-3
```

2. Place cursor at the beginning of the `line-2`
3. Type `v $`
4. Type `d`
4. See that the line-break between `line-2` and `line-3` was deleted, leaving only two lines.

**Comment by james147** [comment]
You are right `v$d` deletes to the end of line including the line ending
resulting in the line bellow on the current line.

Note this is different from `d$` which does not delete the line ending.
This is inconsistent but it is also inconsistent in vim. So atom is showing
the correct yet annoying behaviour.

**Comment by jeffschwartz** [comment]
You are correct. I stand corrected. Perhaps it is the amount past the eol that is throwing me off in atom. In any case, I apologize for the false alarm. I'm really stoked by atom's vim emulation. Thank you for your support of this excellent plugin.

**Comment by maxbrunsfeld** [comment]
@jeffschwartz, no problem at all; thanks for participating in the issues on this project!
