### ISSUE TITLE
Pressing backspace twice puts you in command mode

### ISSUE THREAD

**Issue by fredkingham** [atom/vim-mode#492]
If you're in insert mode the first backspace deletes text, the second moves you to normal mode

**Comment by maxbrunsfeld** [comment]
I can't reproduce this. Can you report the output of the keybinding resolver (`Key Binding Resolver: Toggle`) when you press backspace twice?

**Comment by fredkingham** [comment]
not sure if it was due to stale code, its stopped happening, closing, (sorry!)

**Comment by Samsinite** [comment]
This is happening to me right now and is really frustrating :/. Just updated to the latest release today. It is only happening in one tab FWIW, not sure how easy this will be to reproduce.

Here is the output of the keybinding resolver

![screen shot 2015-02-11 at 2 21 26 pm](https://cloud.githubusercontent.com/assets/166847/6157811/7047043a-b1f9-11e4-8bb9-a3d2dcb72a44.png)

**Comment by Samsinite** [comment]
Close the tab and reopening the file makes these bug disappear.
