### ISSUE TITLE
[RFE] Add support for incremental search

### ISSUE THREAD

**Issue by ficoos** [atom/vim-mode#493]
```
While typing a search command, show where the pattern, as it was typed
so far, matches.  The matched string is highlighted.  If the pattern
is invalid or not found, nothing is shown.
```

For more: `:help incsearch`

**Comment by trkoch** [comment]
Incremental search would be terrific! Is it feasible? Maybe some inspiration can be found in a standalone search plugin for Atom, called [mkleehammer/atom-incremental-search](https://github.com/mkleehammer/atom-incremental-search).

**Comment by pencilcheck** [comment]
I'm missing this feature in vim as well, hopefully this will be implemented somehow. :+1:

**Comment by bronson** [comment]
Yes, this is a big one.  I don't think there's a need to implement a new keybinding and behavior like the incremental-search package.  Just make / work like vim and highlight the search results as you type.  (vim with :insearch set of course)

**Comment by davedan7** [comment]
+1

**Comment by jackcasey** [comment]
:+1

**Comment by wwju** [comment]
+1

**Comment by nonelove** [comment]
+1

**Comment by kenng** [comment]
+1

**Comment by tmunro** [comment]
For all those leaving +1s, this might tide you over: https://atom.io/packages/isearch

**Comment by hyouuu** [comment]
+1

**Comment by mitchellwrosen** [comment]
+1

**Comment by paggarw** [comment]
+1

**Comment by calebmeyer** [comment]
Could we steal the implementation of incremental search from here? https://atom.io/packages/vim-mode-plus

**Comment by LandonSchropp** [comment]
+1 I would love to see this added to vim-mode.

**Comment by stelioskiayias** [comment]
+1

**Comment by dsifford** [comment]
@calebmeyer Good tip - Switching to vim-mode-plus until this issue gets resolved :+1:

**Comment by lamuria** [comment]
+1

**Comment by mitchellwrosen** [comment]
People commenting with just "+1": since a month or so ago, you may now instead add a thumbs-up reaction to the issue description.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
