### ISSUE TITLE
Key resolver doesn't handle shift characters properly.

### ISSUE THREAD

**Issue by gepoch** [atom/vim-mode#495]
vim-mode: 0.29.0
atom: 0.175.0

I noticed this behavior quite some time ago (atom 0.130.0 ish?) but I'm just getting around to making this issue now.

It seems that the ambiguous key resolver is not dealing with the shift key correctly.

## Correct behavior:

Suppose I add the following to my keymap:

```
'.editor.vim-mode:not(.insert-mode)':
  'd w w': 'command-palette:toggle'
```

(Note: you'd have to be crazy to do this, but it illustrates the point well.)

Now I go to a piece of text and type [``d w w``]. The command palette opens!

Importantly however, if I just type [``d w``] and wait for a moment, it deletes the following word, just as one would expect! The resolver is doing its best to let me run my [``d w w``], times out, and deletes a word instead.

This illustrates the correct behavior of the resolver.

## The bug:

NOW if I change my configuration to this:

```
'.editor.vim-mode:not(.insert-mode)':
  'd w !': 'command-palette:toggle'
```

Now (in command mode in the editor), I type [``d w shift+1``] the _instant_ I hit shift to make an exclamation mark, vim-mode fires the ``delete-word``. What's more is that the key resolver will actually show my custom "command-palette:toggle" command in the list of potential commands, listing [``dw (partial)``] in the "Key Binding Resolver:" field at the top of the box.

It would seem that vim-mode's key binding resolver is interpreting the shift key event as its own key, not finding any commands for that in the search space, and taking the last unambiguous action that it knows how to do.

The above scenario is pretty absurd, but for a real life example, this is trampling my [vim-surround](https://github.com/gepoch/vim-surround) plugin's keybindings. Specifically in visual mode using vim surround [``s "``] SHOULD surround the selection in double quotes, but instead (on shift) triggers visual mode's [``s``] which executes ``vim-mode:change``. Rather than waiting for the shift+' it instantly falls through to the change command.

Thanks, and lemme know if I can provide any more information!

**Comment by james147** [comment]
This sounds like what we discovered in #403. It is not a bug with vim-mode, but one in atoms keymap see atom/atom-keymap#65 for more details.

**Comment by gepoch** [comment]
Ah! That bug definitely seems to cover this behavior!
