### ISSUE TITLE
Backspace exits insert mode

### ISSUE THREAD

**Issue by wrigleyster** [atom/vim-mode#497]
I upgraded from version 0.29 to 0.30, now pressing backspace in insert mode, deletes the character left of the caret and exits insert mode. Atom version: 0.176.0, Windows 7.

**Comment by fentas** [comment]
+1
ubuntu 14.04..
But for me is it not only Backspace also tab (for autocompleten).
This Bug makes it kind of unusable.

**Comment by Aldotroid** [comment]
+1 
OSX 10.10.1 (14B25)
Atom  0.176.0 (0.176.0)
vim-mode 0.30.0

**Comment by jeffschwartz** [comment]
I don't see this on my Macs, latest versions of everything.

**Comment by barwinco** [comment]
Didn't happen for me:

Linux
Atom 0.177.0-7add4af
vim-mode 0.30.0

**Comment by ZiaBhatti** [comment]
+1

OSX Yosemite.  Bad enough to make the entire thing unusable

**Comment by kmorey** [comment]
I had this problem (OSX Yosemite) and uninstalling and reinstalling the plugin fixed it for me.

**Comment by christophberger** [comment]
Same issue and same fix for Windows. Uninstall vim-mode, reinstall, restart Atom -> issue vanished.
(Still have to test this with my OSX and Lubuntu machines at home but I expect the solution to work there as well.)
Thanks kmorey for sharing your solution.

**Comment by bradleyflood** [comment]
Likely related to #522 
Removing package, restarting Atom and re-installing package fixed it for me.

**Comment by Sharpie** [comment]
+1 Just noticed this today after updating vim-mode from 0.36 to 0.37.

Atom 0.187.0
OS X 10.8.5

**Comment by highb** [comment]
Found on Atom 0.187.0/OSX 10.10.2 after upgrading to 0.38.
Removing, restarting, and re-installing also fixed it for me.

**Comment by bronson** [comment]
Sounds like this isn't a problem anymore...  consider closing this issue?
