### ISSUE TITLE
Add ex commands, including save

### ISSUE THREAD

**Issue by rgbkrk** [atom/vim-mode#50]
Many of the `ex` commands are critical to true `vi` heritage, including `:w`. From [wikipedia's article on `ex`](http://en.wikipedia.org/wiki/Ex_%28text_editor%29):

> ex was eventually given a screen oriented visual interface (adding to its command line oriented operation), thereby becoming the vi text editor.

We've got a lot of our movement commands, but it would be great to have our `:w`, `:%s`, `:g`.

Most of the movement commands are there, so I'm generally having a good time. Thanks for this package!

**Comment by fentas** [comment]
I would like to see this enhancement realized in some way. Seperate package would work for me also.
+1

**Comment by kristoiv** [comment]
+1 I def. want this! I keep hitting :w, and was sad not to be able to goto line using :<number>.

**Comment by darkshadow** [comment]
You guys are trying to reinvent how vim emulation should work ?. The whole point of vim emulation is to make it easy for vim users to work on atom. If there is no way to save a file using :w then it's not vim emulation. Why not just go ahead invent a novel alternative to pressing Escape ?.

Mean while I was waiting on this issue I went back to vim and have been playing around with spacemacs and tried other editors that have basic vim keybindings. Unsubscribing from this issue, I no longer want to get these +1 mails.

**Comment by nnjpp** [comment]
If it's in a different package, fine, but +1 on this being essential. This is muscle memory, and it's a misconception to think that many long-term vim users are interested in 'transitioning' their muscle memory to the atom way.

**Comment by joelmo** [comment]
Maybe the easiest would be to use the vim binary for this feature, just
send the command to it, let it execute and save. That way people can use
custom commands and use vimscripts.

**Comment by jeffschwartz** [comment]
@joelmo the problem seems to be that the vim module currently doesn't support all the commands (someone please correct me if I am mistaken about this). So acting as a delegate and calling into the vim module won't work.

**Comment by joelmo** [comment]
On Wed, Feb 4, 2015 at 5:20 PM, Jeff Schwartz <notifications@github.com>
wrote:

> @joelmo <https://github.com/joelmo> the problem seems to be that the vim
> module currently doesn't support all the commands (someone please correct
> me if I am mistaken about this). So acting as a delegate and calling into
> the vim module won't work.
>
The commands that vim-mode supports doesn't have to be delegated.

**Comment by jeffschwartz** [comment]
@joelmo so how can you save a file now just using vim emulation? I don't see a "save" option in the command palette. I'd guess if "save" were implemented then it would be exposed as would other ex commands and would show in the command palette, right?

**Comment by joelmo** [comment]
I don't understand what you mean. If atom supports opening external processes, then it could just execute /usr/bin/vim /path/to/file +CustomCmd +w +qa!, CustomCmd could be %substitute or anything. If those commands have to show up in the command palette there probably is a way to query them, ':command' in vim will list all user commands.

**Comment by jeffschwartz** [comment]
@joelmo that's my point, this isn't vim and currently vim emulation doesn't implement what the actions that external commands would need, like saving a file in response to :w - it doesn't do that now. I'm not saying it wouldn't be nice if it did. Either a separate ex command module will have to implement :w or the current vim module will have to implement it. Personally, I sort of like the idea of a separate ex command module but I'd be happy in either case. The bottom line for me is that I don't expect vim emulation to emulate every facet of Vim. If I wanted that then I'd just use Vim (and I do at times). Perhaps when Neovim is ready, then some enterprising UI person will craft a sweet GUI around it. Until then for me there's Atom with decent (but could be better) emulation and the real deal when I want it.

**Comment by gepoch** [comment]
FWIW, the key resolver is very awesome, and vim mode is quite happy to work with it.

This could be a good workaround for ya'll, if you weren't doing this already:

In your keymap.cson

```
'.editor.vim-mode:not(.insert-mode)':
  ': w enter': 'core:save'
```

And that's `:w` taken care of.

Some of the other commands may require more creativity, however. Not sure what to do for `:%s` You could launch atom's native find and replace though, as a productive step:

```
'.editor.vim-mode:not(.insert-mode)':
  ': w enter': 'core:save'
  ': % s enter': 'find-and-replace:show'
```

Again, not truly vim emulation, but it might be helpful to some for the time being.

**Comment by joelmo** [comment]
I agree that not everything have to be emulated, but I believe the core commands people are asking for is  substitute, global, sort, bufdo. All those, except last accept a regex, and also supports operating on ranges. I think it would be hard work to implement an emulation for these. This feature was suggested one year ago, but I don't feel like doing that work so I'm just using vim and follow some progress on neovim.

**Comment by jameydeorio** [comment]
This is the only issue keeping me from using Atom

**Comment by lloeki** [comment]
No one was stepping up so, ex-mode here. While there's only `w` and `write`, groundwork is done, so adding new commands is easy: https://atom.io/packages/ex-mode

**Comment by Tsarpf** [comment]
+1 This is the main thing that makes me not use Atom. I want :commands.

...But cool that finally someone has started working on the ex-mode.

**Comment by webduvet** [comment]
: commands are essential.
Simply life is not possible without them.
Atom is nice, fancy, great, has a lot of potential and I'm sure I could love it. (with :)

**Comment by flyingfisch** [comment]
ex-mode now supports `:s` as well. Could we add a link to ex-mode in the readme?

**Comment by bronson** [comment]
@flyingfisch you're too modest (: https://github.com/atom/vim-mode/commit/40e7f3d6fea306063e6249953954c0d873f345de

Does it make sense to close this in favor of opening bugs on ex-mode?  Or is there anything that still needs to be tracked here?

**Comment by rgbkrk** [comment]
I'm happy to close the issue now that I know about [ex-mode](https://atom.io/packages/ex-mode).

**Comment by flyingfisch** [comment]
@bronson yeah after i posted here i thought i would just do it the github way ;)

**Comment by rgbkrk** [comment]
Heh, I never closed this. I'll keep it open now that `ex-mode` is looking for maintainers: https://github.com/lloeki/ex-mode/issues/116

Perhaps there are contributors here that would like to help there (or bring over some of it?)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
