### ISSUE TITLE
Ctrl-R can not open tag list but insert an 'r' character

### ISSUE THREAD

**Issue by liugangnhm** [atom/vim-mode#502]
Ctrl-R can not open tag list but insert an 'r' character, and sometime with no response

**Comment by bronson** [comment]
I don't understand.  Ctrl-R redoes an edit, the opposite of undo, and it seems to work fine.  (?)

**Comment by liugangnhm** [comment]
sorry for my mistake, Ctrl-R is my own key-bind.
