### ISSUE TITLE
Rename command mode to normal mode

### ISSUE THREAD

**Issue by coolwanglu** [atom/vim-mode#504]
http://vimdoc.sourceforge.net/htmldoc/intro.html#vim-modes-intro

Although normal mode is indeed also known as the command mode, AFAIK, the term `normal mode` is used more often.

Also since we are now planning the command-line mode, renaming it would make them less confusing.

What do you say, I can make a PR for this.

**Comment by maxbrunsfeld** [comment]
Yeah I agree, `normal mode` is what I use most often. I'd merge said PR.

**Comment by coolwanglu** [comment]
@maxbrunsfeld  how does #508 look like?

**Comment by romgrk** [comment]
I would strongly suggest to fix this ASAP. As more code is written, it will take greater effort to correct this. `Command mode` should refer to the mode in the command bar.

**Comment by romgrk** [comment]
@maxbrunsfeld up

**Comment by bronson** [comment]
this is in master, can be closed.  :fireworks:

**Comment by thomasjo** [comment]
As mentioned by @bronson, this was resolved when https://github.com/atom/vim-mode/pull/508 got merged.
