### ISSUE TITLE
assert mechanism?

### ISSUE THREAD

**Issue by coolwanglu** [atom/vim-mode#509]
Throughout the project I cannot find a way of asserting something. 
What is the recommended way of doing this?

**Comment by maxbrunsfeld** [comment]
We don't use assertions in the code; we have a separate suite of specs that we use to verify the code's correctness; see the `spec` directory.

**Comment by coolwanglu** [comment]
What I understand is that specs are test suites, but assertions might be better for debugging. I came into some situations like this:

 `function test(a,b)` where either `a` or `b` must be `null`, and it might be able to test all the situations in the test suites. 

On the other hand, with an assertion in the function body, it will be auto breakpoint when something is wrong, which will allow us to find the caller.

**Comment by maxbrunsfeld** [comment]
>  it might not be able to test all the situations in the test suites.

Why would you not be able to?

> with an assertion in the function body, it will be auto breakpoint when something is wrong, which will allow us to find the caller

In *very* rare cases where a bug has been reported and we cannot reproduce it, we might introduce an extra `throw` statement in the way that you're talking about. Most of the time though, we don't do that.

**Comment by coolwanglu** [comment]
I think there are just too many combinations of user input, even if a specific keystroke sequence trigger the bug, say `a` and `b` are both null, the problem might appear in other places, then we need some time to pin point this function.

But it's ok if we don't do so in this project.
