### ISSUE TITLE
command input is not hidden for singleChar mode

### ISSUE THREAD

**Issue by coolwanglu** [atom/vim-mode#511]
The input box is still shown up when a single char is expected.
I'm not sure if `<input>` works with `visibility:hidden`, but we can move it out of the view, something like `top:100%`

**Comment by coolwanglu** [comment]
Example: the `m` motion.

**Comment by coolwanglu** [comment]
Or, how about implement singleChar mode separately, with just event handlers?

**Comment by coolwanglu** [comment]
I found that `register-prefix` is implemented by register multiple keymaps but `m` is implemented by receiving the register from a singleChar input, shall we unify them?

**Comment by maxbrunsfeld** [comment]
This used to work; I probably broke it in some refactoring. It shouldn't be a big deal to fix, I just haven't gotten around to it because I think the current behavior is ok too. I'd be really glad to merge a PR fixing it if you're interested.

**Comment by coolwanglu** [comment]
Yes, I agree that `singleChar` works for the input. Yet the problem is I'm trying to implement the command-line stuffs, and `singleChar` might make the logic more complex. 

I hope I can remove the singleChar mode, and register the keystrokes through keymap, such that it will be easier to add features for the input line. I'm just not sure if this would be OK, what do you think?

**Comment by coolwanglu** [comment]
Hmm I'm still thinking, maybe receiving the keystroke separately might be better, if we want to check the register key, we can `atom.beep()` if an invalid register is typed, and it also saves space in the keymap file.

Not sure what is the best way of integrating atom's keymap API

**Comment by coolwanglu** [comment]
I found that the `hidden-input` class is applied to the input, but it is not hidden. It is a built-in class in atom?

**Comment by jeffschwartz** [comment]
Now I'm forced to look at the bottom of the pane and it distracts me. So I'd love to see this hidden if possible.

**Comment by jacekkopecky** [comment]
seems to be working now, input field not showing for single-character-input commands, close the issue?

**Comment by maxbrunsfeld** [comment]
You're right; thanks, @jacekkopecky.
