### ISSUE TITLE
Why focus pane commands are implemented differently?

### ISSUE THREAD

**Issue by coolwanglu** [atom/vim-mode#512]
See https://github.com/atom/vim-mode/blob/master/keymaps/vim-mode.cson#L90

In vim help, `^w k` and `^w <up>` are the same.

**Comment by bronson** [comment]
This appears fixed?  They behave the same for me with the latest 0.200.0 and 0.48.0.

**Comment by kevinsawicki** [comment]
Looks like this was fixed by https://github.com/atom/vim-mode/commit/534c31d21954813d60488df36cc2dd6f292ff651
