### ISSUE TITLE
Cannot change modes between VISUAL and VISUAL LINE

### ISSUE THREAD

**Issue by learning** [atom/vim-mode#514]
I think this is a issue related to #465, I can't change modes between **VISUAL** and **VISUAL LINE**.
That means while I'm in **VISUAL** mode by `v` key, I can't switch to **VISUAL LINE** mode by uppercase `V`, or vice versa.

**Comment by t9md** [comment]
Sorry for this mess, I didn't noticed this mess, just wanted to fix my commit log, sorry I should learn git.
