### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by kindlychung** [atom/vim-mode#531]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
StatusBarManager.attach (/Users/kaiyin/.atom/packages/vim-mode/lib/status-bar-manager.coffee:32:4)
```

**Comment by maxbrunsfeld** [comment]
I think this is fixed on the latest version of vim-mode. Can you upgrade Atom and vim-mode to the latest versions and report whether you still see this?

**Comment by kevinsawicki** [comment]
Closing this out, deprecations are gone.
