### ISSUE TITLE
j/k on wrapped lines doesn't work on the first/last line of a file

### ISSUE THREAD

**Issue by geoffharcourt** [atom/vim-mode#532]
It looks like support for using `j/k` to move through wrapped lines recently got an upgrade. I noticed on v0.32.0 that you can't use `k` to move up through the wrapped sections of the top line of a file or `j` to move down through the wrapped sections of the last line of a file. vim-mode acts as if the wrapped line is one big line instead of multiple wrapped sections.

In all other parts of a file, `j/k` works like `gj/gk`, or what I would think of as sane navigation through wrapped lines (others might differ there).

**Comment by maxbrunsfeld** [comment]
@jacekkopecky are you interested in looking into this?

**Comment by maxbrunsfeld** [comment]
Thanks for reporting this @geoffharcourt.

**Comment by geoffharcourt** [comment]
:+1:

**Comment by jacekkopecky** [comment]
Cool, no worries. This one was over before I even noticed.
