### ISSUE TITLE
repeat (.) should remember motions

### ISSUE THREAD

**Issue by AsaAyers** [atom/vim-mode#538]
When prefixing several lines I'll often use `I`, `MyPrefix`, `<esc>`, `j` and then `.` to repeat. It currently forgets the `I` (or `A` to suffix) and just inserts the text right there.

If you can point me in the right direction I'll try to contribute a fix when I have some time to work on it.

**Comment by jacekkopecky** [comment]
#560 addresses this

**Comment by AsaAyers** [comment]
If you add `fixes # 538` (without the space) to the body of your pull request it'll close this issue when it gets merged. You can't add it as an extra comment, it has to be in the body, the subject, or one of the commit messages.

**Comment by jacekkopecky** [comment]
Good to know, thanks @AsaAyers – I'm still new here. I edited the first commit, is that what you mean by body?

**Comment by AsaAyers** [comment]
![funny-gif-asian-guy-thumbs-up](https://cloud.githubusercontent.com/assets/324999/6573985/82d6c1be-c6f6-11e4-802f-83d9c9a728b9.gif)
