### ISSUE TITLE
'ct' deletes one character before the cursor

### ISSUE THREAD

**Issue by nesmyslny** [atom/vim-mode#543]
I thought there is already an issue for that, but I can't find it anymore. Sorry, if this is a duplicate.

In some situations the commands `cf`, `ct`, `dt` and `df` also delete one character before the cursor. I don't know the exact circumstances , but could reproduce it as follow:

1. Insert a new line `test (xyz)` and leave insert mode.
2. Yank and put the line after the inserted line: `yyp`
3. Go to x: `fx`
4. Change til closing bracket: `ct)`
5. Result: `test )`

I'm using Atom 0.182.0 and vim-mode 0.34.0 on Linux (x64).

**Comment by jacekkopecky** [comment]
Great, I've been hoping to be able to reproduce this, now I can; let's see if I get some time to play with this before someone else fixes this. 8-)

**Comment by chrisjones-brack3t** [comment]
Using Atom v0.184.0, vim-mode v0.34.0 on OS X 10.10.2 and can confirm the same issue. Thanks for figuring out how to consistently make this show up. It's been driving me nuts for a couple of weeks.
