### ISSUE TITLE
Search text not displaying using /

### ISSUE THREAD

**Issue by MattKunze** [atom/vim-mode#544]
Since the latest update I'm not seeing search text using the vim-mode search (`/`). The search functions correctly, but the search box doesn't show the text I'm typing:

![image](https://cloud.githubusercontent.com/assets/421270/6405911/9d691b44-bde6-11e4-931e-b29189f3f90a.png)

Atom 0.184, vim-mode 0.34, osx

**Comment by vokgist** [comment]
Same here: Atom 0.184, vim-mode 0.34, linux/ubuntu

**Comment by erikweibust** [comment]
I just started using Atom today. First thing I did was install vim-mode. Then was disappointed not seeing my search text. Glad to see there is a bug to get this fixed and that it was working in prior versions.

**Comment by arve0** [comment]
Does not seem to be a style issue, as setting background of search field to white doesn't show any characters. Anyone know of a quick fix?

**Comment by MattKunze** [comment]
The problem is with the mini-editor used to prompt for additional movement and search input. It's not just search, but anything that accepts additional input.

I took a stab at fixing it in #545, and that at least gets it working again on my end. A bunch of the unit tests are failing though, and I haven't had time to look into it any deeper. The behavior seems right, so I can't tell yet if the tests need to be updated to work with the view changes or something else is wrong

**Comment by erickbarron** [comment]
This is something that is used very often and one that really bugs me lol. I sometimes don't know if I am doing the correct word or not. But at least it does work :) . :+1:

**Comment by jcurtis** [comment]
Having the same issue for a few days now. Atom 0.187.0 and vim-mode 0.38.0.

**Comment by axelbsa** [comment]
+1
Having the same issue.
Haven't tried @MattKunze 's branch, but would be nice i could just apm install the branch

**Comment by tmm1** [comment]
This was fixed in the latest release.
