### ISSUE TITLE
dd does not delete trailing lines

### ISSUE THREAD

**Issue by mitsuhiko** [atom/vim-mode#546]
If you are at the end of the file and you have a few empty lines, "dd" or forms thereof will not delete those extra lines.

**Comment by octref** [comment]
+1

Disabling `whitespace` package doesn't help either. 
I'll dig into this later today. 
I'm fairly new to this package so it'd be awesome if any maintainer could give me some pointers.

**Comment by spirityy** [comment]
+1

**Comment by maxbrunsfeld** [comment]
Closing this out in favor of #801 since that issue has more detail. Please subscribe to that one for updates.
