### ISSUE TITLE
Problem with Command mode

### ISSUE THREAD

**Issue by erikweibust** [atom/vim-mode#554]
I am very new to Atom, having only installed it a couple days ago. The first thing I did was figure out how to install "vim mode".

I'm having problems with Command mode. Is it not possible to :w (save file) or :21 (jump to line 21)? Is this a defect, missing functionality that I could work on implementing or just not possible in Atom?

**Comment by christopherdumas** [comment]
Currently, there is no Ex mode in atom's vim-mode, meaning that you cannot do an `:` commands. There is a discussion about whether to add one.

**Comment by dsandstrom** [comment]
There is, however, a ex-mode package available: https://atom.io/packages/ex-mode.  I'm not sure if `:21` is implemented, but `:w` works.  The readme doesn't list the available commands, but you can look at the source to see what is: https://github.com/lloeki/ex-mode/blob/master/lib/ex.coffee#L26.

**Comment by maxbrunsfeld** [comment]
Closing as this functionality is implemented in a separate package, as @dsandstrom said.
