### ISSUE TITLE
Trouble loading changes for development

### ISSUE THREAD

**Issue by pbrianmackey** [atom/vim-mode#559]
I am working on extending the functionality of vim-mode.  I have cloned the repo and opened it in Atom via the View menu > Developer > Open in dev mode.  I made a change:

```coffee
class Insert extends Operator
   //...code
  execute: ->
    console.log("I am working!")  # Added code here
    if @typingCompleted
      return unless @typedText? and @typedText.length > 0
      @editor.transact =>
        @editor.getBuffer().insert(
          @editor.getCursorBufferPosition(),
          @typedText,
          normalizeLineEndings: true
        )
    else
      @vimState.activateInsertMode()
      @typingCompleted = true
```

After making this change I reloaded the environment via "Ctrl+alt+r". Now I hit "Ctrl+Shift+p" and look for "vim-mode" or "vim" and find no results.  I also do not see the activation command in package.json:

```json
"activationCommands": {
    "atom-workspace": "vim-mode:whatever"
  }
```

How can I load vim-mode and do some development?

**Comment by pbrianmackey** [comment]
I found further instructions in the [contributing.md](https://atom.io/docs/latest/contributing-to-packages.html).  I ran through the steps in the order listed and had no luck.  Then I ran:

`apm develop vim-mode`

And I got a second clone of the repository sent to a new location on my computer.  I switched to this new location and ran:

`apm install vim-mode`

then

`atom --dev` and loaded up the project.  Now I can make changes and reload them with `ctrl+alt+r`.  It's a little weird, but I guess that works for now.

**Comment by maxbrunsfeld** [comment]
Generally, the workflow for developing an Atom package is just:

1. Clone the package wherever you want
2. Either:
  * Run `apm link --dev` from the package directory and test your changes in dev mode
  * Run `apm link` from the package directory and test your changes in normal mode

I recommend `apm link --dev` so that you don't accidentally mess up your normal editing environment.
