### ISSUE TITLE
Implement Replace mode

### ISSUE THREAD

**Issue by andyearnshaw** [atom/vim-mode#562]
Please add replace mode as per:

    vim -c "help Replace"

> 5. Replace mode				*Replace* *Replace-mode* *mode-replace*

> Enter Replace mode with the "R" command in normal mode.

> In Replace mode, one character in the line is deleted for every character you
type.  If there is no character to delete (at the end of the line), the
typed character is appended (as in Insert mode).  Thus the number of
characters in a line stays the same until you get to the end of the line.
If a <NL> is typed, a line break is inserted and no character is deleted.

> Be careful with <Tab> characters.  If you type a normal printing character in
its place, the number of characters is still the same, but the number of
columns will become smaller.

> If you delete characters in Replace mode (with <BS>, CTRL-W, or CTRL-U), what
happens is that you delete the changes.  The characters that were replaced
are restored.  If you had typed past the existing text, the characters you
added are deleted.  This is effectively a character-at-a-time undo.

> If the 'expandtab' option is on, a <Tab> will replace one character with
several spaces.  The result of this is that the number of characters in the
line increases.  Backspacing will delete one space at a time.  The original
character will be put back for only one space that you backspace over (the
last one).  {Vi does not have the 'expandtab' option}

It's quite a major omission IMO, especially given that there is no equivalent (ie, insert/overtype mode).

**Comment by maxbrunsfeld** [comment]
Yup, replace mode would be nice. I would definitely merge a PR adding a replace mode if you or anyone else is interested in contributing this.

**Comment by erickbarron** [comment]
I know the regular 'r' works for me, but I don't find myself using 'R' as much. But yes,  I would like this feature to be added as well. :+1:

**Comment by jacekkopecky** [comment]
Please let me know if anyone is working on this; I may take a stab (unless marking takes precedence). I use `R` a lot.

**Comment by maxbrunsfeld** [comment]
It's all yours @jacekkopecky!

**Comment by andyearnshaw** [comment]
I started writing the spec for it on the train home last night but didn't get very far, so feel free @jacekkopecky.  I don't have much free time and I haven't done any work on atom before, so you'd probably get it done quicker than me and that's what I'd prefer :smiley:.

**Comment by jacekkopecky** [comment]
Any thoughts on #573, anybody? 8-)

**Comment by tangledhelix** [comment]
Seems like this issue should be closed? This is merged to master a while ago and in the release...
