### ISSUE TITLE
insert repeat gets confused by `delete`

### ISSUE THREAD

**Issue by jacekkopecky** [atom/vim-mode#564]
in insert mode, `delete` will remove the character following the cursor, but `.` doesn't replay it correctly. Demonstration of the problem: 
 1. have `1234` in the editor and the cursor is on 2
 2. type `iabc<delete><esc>`  – you should have `1abc34` in the editor and the cursor on `c`
 3. move cursor on the `1`
 4. type `.` – you should have `abcabc34` in the text editor, with cursor on the first `c` (the original `1` would get eaten by the repeated `delete`)

But what you actually get is `ab1abc34` with cursor on the first `b`.

The problem is in `TransactionBundler` in `input.coffee` which treats the `delete` as a `backspace`.

**Comment by maxbrunsfeld** [comment]
Thanks for fixing this.
