### ISSUE TITLE
Keybind makes comma key not work properly

### ISSUE THREAD

**Issue by TheAtomicGoose** [atom/vim-mode#572]
I rebound `,t` to toggle and focus the tree, which works as expected, but when I try to use a comma while in insert mode, I have to type comma twice to get it to show up once. I tried putting this code, found in #50, in my init file:

```javascript
atom.commands.add 'atom-text-editor', 'insert-incomplete-keybinding', (e)->
  oe = e.originalEvent
  char = String.fromCharCode(oe.which)
  char = char.toLowerCase() unless oe.shift
  atom.workspace.activePaneItem.insertText(char)
```

And the following in my keymap.cson:

```
'atom-text-editor.vim-mode:not(.insert-mode)':
  ',': 'insert-incomplete-keybinding'
```
I also tried replacing `:not(.insert-mode)` with `.command-mode`, but that didn't work either. How could I make it so that I can type commas normally?

**Comment by jazzpi** [comment]
What does your keybinding for `,t` look like?
I have some keybindings starting with a `,` in command mode and didn't even need to add a `insert-incomplete-keybinding` for the `,` key to normally use it in insert mode.

**Comment by TheAtomicGoose** [comment]
Sorry, this was solved [here](https://discuss.atom.io/t/only-allowing-keybind-to-be-triggered-when-in-command-mode-vim-mode/15496). The solution was to put this in my `keybind.cson`:
```javascript
'atom-text-editor.vim-mode:not(.insert-mode), .tree-view':
  ', t': 'tree-view:toggle'
```.
