### ISSUE TITLE
Changelog not in sync with the v0.38.0 release

### ISSUE THREAD

**Issue by antoine1fr** [atom/vim-mode#575]
Hi,

The changelog doesn't mention the v0.38.0 release.

That being said, the vim-mode is awesome, keep up the good work!

**Comment by jacekkopecky** [comment]
that's now history (still true but not a big problem I think), can be closed?

**Comment by antoine1fr** [comment]
You can close it of course ! :)

**Comment by maxbrunsfeld** [comment]
Thanks for the heads up @antoine1fr. We're trying to do a better job with the changelog.
