### ISSUE TITLE
Vim Keybindings in File Browsing Pane?

### ISSUE THREAD

**Issue by damassi** [atom/vim-mode#576]
It would be fantastic if we could navigate around the file pane like you can in NERDTree for Vim.  Quick jumps via `/search`, paging, etc.  Would it be possible to implement something like this in Atom?  Its the one thing holding me back from a full switch away from MacVim.  

Great work otherwise!

**Comment by lettertwo** [comment]
I'd love to see this, too! I think the current stance is that it won't happen via this package, though (see #131).

**Comment by damassi** [comment]
@dougblack's comment in that thread seems to be a nice work-around, though having first class support right out of the box would be nice.

**Comment by TheAtomicGoose** [comment]
If I'm understanding what you're looking for correctly, you want to be able to move around the file tree in the same manner that you do in NERDTree? If so, I have that most of the way working. Once the tree is open and focussed, you can use `hjkl` and `Enter` to navigate the pane.

I bound `,t` to both toggle and focus the file tree pane, which works to do those two things, but creates another, seemingly unrelated issue ( #572 ). I think that if you used a different keybind, you could use the tree pane pretty much as if it was NERDTree.

**Comment by damassi** [comment]
Rad!  Will give it a spin tomorrow.

**Comment by pencilcheck** [comment]
/ searching doesn't work in tree pane, also can't switch focus between the tree and file easily.

**Comment by TheAtomicGoose** [comment]
Ah, yes, I haven't tried searching in the tree pane, so I didn't think to say that that didn't work. I'm not sure what you consider switching easily, but for me it's just a matter of doing `,t` to switch between tree and main window.

**Comment by damassi** [comment]
Searching via `/` would be fantastic.

**Comment by pencilcheck** [comment]
@TheAtomicGoose in vim you can switch focus between different pane, I don't know how to do that in Atom without closing the pane in the first place.

**Comment by TheAtomicGoose** [comment]
@pencilcheck: you can use `Ctrl-0` to focus the tree pane, so if you rebind that to something you like, you should be able to change the focus easily.

**Comment by pencilcheck** [comment]
@TheAtomicGoose that did it, cool.

**Comment by pgericson** [comment]
Here is a whole thread of bind copy&paste snippets (for does that got this as the first result on google):
https://discuss.atom.io/t/only-allowing-keybind-to-be-triggered-when-in-command-mode-vim-mode/15496

The following snippet toggles focus between project tree and the editor
```
'atom-text-editor.vim-mode:not(.insert-mode), .tree-view':
  ', n': 'tree-view:toggle-focus'
```

**Comment by damassi** [comment]
thanks @pgericson - just what i was looking for
