### ISSUE TITLE
Delete acts as cut!!

### ISSUE THREAD

**Issue by ahmadseleem** [atom/vim-mode#583]
I would like to use the default the clipboard as the default register for copy/cut *only*.
Not for delete, please.
I wanna delete to delete with adding the object to the clipboard while copy/cut does.

Thanks!

**Comment by maxbrunsfeld** [comment]
Are you referring to the `d` operator? In vim, that operator writes to the default register (unless a register is specified using the `"` prefix).

**Comment by ahmadseleem** [comment]
Should that be the default behavior when choose clipboard as the default register?
Most people when delete something they don't need it to override the last copy/cut object...
So, if I wanna remove a text object and save it to be used later I would use Cut not Delete...

In my opinion the best way to do so:
- *Y* => to add to the clipboard.
- *C* or *X* => to delete & add to the clipboard.
- *D* => to delete. like to any other register.... blackhole register or whatever you call.

Thanks!

**Comment by bhuga** [comment]
> I would use Cut not Delete...

These are the same thing in vim:

http://vim.wikia.com/wiki/Copy,_cut_and_paste

> C or X => to delete & add to the clipboard.

`c` (change) is different; it enters insert mode after cutting.

**Comment by maxbrunsfeld** [comment]
@ahmadseleem - this package emulates vim. It seems like you're suggesting a completely different behavior. Maybe you want a different package?

**Comment by ahmadseleem** [comment]
@bhuga Yes, I see that *c* enters insert mode after cutting.
but, I meant the point that it does add the changed text to the clipboard, I Think. Same as copy does in that regard.
That's all.

@maxbrunsfeld  I like this Package, but just suggesting an idea to improve the default behavior as most vim users do when they install vim...
It's just an idea and a personal opinion. So, if you don't like it no problem at all...

Thanks guys for your efforts!

**Comment by danielmurphy** [comment]
I'm way late to the party, but the workaround here is to edit your keymap. In `keymap.cson`, add these lines:

```
'atom-text-editor.vim-mode.normal-mode':
  'x': 'core:delete'
```

Works for me!™

**Comment by integrii** [comment]
Found this in the vim-mode-plus settings!  Makes sense from CLI but not in a desktop window environment.
