### ISSUE TITLE
C-d / C-u in visual mode

### ISSUE THREAD

**Issue by josephcc** [atom/vim-mode#593]
In vim, you can use C-d / C-u to expand your selection while in visual mode, but in atom/vim-mode it would simply put you back in the command mode.

**Comment by daniloisr** [comment]
I'm woking with it, and my idea is to switch the C-d behaviour from a `Scroll` subclass to a `MoveToLine` subclass. I write a sketch for it and apparently it's working https://github.com/daniloisr/vim-mode/commit/544f5dbd8e0e86d9fd0097a830624aebbb6ca88e.

What do you guys think? Can I continue with this approach?
Thx

**Comment by maxbrunsfeld** [comment]
@daniloisr Yeah, your approach is good. I would love to merge a PR fixing this. Are you interested in fixing #614 too?

**Comment by daniloisr** [comment]
@maxbrunsfeld Nice! I will prepare a PR for both issues soon. Thx

**Comment by bronson** [comment]
This can be closed?  It appears to work in 0.200.0 / 0.48.0.

**Comment by daniloisr** [comment]
@bronson I think it be closed

**Comment by maxbrunsfeld** [comment]
Thanks!
