### ISSUE TITLE
Move up / down by n lines

### ISSUE THREAD

**Issue by l4u** [atom/vim-mode#600]
is there a way that I can map a key to `vim-mode:move-up` with number of lines? like `vim-mode:move-up(4)`?

**Comment by romgrk** [comment]
No, not possible unless you have a command named `vim-mode:move-up(4)`, but no argument is transferred, it's all strings. I have a function `custom:move-ten-down`, which is the best possible option for the moment.

    Fn =
        moveCursor: (c) ->
            e = atom.workspace.getActiveEditor()
            p = e.getCursorScreenPosition()
            p.row += c
            e.setCursorScreenPosition(p)


Then

    commands = 
        ...
        'custom:move-ten-down': Fn.moveCursor.bind(@, 10)
        'custom:move-ten-up': Fn.moveCursor.bind(@, -10)
        ...

    for target, list of commands
        for name, args of list
            atom.commands.add target, name, args

**Comment by jacekkopecky** [comment]
For moving all cursors and staying within the line, and not canceling visual mode, this may be better in your `init.coffee`: 
```
Prefixes = require './packages/vim-mode/lib/prefixes'
Motions = require './packages/vim-mode/lib/motions/index'
VimMode = require './packages/vim-mode'

MoveByLines = (num) ->
  editor = atom.workspace.getActiveTextEditor()
  vimState = VimMode.getEditorState(editor)
  repeat = new Prefixes.Repeat(Math.abs(num))
  if num > 0
    move = new Motions.MoveDown(editor, vimState)
  else
    move = new Motions.MoveUp(editor, vimState)
  vimState.pushOperations([repeat, move])

atom.commands.add 'atom-text-editor', 'custom:move-ten-up',   -> MoveByLines(-10)
atom.commands.add 'atom-text-editor', 'custom:move-ten-down', -> MoveByLines(10)
```
and of course, your `keymap.cson` then should contain something like this:
```
'atom-text-editor.vim-mode:not(.insert-mode)':
  'K': 'custom:move-ten-up'
  'J': 'custom:move-ten-down'
```

**Comment by l4u** [comment]
Thanks! it works!

**Comment by charlieegan3** [comment]
FWIW - I needed to use this instead:
```
'atom-text-editor.vim-mode:not(.insert-mode)':
  'shift-K': 'custom:move-ten-up'
  'shift-J': 'custom:move-ten-down'
```
This is helpful @jacekkopecky - thanks.

**Comment by mikolchon** [comment]
@jacekkopecky How to change it so that it works for vim-mode-plus?
