### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by gokmen** [atom/vim-mode#601]
Requiring `View` from `atom` is no longer supported.
Please require `atom-space-pen-views` instead:
  `{View} = require 'atom-space-pen-views'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/exports/atom.js:61:9)
Object.<anonymous> (/Users/gokmen/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-view.coffee:1:1)
```

**Comment by maxbrunsfeld** [comment]
Fixed by https://github.com/atom/vim-mode/commit/197672907b652c1420b79a184eca021c41bd1913. Thanks!
