### ISSUE TITLE
Status bar does not display current mode

### ISSUE THREAD

**Issue by jazzpi** [atom/vim-mode#608]
I think this is due to (undocumented?) changes in the status bar API - consuming the status bar service doesn't work anymore.

Instead, I think you have to add something like this to the `activate` function in `vim-mode.coffee`

```coffeescript
atom.packages.once 'activated', =>
  @statusBarManager.initialize(document.querySelector('status-bar'))
  # Further initialization code
```

**Comment by maxbrunsfeld** [comment]
This has been updated already. Can you try updating to the latest Atom and the latest vim-mode? I'll reopen this if you're still experiencing this problem.

**Comment by jazzpi** [comment]
Oh yes, it works after updating - I think I may have simply overlooked it :flushed:
