### ISSUE TITLE
Ctrl+F or Ctrl+B reset visual line mode selection

### ISSUE THREAD

**Issue by Valve** [atom/vim-mode#614]
If I select multiple lines in visual line mode (shift+v, j,j,j), and then press Ctrl+F to extend the selection to the next screen, the visual line selection disappears.

Expected behavior:

Visual line mode should select the next screen, forwarded by Ctrl+F

**Comment by daniloisr** [comment]
It's similar to this issue https://github.com/atom/vim-mode/issues/593

**Comment by Valve** [comment]
Since #616 got merged, will this have a fix as well?

**Comment by maxbrunsfeld** [comment]
I think this has been fixed for some time. Can anyone reproduce this with Atom 1.1.0 and vim-mode 0.63?

**Comment by morenoh149** [comment]
dont' think this works

**Comment by maxbrunsfeld** [comment]
@morenoh149 I think this has been fixed for a few releases; I actually meant to close this. Are you on the latest Atom and vim-mode?

**Comment by morenoh149** [comment]
I just updated to 0.63. Maybe Im confused? I came here searching for why `ctrl-f` moves the screen down but not my cursor.

So I do `ctrl-f` then when I do `j` my screen jumps back to where the cursor stayed.

**Comment by maxbrunsfeld** [comment]
I remember a bug like that being fixed... what version of Atom are you on?

**Comment by morenoh149** [comment]
oh it's fixed now. I hadn't restarted.

**Comment by maxbrunsfeld** [comment]
:+1: Thanks for the update.
