### ISSUE TITLE
Implement Sublime style multiple cursors in command mode

### ISSUE THREAD

**Issue by calebmeyer** [atom/vim-mode#615]
This is the killer feature which Sublime has that has prevented me from switching to Atom for day to day development.

When I have multiple selections created, I can act on all of them in command mode:
![subl multiple cursor](https://cloud.githubusercontent.com/assets/3342777/7073114/cdadbc74-deb6-11e4-9ce2-a27325248187.gif)

The ability to do motions (for example by word) on several selections at once is invaluable. This change still allows you to collapse to a single cursor, you just have to hit ESC twice.

The current behavior of atom is that pressing ESC while multiple cursors are selected changes to a single cursor and enters command mode.

**Comment by maxbrunsfeld** [comment]
What versions of Atom and `vim-mode` are you using? As far as I can tell, this is all possible currently with `vim-mode`.

**Comment by calebmeyer** [comment]
Well, I'll be darned. Last I tried this, it didn't work. This morning I tried this, and it did work. Closing this issue.
