### ISSUE TITLE
`cc` should not require me to reset the indentation

### ISSUE THREAD

**Issue by maletor** [atom/vim-mode#625]
I think this may be a bug on Atom core because vim-mode seems to simply call out to it.

**Comment by bronson** [comment]
You're right.  `ddO` should be an equivalent command, but it gets the indentation correct.

Anyone know why O works with indentation while cc doesn't?

**Comment by myrtleTree33** [comment]
Hmm seem to be getting that as well.

`cc` should trigger identation + insert mode, however it just clears the line, goes into insert mode and does not indent at all.

**Comment by myrtleTree33** [comment]
`dd0` does not work for me correctly.

**Comment by drifkin** [comment]
`cc` is clearing the line without properly indenting for me as well. However `ddO` does work as I'd expect `cc` to. @myrtleTree33 keep in mind the third character is the capital letter `O`, not the digit `0`.

**Comment by nosami** [comment]
I just came here to report this issue then found this. I think I will make a custom command for now.

**Comment by nosami** [comment]
I have a workaround for now

In your init script:
```
atom.commands.add 'atom-text-editor', 'custom:cc': (e) ->
  editor = atom.workspace.getActiveTextEditor()
  atom.commands.dispatch(e.currentTarget, 'editor:delete-to-end-of-line')
  atom.commands.dispatch(e.currentTarget, 'editor:delete-to-beginning-of-line')
  atom.commands.dispatch(e.currentTarget, 'vim-mode:activate-insert-mode')
  editor.indent()
```

Keymap:
```
'atom-text-editor.vim-mode:not(.insert-mode)':
  'c c': 'custom:cc'
```

**Comment by nosami** [comment]
'S' for 'vim-mode:substitute-line' works almost the same as 'cc' but I found it sometimes adds an extra indent.
