### ISSUE TITLE
Better increase/decrease handling for negative number.

### ISSUE THREAD

**Issue by t9md** [atom/vim-mode#641]
Recently increase/decrease feature is supported by PRs on #636.
That was great! thanks!!
When I use increase number by `ctrl-a`. I frequently hit following situation.

Editing `keymap.cson`, I copied last line from above line and increase number to `z 2`,
```cson
'atom-text-editor.vim-mode.command-mode':
  'z 1':    'editor:fold-at-indent-level-1'
  'z 2':    'editor:fold-at-indent-level-1'
```
Then move to right by `l` and increase next number, it result in 
```cson
  'z 2':    'editor:fold-at-indent-level0'
```
I want `editor:fold-at-indent-level-2` in this case.
In this case I don't want it treated as negative number when `-` is preceded by like [A-Za-z].
This is not feature original Vim supported, but I think this is reasonable enhancement.
So when increase/decrease pick up number, wether it take minus char(`-`) as manipulation target should be determined by the preceding character.

- Expected behavior by this enhancement.
```
# treat this as positive number
"foo-bar-1" # c-a => foo-bar-2 , c-x foo-bar-0
```

Since it break expectation for original Vim user, it might better to provide this feature as optional configuration.

**Comment by jacekkopecky** [comment]
I've had the same issue before. However, I've also edited SVG where in a path, a negative number can easily follow an alphanumeric character (example: `<path style="stroke: #594"  d='M390,270 v5 h5 v-5 h-5'/>`); and I can all too easily imagine editing program source code where `x-3` means subtraction, not an identifier.

Perhaps we need extra commands for ignoring the `-`; how about `ctrl-shift-a` and `ctrl-shift-x`? Would this work for you?

**Comment by t9md** [comment]
I myself don't need any keymap, I will replace `c-a`, `c-x` to new one by myself.
BTW. I haven't edited SVG yet, but I agree current behavior is better in such situation.
This is greatly depending on language type and also formatting convention( whether put extra space  or not between `-` operator).
I prefer configuration option and want to change based on language scope.
But if this is implemented as another command I'm still happy for that.

**Comment by maxbrunsfeld** [comment]
I like the current behavior, but I'd be willing to merge a PR that added some kind of configuration option for controlling this. Maybe `vim-mode.numberRegex`, which could be set differently in different scopes?
