### ISSUE TITLE
Blockwise-visual-mode not working

### ISSUE THREAD

**Issue by TheLuckyOne** [atom/vim-mode#645]
Hi! 
Vim-mode:activate-blockwise-visual-mode not working on my mac, linux and windows. 
What am i doing wrong?

**Comment by bronson** [comment]
Get this, Atom doesn't support block select yet: https://github.com/atom/atom/issues/2306

Apparently there's been some work but nothing usable yet.  If Atom 1.0 ships without block select, that would be downright embarrassing.

**Comment by bronson** [comment]
Also, this is a dupe of https://github.com/atom/vim-mode/issues/516
