### ISSUE TITLE
Press L to move right triggers IME popup in OS X

### ISSUE THREAD

**Issue by ahmadseleem** [atom/vim-mode#656]
Hi,
when trying to move right as in Vim, I press L and hold.
This triggers autocomplete in OS X with some weird letter!!!
Any idea how to disable that completely?

Thanks!

**Comment by ahmadseleem** [comment]
like here:
http://osxdaily.com/2011/08/04/enable-key-repeat-mac-os-x-lion/

I think Vim and emacs turn this off

I don't wann turn it off for the system wide. just for Atom...

**Comment by ahmadseleem** [comment]
I used this to turn it off: 
defaults write -g ApplePressAndHoldEnabled -bool false

But, it's off everywhere in the system...

**Comment by jazzpi** [comment]
A quick google search brought up a comment on [this article](http://belchak.com/2011/07/23/re-enabling-key-repeat-in-osx-lion/):

> You can also disable this per app by replacing "-g" with the app's defaults identifier.

Now I don't own a Mac and can't find the identifier for Atom - but in general, this is not an  issue with `vim-mode` at all - I'd recommend asking this question on [Atom Discussion](https://discuss.atom.io/) or [Apple.SX](http://apple.stackexchange.com/).

**Comment by ahmadseleem** [comment]
For anyone who wanna know the default identifier for Atom it's:

```
com.github.atom
```
You can get like that from the terminal:
```applescript
osascript -e 'id of app "Atom"'
```

**Comment by jacekkopecky** [comment]
I'd disagree about this not being a vim-mode issue. Atom in general plays
nicely with this feature (holding a key for special characters, I'll just
call it "the feature").

The feature is a modern experiment in usability, and it assumes a-z keys
are not often repeated by holding them. Vim-mode violates thar assumption,
and only in "command" mode. It would make most sense if we managed to turn
the feature off in command mode.

I have the feature disabled by default but would give it a try if it stops
interfering with vim-mode command mode.

**Comment by ahmadseleem** [comment]
@jacekkopecky Agreed...
That's what I meant briefly with this line:
>> I think Vim and emacs turn this off

**Comment by maxbrunsfeld** [comment]
Yeah, I'd love to disable IME when *not* in insert mode. Unfortunately, the [ime-mode CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/ime-mode) that can be used to selectively disable it is not yet implemented in chromium. I'm definitely open to suggestions.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
