### ISSUE TITLE
jumplist support

### ISSUE THREAD

**Issue by t9md** [atom/vim-mode#659]
# Reference

jumplist provide cursor position history. 
You can go back and forward to previous and next cursor position with `ctrl-o` and `ctrl-i`.
- [jumplist](http://vimdoc.sourceforge.net/htmldoc/motion.html#jumplist)
- [Jumping to previously visited locations@Vim Tips wiki](http://vim.wikia.com/wiki/Jumping_to_previously_visited_locations)
# Code
## PR
- #397 by @garcg 
## Packages
- [last-cursor-position](https://atom.io/packages/last-cursor-position) by @fcharron
- [cursor-history](https://atom.io/packages/cursor-history) by @t9md (Me), released 3 days ago.

I'm trying to figure out how to implement this feature based on my cursor-history packages.

The steps I'm thinking now are..
- Need to define(or clarify) what jump is in Vim and let vim-mode provide some status(or already exists?) or hook point.
  Currently my package use line delta(default=4) to determine jump or not which is same strategy as last-cursor-position does.
- Loosely integrate to try out by using vim-mode as service provider and let my package use vim-mode's state or hook as service consumer.
- Or write PR to include vim-mode itself.
- Need to write specs to test. This might be tough stuff for me since I'm not familiar with writing GUI test.

**Comment by bronson** [comment]
Hi, cursor-history is a great plugin.

Curious why you want Atom work exactly like vim.  For my fingers, cursor-history works well enough that I haven't been able to tell a difference.  Hooking into vim-mode sounds like a big and thankless task.  I haven't looked closely at vim-mode's code though.

Personally, I'd like to see this functionality in vim-mode itself -- they're very popular keypresses.  So I vote for 2: write PR.

**Comment by t9md** [comment]
@bronson 
Thanks for kind feedback.
My cursor-history package grown from when I wrote above issue and I feel big enough to write PR.
I myself happy to use vim-mod and cursor-history independent and separately.
And writing test spec for this type of package is very tough for me.
So for me, I'm not much motivated to write PR by myself for now.

**Comment by jacekkopecky** [comment]
Thanks @t9md, I installed cursor-history and I'm quite happy now.

**Comment by t9md** [comment]
Oh! thanks, I'm happy to hear that.
