### ISSUE TITLE
dd moves cursor to the beginning of the line

### ISSUE THREAD

**Issue by bronson** [atom/vim-mode#673]
Hitting dd in Atom leaves the cursor at the beginning of the following line.

Hitting dd in Vim leaves the cursor at its previous column position.

To reproduce: put the cursor in the middle of some text and hit dd.  It should remain in the same column, not jump to column 0 (unless the next line is empty of course).

Might be related to https://github.com/atom/vim-mode/issues/315

**Comment by maxbrunsfeld** [comment]
> Hitting dd in Vim leaves the cursor at its previous column position.

I haven't seen this. Maybe there's a vim setting that you're using to make it do this? The behavior that I'm familiar with is that the cursor moves to the first non-whitespace character of the next line, as described in #315.

**Comment by maxbrunsfeld** [comment]
Also, what version of vim are you using? Could you record a gif of this happening after opening vim w/ the default configuration?

```sh
touch empty_vimrc
vim -u empty_vimrc
```

**Comment by bronson** [comment]
OMG, you're right.  Starting vim without plugins makes dd behave the way you describe.

No idea which plugin did that to me, no desire to find out.  :)  Sorry for the noise.
