### ISSUE TITLE
'dd' doesn't delete the line

### ISSUE THREAD

**Issue by scarolan** [atom/vim-mode#681]
I use this so often I don't think I want to use atom if it's missing.  Please incorporate support for basic vi-like commands like "dd" to delete a single line.

**Comment by maxbrunsfeld** [comment]
@scarolan this command has been implemented and working for a long time. What behavior are you seeing? Can you upgrade to the latest versions of Atom and vim-mode? Also, could you open the keybinding resolver (`Key Binding Resolver: Toggle` in the command pallette) and report its output when you enter `dd`?

**Comment by ardrigh** [comment]
I just installed vim mode, and noticed dd doesn't behave correctly either.

This is noticeable if you start a new file and you want to delete and go back up a few lines.
It seems to be something with the EOF not being handled by <kbd>dd</kbd>.

To replicate this, enable 'invisible characters' so you can see the EOL/CR markers.

Create a new file with a few lines of text
At the end of the file write a new line but stop so there is no EOL/CR marker.
Hit <kbd>dd</kbd> to delete the line 

Vim behaviour: It deletes the entire line and moves you to the line above until you are at line 1.
Atom vim mode behaviour: It clears the current line you are on, but leaves you to the start of that line

If you select any lines with an EOL/CR character, then it will successfully delete that line, and move the content below it up.
If you add a new line between existing lines where EOL is visible, that deletes correctly, but that new line will automatically have an EOL/CR marker when it is added.

I hope that description helps.

**Comment by maxbrunsfeld** [comment]
Closing this in favor of #801 since that issue's description is more exact. Please subscribe to that issue for updates. Thanks!
