### ISSUE TITLE
vim-mode delimits paragraphs differently to Vim

### ISSUE THREAD

**Issue by zaz** [atom/vim-mode#689]
Before `dap` is typed:

    # XXX fix
    add_atom_command: (binding, fn) ->
        binding = 'gpd:' + binding
        █@subscriptions.add atom.commands.add 'atom-workspace', binding: -> fn.call(@)

Expected result after `dap` is typed:

    █

Actual result after `dap` is typed:

    # XXX fix
    █

Not sure how important this is, just thought I'd report it anyway.

**Comment by maxbrunsfeld** [comment]
I think this was just fixed via #684.

**Comment by MarkusSN** [comment]
No, the ip/ap is still delimited by comments. It should be a pretty easy fix, I will probably look into it :)

**Comment by maxbrunsfeld** [comment]
Ok thanks for clarifying @MarkusSN.

**Comment by jb** [comment]
Thanks guys. I really appreciate your work!
