### ISSUE TITLE
How do you remap jj to go into escape mode

### ISSUE THREAD

**Issue by tawanda** [atom/vim-mode#693]
How do you remap jj to go into escape mode

i tried
```
'atom-text-editor.vim-mode:not(.insert-mode)':
  'j': 'vim-mode:move-down'
  'j': 'vim-mode:reset-command-mode'
```

but this disables the j and dosen't escape when you are in insert mode

**Comment by fogine** [comment]
possible solution already [here](https://github.com/atom/vim-mode/issues/334)

**Comment by tawanda** [comment]
works like a charm, thanks :)
