### ISSUE TITLE
Implement 'R' for replace mode

### ISSUE THREAD

**Issue by fazlearefin** [atom/vim-mode#700]
Pressing `R` in command mode will place the editor in replace mode for overwriting existing characters.

**Comment by jacekkopecky** [comment]
There's a PR #573 for this, but it got no comment from the maintainers.

**Comment by fazlearefin** [comment]
Great! Hope the maintainers notice this and does something about your PR #573

**Comment by gittyupagain** [comment]
+1

**Comment by bronson** [comment]
This is a dupe of #562.  And I really do wish #573 would be merged or commented on.

**Comment by lurimendes** [comment]
+1

**Comment by tangledhelix** [comment]
Replace mode was merged some time ago - this issue can be closed, I think.
