### ISSUE TITLE
Search does not work.

### ISSUE THREAD

**Issue by zwarag** [atom/vim-mode#709]
Atom: 0.211.0
Chrome: 43.0.2357.125
Fedora: 22
Kernel: 4.0.5-300.fc22.x86_64

When I enable the plugin vim-mode and type "shift+7" nothing happens.
I'd expect it to open the little search Windows but it does nothing.
Any Idea what this could trouble?

I tried to turn off all plugins and themes to be sure but the result was the same.

**Comment by jacekkopecky** [comment]
Hi, just to check - would shift+7 normally produce a slash (`/`) on your keyboard?

**Comment by jazzpi** [comment]
It looks like you're using a non-US keyboard layout. Those do not play nicely with `vim-mode` (or Atom in general) unless you use the [keyboard localization](https://atom.io/packages/keyboard-localization) package.
<kbd>Shift-7</kbd> gets registered as <kbd>&</kbd> since that's what it represents on a US keyboard layout.

**Comment by zwarag** [comment]
I use german layout with no dead keys. Running on a lenovo x1 3rd gen.
Yes a shift+7 does produce a `/`.

To test, I changed my keyboard layout to english (US) layout.
So then I pressed the `/` button that would be `-` on my keyboard.
That worked very well.
But I don't intend to use english keyboard for every day use.

Can I somehow help you guys with this task?

**Comment by jazzpi** [comment]
This is a [bug in Chromium/Blink](https://code.google.com/p/chromium/issues/detail?id=263724), so unless you want to fix that, your best shot would be to use the keyboard-localization package I mentioned.

**Comment by zwarag** [comment]
Installing https://atom.io/packages/keyboard-localization actually solves the problem.
Thank you @jazzpi

**Comment by Ben3eeE** [comment]
Looks solved closing.
