### ISSUE TITLE
:range commands not recognized

### ISSUE THREAD

**Issue by andianderson522** [atom/vim-mode#714]
commands such as:
:10,50y a
:10,15c 42
:5,30m 80

do not work. and give 
   ` Command error: Not an editor command: 10,50y a`

**Comment by jacekkopecky** [comment]
Are these `ex-mode` commands – that is, an issue for the `ex-mode` package?

**Comment by andianderson522** [comment]
I belive :10,50y a is a vi command as it is a yank into a named buffer. I will ask the ex guys if its in their domain.

**Comment by jazzpi** [comment]
Yes, this should be handled by `ex-mode`. `vim-mode` doesn't provide full `vim`-support, only parts. And all `ex` commands (i.e. commands starting with `:`) are handled by `ex-mode`.

**Comment by andianderson522** [comment]
Thanks Ill report it there
