### ISSUE TITLE
Commands for changing case: ~, vu, vU, gu, gU, guu, gUU, etc

### ISSUE THREAD

**Issue by wylieconlon** [atom/vim-mode#73]
Most of these commands involve selecting a visual block where you can change the case of everything selected. More examples of commands from the [vim wiki on switching case](http://vim.wikia.com/wiki/Switching_case_of_characters):

```
~
Toggle case of the character under the cursor, or all visually-selected characters.

3~
Toggle case of the next three characters.

g~3w
Toggle case of the next three words.

g~iw
Toggle case of the current word (inner word – cursor anywhere in word).

g~$
Toggle case of all characters to end of line.

g~~
Toggle case of the current line (same as V~).
The above uses ~ to toggle case. In each example, you can replace ~ with u to convert to lowercase, or with U to convert to uppercase. For example:

U
Uppercase the visually-selected text.
First press v or V then move to select text.
If you don't select text, pressing U will undo all changes to the current line.

gUU
Change the current line to uppercase (same as VU).

gUiw
Change current word to uppercase.

u
Lowercase the visually-selected text.
If you don't select text, pressing u will undo the last change.

guu
Change the current line to lowercase (same as Vu).
```

**Comment by jacekkopecky** [comment]
Hi, some of this is addressed by #556

**Comment by bronson** [comment]
Looks like g~~, gUU, and guu are the only remaining ones to be implemented.

**Comment by t9md** [comment]
As reference, my folked vim-mode now support this.
https://github.com/t9md/vim-mode/commit/4b206accd1cae0f60ebf6aa1016d4c9f2a69d56f
Current official vim-mode's have minor bug(gU, gu, g~ operator won't move cursor in Vim).

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
