### ISSUE TITLE
Linewise visual select incorrectly moves cursor

### ISSUE THREAD

**Issue by bronson** [atom/vim-mode#744]
To reproduce: go to the middle of a line, hit `V` to start linewise visual select, and hit `V` again to stop

What happens: the cursor jumps to the end of the line.

What should happen: the cursor remains where it originally was.

This was originally found in https://github.com/atom/vim-mode/pull/476

**Comment by bronson** [comment]
Also: `V` and then `>` to indent leaves the cursor in the wrong position.  The cursor should not move (so, the line moves under the cursor, but the cursor remains in whatever column it started).

Found in #747

**Comment by t9md** [comment]
My PR don't cover `v` then `>` issue. I'm not sure its actually bug.
My MacVim.app don't keep original cursor column when doing `v>`.
Maybe its useful feature, but its not bug, kind of enhancement?

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 29 2015 20:38:11)
MacOS X (unix) version
Included patches: 1-712 
```

**Comment by bronson** [comment]
Wow, you're right!  I disabled my plugins and now the cursor jumps to the first nonblank line when indenting.  Criminy.

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Oct 25 2014 23:10:43)
MacOS X (unix) version
Included patches: 1-258
```

Probably one of these changes that behavior on my machine.  :(

```
~$ ls ~/.vim-old/bundle/
Arduino-syntax-file          vim-instant-markdown
IndexedSearch                vim-irblack
YAIFA                        vim-javascript
a.vim                        vim-less
ag.vim                       vim-pathogen
base16-vim                   vim-rails
clam.vim                     vim-railscasts
ctrlp.vim                    vim-rake
ctrlp_bdelete.vim            vim-repeat
editorconfig-vim             vim-ruby
gundo.vim                    vim-ruby-block-conv
jQuery                       vim-runtest
puppet-vim                   vim-slim
syntastic                    vim-snippets
tagbar                       vim-speeddating
twilight                     vim-surround
ultisnips                    vim-textobj-comment
vim-airline                  vim-textobj-parameter
vim-bundler                  vim-textobj-rubyblock
vim-closebuffer              vim-textobj-syntax
vim-coffee-script            vim-textobj-uri
vim-colors-solarized         vim-textobj-user
vim-commentary               vim-textobj-variable-segment
vim-crosshairs               vim-toggle-wrap
vim-dispatch                 vim-tomorrow-theme
vim-easy-align               vim-trailing-whitespace
vim-eco                      vim-unimpaired
vim-endwise                  vim-vinegar
vim-expand-region            vim-visual-star-search
vim-fugitive                 vim-vividchalk
vim-git                      vim-yankstack
vim-indent-object
```

So, agreed.  NOTABUG.

**Comment by t9md** [comment]
Btw my PR now can cover simply changing `restorColumn` argument for activateNormalMode  in Yank Motion.
But its better another PR and make it optional with config.

**Comment by t9md** [comment]
To be explicit NOBUG for `v>`. BUG for `VV` or `V Esc`( for original subject of this issue), its covered by #814.

**Comment by bronson** [comment]
Right.  `VV` and `V Esc` are buggy in vim-mode (not for long!), `v>` and `V>` aren't.  Their behavior is exactly the same as stock.

I *am* curious which plugin fixes it on my machine but not curious enough to actually figure it out.  Maybe if Vim had package-cop...

**Comment by t9md** [comment]
Maybe indent-object as name implies.

**Comment by bronson** [comment]
OK fine, I found it binary-search style.  Turns out it's a vim option:

```
set nostartofline
```

Which, since it's not even in [sensible.vim](https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim), probably shouldn't be in vim-mode.  Ah well.

indent-object is a pretty useful text object that selects surrounding lines at the same indent.  One day I'll bring it to vim-mode.

**Comment by t9md** [comment]
Its worth to know it was native Vim option, so that we incorrectly claiming is original vim-mode feature :smile: , thanks for clarifying this.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
