### ISSUE TITLE
Why vim keys does not work in fuzzy search

### ISSUE THREAD

**Issue by gingray** [atom/vim-mode#745]
Why vim keys does not work in fuzzy search? I mean it was really good to do this ctrl + j and ctrl + k (to move up and down). Is it possible to do ?

**Comment by bronson** [comment]
But then how would you add a 'j' or 'k' to the search?

If you don't mind skipping Js and Ks, it might be just a matter of keybindings.  Fuzzy Finder uses a SelectList view from atom-space-pen-views, so you just need to bind [core:move-up and core:move-down](https://github.com/atom/atom-space-pen-views/blob/master/src/select-list-view.coffee#L40-L46).

But I don't know of a way to create a binding that only applies when a SelectList is active...  Maybe ask on the forums?

**Comment by gingray** [comment]
@bronson Thanks for response yup i've configured in my keymap.cson here the config (i also add same navigation to search)
```
'.select-list.fuzzy-finder .editor':
  'ctrl-j': 'core:move-down'
  'ctrl-k': 'core:move-up'

'.preview-pane.pane-item':
  'ctrl-j': 'core:move-down'
  'ctrl-k': 'core:move-up'
```
