### ISSUE TITLE
Go to line number is off

### ISSUE THREAD

**Issue by msmaili** [atom/vim-mode#749]
I noticed whenever I try to go to a particular line, it's off by one.  I'm guessing it's just some indexing issue.

E.g., typing `:20` takes me to line 21.

Also, is there a way to show the bottom input bar when entering a line number?  That way I can see what line I'm typing?

**Comment by bronson** [comment]
Hm, I can't reproduce this.

What type of file?  And does line wrapping affect it?

It's true, showing the keys typed in the status bar while in operator pending mode would be very cool.  And it would be more Vim-like.  That probably merits its own issue.

**Comment by msmaili** [comment]
To be honest, all files.  I'm pretty sure I have line wrapping completely disabled but if you tell me what the setting name is I can check to make sure.

I'll go ahead and open a new issue regarding the bar.

**Comment by bronson** [comment]
Probably related to https://github.com/atom/vim-mode/issues/716

**Comment by jacekkopecky** [comment]
Typing `:20` would be an ex-mode command, so possibly this could be an
issue for that package, rather than vim-mode.

**Comment by msmaili** [comment]
Thanks for the clarification, I didn't realize ex-mode may be the package.

Is there a way to transfer issues between projects or should we just close this and open a new there?

**Comment by 50Wliu** [comment]
This issue was moved to lloeki/ex-mode#67
