### ISSUE TITLE
% motion composing with d command

### ISSUE THREAD

**Issue by irrationalistic** [atom/vim-mode#753]
I've been working on a rebuild of the % bracket matching system to support additional types for comments and functions. I've come across a bug that seems to work oddly with the `operatesInclusively` bit. Before I try to dig in, I wanted to see if anyone had any thoughts!

In a blank file, input `(test)` and move the command-mode cursor to the closing parentheses. Use the command `d %` to delete to the matching open parentheses. You should be left with an empty file, but instead the closing item remains!

Any thoughts?

**Comment by irrationalistic** [comment]
Further exploration, the same action using `v` instead does include the inclusive character: `v %` then hitting `d` will delete inclusively.

**Comment by jacekkopecky** [comment]
Yes, backwards deletions don't properly handle inclusive motions. If you want to have a go, you may want to start in `Motion::moveSelectionInclusively`, I think.

**Comment by bronson** [comment]
Is this issue inspiring #783?  Just curious.

**Comment by jacekkopecky** [comment]
Ah, I had this issue on the list of things that bug me, and forgot someone else was working on it. Sorry @irrationalistic if you were also working on fixing it. If you already have the fix and it's better than mine, feel free to propose an alternative PR.
I'm looking forward to your extensions of `%` to "additional types for comments and functions".

**Comment by jacekkopecky** [comment]
And thanks @bronson for spotting the connection.

**Comment by irrationalistic** [comment]
No worries! Haven't had time to work on it anyways! Thanks for catching it.
