### ISSUE TITLE
vim-mode icon cannot correctly display which status(command or insert) it is

### ISSUE THREAD

**Issue by YukariyoRyu** [atom/vim-mode#755]
vim-mode icon cannot correctly display which status(command or insert) it is while editing muliti-texts. which will make confused while editing. Please solve the issue. Thank you atom team.
![screen shot 2015-07-09 at 14 17 07](https://cloud.githubusercontent.com/assets/7519371/8589144/68381f2a-2645-11e5-8708-a35a42f522f4.png)

**Comment by bronson** [comment]
Strange.  Is your insert cursor always a block, or is it just sometimes?  Can you give some hints on how to reproduce this?

Do you have anything in your styles.less that's screwing it up?  Does it happen when starting in safe mode?

**Comment by YukariyoRyu** [comment]
The status is that while I open a file firstly in view mode. Then I insert "i" to change to the edit mode. And so on I open another file which also in edit mode as the icon views on right bottom. But the cursor is a block not a insert-line. It appears every time when I open more than one file. I just install vim mode. I didn't install any theme .Ah my OS is Mac OS X 10.10.4 .
Thank you.

**Comment by evanjbowling** [comment]
I was able to reproduce this issue in *two* different scenarios:

### Scenario A
*file in 'Normal' mode is labeled as 'Insert' mode*
1. Open file 1
2. Open file 2
3. Tab to file 1
4. Press 'i' for insert mode on file 1
5. Tab to file 2

#### Observation
Mode displayed incorrectly as 'Insert' on file 2. Block cursor still displayed as shown in screenshot above. Interactions (e.g. press 'i') prove that file is still in 'Normal' mode. Entering 'Insert' mode corrects the issue.

### Scenario B
*file in 'Insert' mode labeled as 'Normal' mode*
1. Open file 1
2. Press 'i' for insert mode on file 1
3. Open file 2
4. Press 'i' for insert mode on file 2
5. Tab to file 1
6. Press 'ESC' for normal mode on file 1
7. Tab to file 2

#### Observation
Mode displayed incorrectly as 'Normal' on file 2. Insert cursor still displayed.

#### Best Guess
These scenarios seem to apply to all other text files opened. Perhaps on the mode change of a single file, the entire array of text files currently open is being processed by mistake.

**Comment by jacekkopecky** [comment]
It seems that the status bar is not updated when the user switches to a
different tab/pane etc. Should be an easy fix. Thanks for the very good
issue report.

**Comment by jacekkopecky** [comment]
This should probably be closed (by #823).

**Comment by 50Wliu** [comment]
Thanks @jacekkopecky!  @YukariyoRyu, if you're still experiencing this on the latest version of vim-mode, please comment here!
