### ISSUE TITLE
Crash on complex command

### ISSUE THREAD

**Issue by brigand** [atom/vim-mode#760]
I tried to do the an error report/copy to clipboard, but only the toggle button did anything. Restarting atom didn't help. Screenshot:

![error][1]

Steps:

- <kbd>Cmd</kbd><kbd>N</kbd>
- <kbd>c</kbd><kbd>3</kbd><kbd>i</kbd><kbd>w</kbd>

I meant `ci3w` (which works fine). Version 0.54.0.

<sub>By the way, thanks for the best vim bindings out of any editor I've used!</sub>

[1]: http://i.imgur.com/S51zZhx.png

**Comment by jacekkopecky** [comment]
Seems to be similar to #741, if not the same. I'd love to have a look, unless somebody beats me to it (feel free). 8-)

**Comment by jacekkopecky** [comment]
Are you sure `ci3w` works fine? In my tries it seems to work like `c3w` - and in VIM, `ci3` would be an error, the command would be cancelled, and `ci3w` ends up behaving like a simple `w`. This is all a consequence of two issues: **text objects do not know about prefixes/counts**, and vim-mode doesn't correctly cancel commands as soon as an unrecognized sequence is typed in (#734).
