### ISSUE TITLE
Repeat does not interact correctly with replace from visual mode

### ISSUE THREAD

**Issue by ragunr** [atom/vim-mode#761]
A common useage pattern for me with VIM is to search for a term, replace it using a visual selection, and then using next and repeat to continue to replace down a document.  Unfortunately, when I try this combination in VIM-mode, my cursor just jumps back to the previous replacement's last character, making me believe that it is repeating the replace in its absolute position, rather than repeating it at the cursor.

**Comment by jacekkopecky** [comment]
Thank you, yes, that's a known issue #737 with a fix in the queue #740.

**Comment by ragunr** [comment]
Ah I see now, got thrown off by the discussion of multi-line details in that issue.
