### ISSUE TITLE
"dw" should not delete newline ('\n')

### ISSUE THREAD

**Issue by kaizhang** [atom/vim-mode#771]
As in 0.55.0,  'dw' command deletes newline characters. If you use it to delete the last word of current line, it will append the next line to current line, which is very annoying.

**Comment by christopherdumas** [comment]
Yes! I was just having a problem with that!

**Comment by ceres629** [comment]
Also having an issue with this!

**Comment by jacekkopecky** [comment]
duplicate of #550?

**Comment by 50Wliu** [comment]
Thanks a lot @jacekkopecky :).
