### ISSUE TITLE
can't moveDown/Up from wrapped line in visual-mode.

### ISSUE THREAD

**Issue by t9md** [atom/vim-mode#785]
moveDown(j) , moveUp(k) can' go across wrapped line in visual-mode if selection is **linewise**.
No problem in selection is **characterwise**.

Here is example, L176 is wrapped, and cursor is L175 in visual-mode.
When I did `j`, I can't go down from L176. And also can't go up with `k` to go across wrapped line.

![image](https://cloud.githubusercontent.com/assets/155205/8791943/8a04bea0-2f9c-11e5-9c29-119de8ec0f5e.png)

**Comment by t9md** [comment]
I'm now investigating, `moveSelectionLinewise` have some bug..

**Comment by t9md** [comment]
Issue  is cursor movement(cursor. is screenPosition wise but `moveSelectionLinewise` is bufferPosition wise.
So even if screen position was changed by `@moveCursor()` of  MoveUp or MoveDown motion, 
[this line](https://github.com/atom/vim-mode/blob/12c7df663c337bb2894718000caa1e77fe4656fb/lib/motions/general-motions.coffee#L61) won't care screenRow change.

I quickly implemented fix on `@moveSelectionLinewise` method(counting screenRows and adjust count argument passed to `@moveCursor()` argument, but supporting count argument is not easy since current screenRow count while moving.

So the solution I'll try next is to make `moveCursor()` aware of screenRowCount in linewise motion.

**Comment by t9md** [comment]
I sent PR for fix this, but this PR need discussion.

First of all other motions are currently not aware of diff of screenRow and bufferRow, so having same issue when line is softwrapped. e.g. `MoveToFirstCharacterOfLineAndDown`.

Theoretically all motion which do linewise motion and using simple `cursor.moveDown()` or `cursor.moveUp()` have same isssue.

Passing screenRowCount to `cursor.moveUp(screenRowCount)`, `cursor.moveDown(screenRowCount)` fix this un-awareness.
By this fix, also fix `dj`, `dk` of soft-wrapped line(maybe other `jk` depending motion).

But this fix have side effect.
This fix making normal `j`, `k` motion bufferLineWise.
Currently `j`, `k` is screenLineWise which is atom's default and equivalent to Vim's `gj`  and `gk`.

How should we handle this screenRow and bufferRow diff.

**Comment by GabeIsman** [comment]
Ran into this issue. I can move down past a wrapped line, but never up.

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
