### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by gulbinas** [atom/vim-mode#793]
Requiring `View` from `atom` is no longer supported.
Please require `atom-space-pen-views` instead:
  `{View} = require 'atom-space-pen-views'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
```
Object.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/exports/atom.js:62:11)
Object.<anonymous> (/Users/justinas/.atom/packages/vim-mode/lib/view-models/vim-command-mode-input-view.coffee:1:1)
```

**Comment by maxbrunsfeld** [comment]
It looks like you're using an old version of vim-mode (and probably an old version of Atom). Closing this out, but let me know if you're having issues after upgrading to Atom 1.0.3 and vim-mode 0.57.
