### ISSUE TITLE
Ctrl + U doesn't match vim functionality

### ISSUE THREAD

**Issue by s-taylor** [atom/vim-mode#799]
Ctrl + U should allow you to move the cursor to the very top of the screen (as it does in vim).
In vim-mode once the scrolling has reached the top of the screen the cursor does not move any further upwards. This means you then need to use "k" to scroll up line by line.

**Comment by bronson** [comment]
This is true of a lot of the motion commands, and it shouldn't be.

@50Wliu I'd actually label this a bug.

**Comment by s-taylor** [comment]
If the intention is to mimic vims functionality, it's definitely a bug and not a feature.

**Comment by icook** [comment]
I just did a simple fix for this, but no tests and it doesn't perfectly mirror vim functionality. In my patch, if the new top of window or bottom of window is present then the cursor moves there. Not very elegant, but figured I mention it as a resource.

https://github.com/icook/vim-mode/tree/fix-scroll-top

**Comment by adamalbrecht** [comment]
+1 This bugs me all the time.

**Comment by seokgyo** [comment]
+1

**Comment by nonelove** [comment]
+1

**Comment by s-taylor** [comment]
@icook thanks for this.

**Comment by macgyver** [comment]
:+1:

**Comment by mattr-** [comment]
@icook Just so you know, I'm attempting to turn your quick fix into a
proper fix with tests and everything, so hopefully this will be done and in
vim-mode proper soon.

**Comment by macgyver** [comment]
Slightly related: pressing ctrl+u and ctrl+d in vim moves the page down and also moves the cursor. In atom vim-mode the cursor remains where it was.

**Comment by maxbrunsfeld** [comment]
@macgyver I believe that is fixed in 0.63.

**Comment by macgyver** [comment]
Ah, so it is, thanks! I had upgraded but it seems like I needed to restart
Atom for it to take effect.

**Comment by maxbrunsfeld** [comment]
Also, I think this original issue is fixed as of 0.63, so I'm closing this out. Everyone, please let me know if you're still experiencing this problem.
