### ISSUE TITLE
Last character on line is skipped when selecting upward

### ISSUE THREAD

**Issue by bronson** [atom/vim-mode#806]
I think there's an issue with #770.

When I'm in normal mode, and I click to the right of a line and drag upwards, the very last character on the line gets skipped.

![bug3](https://cloud.githubusercontent.com/assets/1776/9002061/41a4ac5e-3714-11e5-9047-5e84f3565ee1.gif)

gvim handles this correctly.

**Comment by bronson** [comment]
cc @jacekkopecky

**Comment by bronson** [comment]
If you double-click the last word on a line, the last character in the word doesn't get selected either.

**Comment by jacekkopecky** [comment]
Interesting, thanks, definitely will look into it.

**Comment by bronson** [comment]
Also: cmd-a to select all misses the last character in the file.  (when the file doesn't end with a newline)

**Comment by pirminis** [comment]
+1 this is definately fresh new bug

**Comment by jacekkopecky** [comment]
Yes, quite right, the problem is that vim-mode doesn't know the motion is
for selecting. I'm working on a solution.

**Comment by mcastilho** [comment]
Do we have a fix for this ?

**Comment by jacekkopecky** [comment]
yes, it's #827

**Comment by jacekkopecky** [comment]
I'm very sorry indeed to have caused the regression.

**Comment by caleb** [comment]
I think this might be related, so I closed my issue: https://github.com/atom/vim-mode/issues/842

It's exactly the same thing, but it sure seems like it might be in the same family :)

**Comment by mcastilho** [comment]
@jacekkopecky Thanks.  How can I get this fix? Still doesn't show an update in Atom. Are you waiting for more changes to do a release? 0.58 still have this issue.

**Comment by jacekkopecky** [comment]
@mcastilho the fix (#827) relies on functionality that will be released in Atom 1.0.8 which should be coming any day now, then vim-mode 0.59 should be released very briefly afterwards.
