### ISSUE TITLE
%s/ - /\t/ig just puts in the letter t

### ISSUE THREAD

**Issue by GaryFurash** [atom/vim-mode#816]
running :%s/ - /\t/ig
turns 
PO_HDR Purchase Order Header- Header Record for Purchase Order
into 
PO_HDR Purchase Order HeadertHeader Record for Purchase Order
instead of replacing the "-" with a tab character? Is this user error?

**Comment by jacekkopecky** [comment]
This would be an issue for the ex-mode package, you may want to open it
there please.
