### ISSUE TITLE
Can't select last character of file using cmd-a or the mouse

### ISSUE THREAD

**Issue by DylanBruzenak** [atom/vim-mode#826]
Noticed this since the last update. 

Enter command mode and drag from the end of the file

OR 

hit cmd-a when in command mode

The last character of the file is not selected.

Using vG works. Also if you enter insert mode you can use the mouse and cmd-a as normal, which points at this being a bug in vim-mode.

**Comment by jacekkopecky** [comment]
Yes, #806, working on it, sorry.

**Comment by DylanBruzenak** [comment]
Duplicate of https://github.com/atom/vim-mode/issues/806
