### ISSUE TITLE
Disabling vim mode while in command mode leaves it in a pseudo-command mode

### ISSUE THREAD

**Issue by rgbkrk** [atom/vim-mode#83]
Steps to reproduce:
1. Enable vim-mode
2. Go to command mode
3. Disable vim-mode from the settings tab
4. Try to type or escape command mode!

**Comment by chapgaga** [comment]
@maxbrunsfeld is there any plugin which can activate and deactivate other plugins?

**Comment by maxbrunsfeld** [comment]
Not that I know of, but it would be easy to write one. See the [PackageManager](https://atom.io/docs/api/latest/PackageManager#) docs.
