### ISSUE TITLE
^ does not work; cursor disappears

### ISSUE THREAD

**Issue by rumpelsepp** [atom/vim-mode#830]
When using `^` to jump to the first non whitespace char, the cursor just disappears. `$` works as expected.

![test](https://cloud.githubusercontent.com/assets/1961699/9355846/f952ac9e-467c-11e5-8a1f-d92f5365d4f2.gif)

**Comment by jacekkopecky** [comment]
When the cursor is gone, do other things work? `hjkl` movement, `a` to append and so on? Does the cursor reappear? Do the commands behave as if the cursor was where expected, just invisible?

**Comment by rumpelsepp** [comment]
> When the cursor is gone, do other things work?

The cursor reappears but stays on the same position when I press, e.g. h. After that it works as it did before.

**Comment by jacekkopecky** [comment]
Thanks; to get `^`, do you press `shift-6` or some other key combination? There seem to be problems with Atom and international keyboards.

**Comment by rumpelsepp** [comment]
I use a german keyboard layout; so I just press `^`.

**Comment by rumpelsepp** [comment]
```
$ localectl
   System Locale: LANG=en_US.UTF-8
                  LC_NUMERIC=de_DE.UTF-8
                  LC_TIME=de_DE.UTF-8
                  LC_MONETARY=de_DE.UTF-8
                  LC_PAPER=de_DE.UTF-8
                  LC_MEASUREMENT=de_DE.UTF-8
       VC Keymap: de-latin1-nodeadkeys
      X11 Layout: de
     X11 Variant: nodeadkeys
```

**Comment by jacekkopecky** [comment]
In case you haven't already, can you please try it with https://atom.io/packages/keyboard-localization installed? Cf #709

**Comment by rumpelsepp** [comment]
The cursor does not disappear any more. But it also does not jump to the intended position; it just stays where it is.

**Comment by rumpelsepp** [comment]
Clearly a keyboard layout issue. I just switched to US layout and it works.

**Comment by jacekkopecky** [comment]
Maybe you can check Keybinding Resolver, it might tell you what Atom thinks you're pressing.

**Comment by rumpelsepp** [comment]
![screenshot from 2015-08-19 15-49-56](https://cloud.githubusercontent.com/assets/1961699/9357950/f47ea17a-4689-11e5-9b22-b845e90e7b3c.png)

**Comment by jacekkopecky** [comment]
Yup, sorry, this seems to be an Atom issue. You could fix it in your `keymap.cson` with a custom binding or several.

**Comment by rumpelsepp** [comment]
To which of these ~1k atom packages should this reported to?

**Comment by jacekkopecky** [comment]
It may be atom-keymap #37, I think.

**Comment by maxbrunsfeld** [comment]
:point_up: What @jacekkopecky said.
