### ISSUE TITLE
gg=G (format all code)

### ISSUE THREAD

**Issue by brigand** [atom/vim-mode#838]
I've gotten used to formatting code in this way.

I think I originally saw it on this [vim wiki page][1]:

[1]: http://vim.wikia.com/wiki/Fix_indentation

> In normal mode, typing gg=G will reindent the entire file. This is a special case; = is an operator. Just like d or y, it will act on any text that you move over with a cursor motion command. In this case, gg positions the cursor on the first line, then =G re-indents from the current cursor position to the end of the buffer.

I'm guessing it'll be easy to fix because it does work in visual mode ggvG=<kbd>esc</kbd>, which also means it's a low priority.

**Comment by jacekkopecky** [comment]
@brigand can you please describe how `=G` behaves differently from what you
expect, best on a simple test case?

**Comment by brigand** [comment]
```js
// javascript
function f(){
var a = 1;
}
```

Cursor at start of file, `=G`

 - vim: reindents
 - atom: nothing

Cursor at end of file, `=G`

 - vim: nothing
 - atom: reindents

In both vim and atom G alone moves the cursor to the end of the file. Atom behaves like vim in other cases, e.g dG deletes from cursor to end of file, but =G formats from cursor to top of file.

---

I looked at `:help G` in vim.

```
G                       Goto line [count], default last line, on the first
                        non-blank character linewise.  If 'startofline' not
                        set, keep the same column.
                        G is a one of jump-motions.
```

So with this and the cursor at the start of the file, 

```js
function f(){
var a = 1;
var a = 1;
var a = 1;
}
```

In both atom and vim =3G gives the following. It's as-if atom ignores the "default last line" part just for the `=` command.

```js
function f(){
  var a = 1;
  var a = 1;
var a = 1;
}
```
