### ISSUE TITLE
select in insert mode doesn't switch to visual mode

### ISSUE THREAD

**Issue by jacekkopecky** [atom/vim-mode#840]
In insert mode, we can still select text with `shift-<arrow key>`. Should we switch to visual mode if we do?

**Comment by maxbrunsfeld** [comment]
I don't think so; I think it's good that insert mode feels like regular Atom. For example, it's kind of nice when inserting text to be able to quickly retype the current word by selecting it using `cmd-d`, and then to continue typing in insert mode.

What are your thoughts? If you or other people feel strongly about it, we could make it configurable.

**Comment by jacekkopecky** [comment]
I don't feel strongly either way, happy to close this in a week if nobody says otherwise.

**Comment by t9md** [comment]
I strongly :smile:  agree with @maxbrunsfeld.
Switching another mode **automatically** from insert-mode is very counter intuitive.

**Comment by maxbrunsfeld** [comment]
Ok, closing this out for now. Thanks!
