### ISSUE TITLE
Cannot always select the last character with the mouse

### ISSUE THREAD

**Issue by caleb** [atom/vim-mode#842]
I'm running Atom `1.0.7` with vim-mode `0.58.0` on OS X 10.10, and I don't have any other plugins installed (besides those that come with Atom).

When I try to select a line with the mouse, it won't select the last character.

![Selection Bug](https://dl.dropboxusercontent.com/u/473648/Images/vim-mode-selection-bug.gif)

If I disable vim-mode then selection works fine.

This seems definitely related to #806.

**Comment by maxbrunsfeld** [comment]
Thanks for finding that existing issue :+1:.
