### ISSUE TITLE
Atom editor keyboard input locks for whole window, requiring an Atom restart

### ISSUE THREAD

**Issue by ramikassab** [atom/vim-mode#847]
RE: https://discuss.atom.io/t/i-cant-type-in-the-ide/12466

I'd like to add that I had this happen to me about a month back separately from this incident and I went on an extension uninstall/disable sprint, one by one, trying to figure out what it was. Nothing prevented the problem from recurring except for disabling the vim-mode extension. I stopped using Atom for a few days and went back to my iterm2/vim setup. It was right around when Atom 1.0 was about to launch. I believe when it did, is when I re-opened, updated everything and tried again and it worked... until the post referenced below.

It's really hard to pinpoint exactly what is causing this for obvious. It could be a bad interaction with another extension or something within vim mode itself. One replier from atom's discussion board thought maybe I was entering a different mode and just didn't know. That's not the case. I've been using vim for too long and sure hope I wouldn't make that mistake :)

It might help to note that when this happens, it actually disables all text input for the whole window, across all of the tabs and even atom's own settings screen input input boxes. My other opened atom windows will continue working as expected until the issue happens to them. It's happened to me while editing less css, html/django templates and python, which I usually group together by file type in their own windows.

I haven't been able to reproduce the issue since writing that post and quitting atom the other evening... but I've only tried about 3 times since. Perhaps disabling the vim mode extension and then re-enabling it (my last ditch effort that frustrated evening) may have fixed it or perhaps I just haven't tried again nearly enough.

Has anyone else run into this issue at all?

RE: https://discuss.atom.io/t/i-cant-type-in-the-ide/12466
> Not sure if any of you have found a solution to this but I keep running into the same issue where I can no longer type anything in Atom. This includes even Atom's own settings screens. No input works anywhere. Only command mode works (moving around the file, changing words/characters, deleting, etc but nothing can be typed in insert mode. When it triggers, the problem is isolated only to that individual Atom window. The other windows are unaffected until I switch to them and do whatever it is that triggers this. The only way to fix it is for me to quite Atom and re-open it. Luckily, Atom saves all open windows and tabs so it restores my env; however, this issue happens so often now that Atom has become entirely unusable for me and I've resorted back to the tried and testing vim.

> This was happening to me before the official 1.0 release of Atom so I stopped using it for a while and when I came back to upgrade Atom and all my extensions, it started working without any issues again... until just last night for me. It's funny because I hadn't actually installed or changed anything at all and it had been working without issues for at least a few weeks then, out of the blue, last night the issue started up again. I've since disabled/uninstalled all sorts of extensions such as linters, autocompletions, etc but the plugin that, when disabled/uninstalled, fixed this was the vim-mode plugin itself.

> I think I may have pinpointed what triggers this for me. Essentially, whenever I went into visual mode, selected some text and then either pasted from the clipboard or just hit 'c' to change the text, I wouldn't be able to type anything into the editor anymore. I've tried all sorts of this to get out of this crappy limbo state but the only way is to restart Atom and wait for it to happen again.

> Funny thing, after uninstalling a handful of extensions last night, I was able to prevent this from happening when editing Django HTML files. In my other window, which is full of a whole bunch of LESS file tabs, it's still happening. I wonder if certain filetype specific plugins are triggering this. I just haven't been able to pinpoint it that specifically yet.

> I would absolutely LOVE some help trying to get rid of this problem for good. It's absolutely crushing my Atom experience. There's a whole lot of us out there that depend on VIM so using Atom without it is a showstopper for me. Figuring this out should certainly be a priority considering the shear number of vim-mode users. I'm happy to help provide whatever log data, screencasts/shots, etc may be needed to debug and get to the bottom of this.

> Thanks in advance for any help on this!

**Comment by maxbrunsfeld** [comment]
Are you using the latest version of vim-mode?

**Comment by ramikassab** [comment]
Yup, the first place I turned to whenever this occurred were the updates.

**Comment by maxbrunsfeld** [comment]
Does this happen if you disable every package except for vim-mode? What about if run `atom --safe`?

**Comment by ramikassab** [comment]
I haven't tried disabling every single package but I did disable many of the ones I felt could be responsible such as any linters, autocompletions, git, terminal, beautifiers, etc. I disabled them one by one in hopes of trying to pinpoint the culprit. I'd open Atom, reproduce the editor locking issue (select some or a full line text visually with 'v', hit 'c' to change and put me in insert mode, type without results, go to Atom's prefs and only use my mouse since my keyboard wouldn't even work there, disable the next perceived most likely culprit plugin, quit.... rinse and repeated.

I hit a point where the issue stopping occurring while editing Django html templates in my dedicated template Atom window, which had me thinking I had figured it out. However, when I went to my LESS/CSS window of tabs and began working there, the window's editor locked. After that I quite and have since returned to my pretty beefed up terminal VIM setup.

I just opened ATOM while posting and saw both an update for vim-mode and ATOM and ran both. I've for my terminal VIM setup goin and I've been knee deep it a project for the past few weeks so just haven't had the nerve to spend more time on the ATOM issue and certainly can't use it without VIM. I've switch back today to use it for a while. I'll let you know if the issue creeps up again. Thanks

**Comment by brandensilva** [comment]
@ramikassab I'm starting to have this issue that you were seeing. Did you ever see this issue come back? I feel like it has something to do with visual block mode but I can't narrow it down. It's driving me insane though as I'll get random lock ups. I even uninstalled vim-mode and tried out vim-mode-plus to see if maybe it was fixed but no avail.
