### ISSUE TITLE
vim-easyclip mode option

### ISSUE THREAD

**Issue by wolftune** [atom/vim-mode#851]
So, I know that this plugin is not the place to put all sorts of editor features that various vim plugins provide. However, the specific vim adaptions for commands make sense.

[vim-easyclip](https://github.com/svermeulen/vim-easyclip) is one of the most significant and useful plugins for Vim, as it fixes the whole crzy way that Vim uses registers. Thankfully, vim-mode has the option to use the system clipboard, and then I can use an _external_ clipboard history tool. Sure, it would be nice for Atom to have full clipboard history support more directly, but at least tools exist (I use Klipper in KDE).

So, vim-easyclip is effectively:
- ability to control using the system clipboard (already in vim-mode, yay!)
- clipboard history functions of all sorts (would be great to have, probably should be in Atom separately, and just easy-clip style commands to use it once it exists should be vim-mode, but at least system-clipboard level history tools exist already)
- stop updating the clipboard when you really only want to delete!

That last one is the thing I want to see vim-mode add as an option right now. Essentially have an optional mode where the `d` related delete type commands, including `x`, `s`, and `c` command types, should _not_ be "cut" but just "delete", i.e. remove and _don't_ update the clipboard. Then, `m` commands for "move" work like "cut" where items are removed _and_ the clipboard is updated. Yank commands are unchanged.

That simple option would be easy to add, and the rest of the easy-clip functions can be achieved with external tools well enough once using the system clipboard.

**Comment by jacekkopecky** [comment]
You can always use the blackhole register `_` to prevent updating the clipboard. Would this help?

An Atom package for clipboard history might be quite interesting indeed.

**Comment by wolftune** [comment]
@jacekkopecky sure, but that's super tedious. You specify that every time I hit `x`?

So, what I'm suggesting could simply be: an option to have `d`, `x`, `s`, and `c` commands use the blackhole register automatically, and have `m` be a synonym of `d` that behaves exactly as `d` does *currently*.

**Comment by wolftune** [comment]
UPDATE: There's already a clipboard history option: https://atom.io/packages/clipboard-plus and a vim-mode support plugin: https://atom.io/packages/vim-mode-clipboard-plus

So, anyone who wants internal history can use that, anyone who wants to use system clipboard can use a system-clipboard history tool.

So, really the only thing this ticket is about is the option to use easyclip style non-copying delete, as I described succinctly [above](https://github.com/atom/vim-mode/issues/851#issuecomment-136063088)

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
