### ISSUE TITLE
Inner word commands next to a delimiter character delete that character

### ISSUE THREAD

**Issue by caleb** [atom/vim-mode#856]
Let's say you have a document with this text:

```
"Hello World"
```

If your cursor is on the `H`, and you type `ciw` I expect the editor to be in insert mode with this contents:

```
" World"
```

(With the cursor just inside the opening quote). Instead the opening quote is deleted:

```
 World"
```

This gif shows the bug. I perform an `ciw` next to the quote and it's deleted, but if I perform it while on the `e` it behaves as expected:

![vim-mode inner-word command bug](https://dl.dropboxusercontent.com/u/473648/Images/vim-mode-inner-word-bug.gif)

If the quote is a curly brace the same thing happens.

This is on Atom 1.0.11 with vim-mode 0.60 and no other plugins installed.

**Comment by pcasaretto** [comment]
:+1:

**Comment by caleb** [comment]
Looks like this was fixed by: https://github.com/atom/vim-mode/commit/67ce5cecd4ca2cde52e6d754126a9ea9a538d7a3

Thanks!

**Comment by KyleLH** [comment]
Uhh I'm still getting this error. For example, if I have:
```javascript
var a = "none";
```

and do `ciw` when my cursor is over e, it results in:
```javascript
var a = "
```

As you can tell, it removes the word, closing quote, as well as the semicolon
