### ISSUE TITLE
can't install vim-mode error undefined

### ISSUE THREAD

**Issue by mota57** [atom/vim-mode#865]
While installing vim-mode it throw me this error.

OUTPUT ERROR:
Installing “vim-mode@0.60.0” failed.Hide output…
undefined.

Any hints to solve this problem?

**Comment by mota57** [comment]
:/

**Comment by maxbrunsfeld** [comment]
Could you report what version of Atom you're using and your OS? Are you able to install `vim-mode` from the command-line?

```
apm install vim-mode
```

**Comment by mota57** [comment]
Os: Ubuntu 14.04
Atom version : 1.0.15
I tried to install from command line and give me the same error.

**Comment by mota57** [comment]
well thanks for ask at least xD

**Comment by 50Wliu** [comment]
@mota57 can you try updating to Atom 1.0.19 and see if the error still happens?

**Comment by mota57** [comment]
@50Wliu thanks man now its working after installed Atom 1.0.19 :+1:

**Comment by 50Wliu** [comment]
Nice to hear! :sparkles:
