### ISSUE TITLE
ctrl-e should copy from line below

### ISSUE THREAD

**Issue by wbolster** [atom/vim-mode#875]
the insert mode ctrl-y command, which is implemented, copies characters from the line above. ctrl-e should do the same for line below.

**Comment by wbolster** [comment]
it looks like this has deliberately been disabled in 3e556fb648263a9b7dab62dcc2e951d85a1df791, stating "disabled for compatibility with the common binding for going to the end of the line" somewhere in a code comment. i'm not sure where "common binding" comes from, but this is certainly not normal vim behaviour, and i expect vim-mode to work like vim itself.

**Comment by maxbrunsfeld** [comment]
Yeah, `vim-mode` is built to work like Atom in insert mode. If you want to override Atom's own key-bindings in insert mode, everything is all set up for you to do so. The command is: `vim-mode:copy-from-line-below`.

**Comment by wbolster** [comment]
Well, the whole point of `vim-mode` is that it acts like vim! using `ctrl-e` for jumping to the end of the line is actually an emacs binding (and atom apparently), but the point is, well, it's kinda obvious, vim is not emacs...

**Comment by casimir** [comment]
Actually `<C-E>` exists in Vim but for a completely different thing ([see help here](http://vimdoc.sourceforge.net/htmldoc/scroll.html#CTRL-E)). Not that `<C-Y>` is also the opposite.

**Comment by maxbrunsfeld** [comment]
Yeah @casimir the binding you mentioned is in normal mode. This issue is talking about [this one](http://vimdoc.sourceforge.net/htmldoc/scroll.html#CTRL-E).

**Comment by wbolster** [comment]
i still fail to understand the reason for deviating from normal vim behaviour. why is ctrl-e special in insert mode?
