### ISSUE TITLE
If the cursor in the last line, I can't pass the "DD" to delete the last line

### ISSUE THREAD

**Issue by doneself** [atom/vim-mode#876]
If the cursor in the last line, I can't pass the "DD" to delete the last line

**Comment by denqxotl** [comment]
Is it about empty line?

**Comment by marcindomanski** [comment]
I think it is. If there are any characters in the last line, `dd` just removes them, but does not remove the last line. If the last line is empty, well, `dd` doesn't do anything.

I think this has already been reported (#801), but it isn't fixed yet. I would love to see this fixed, I've been waiting for it for quite some time now..

**Comment by redbmk** [comment]
This should probably be closed in favor of #801

**Comment by 50Wliu** [comment]
Thanks @redbmk.
