### ISSUE TITLE
Configure to prevent flash when no search matches.

### ISSUE THREAD

**Issue by jordwalke** [atom/vim-mode#883]
When searching and typing a word that has no match, the flash is really huge and distracting. Is there a way to disable it?

**Comment by t9md** [comment]
Hey, this is for feature of vim-mode-plus? Close this issue and reopen in vim-mode-plus's repo, it confuses other user.

**Comment by t9md** [comment]
Hey isn't this vim-mode-plus' feature?
If so, this is vim-mode's repo, close this issue and reopen in vim-mode-plus's repo.

**Comment by jordwalke** [comment]
Oh, I'm so sorry - I had both tabs open and I was comparing. I'll file an issue on the right repo. Apologies everyone!
