### ISSUE TITLE
Sentence motion support?

### ISSUE THREAD

**Issue by jonasws** [atom/vim-mode#884]
In Vim it is possible to do stuff like "_something_ to end of sentence". This feature would be very useful to include in this package. Anyone else thought of this or any plans made to include this later? Should be able to implement in a simliar fashion to how `Paragraph` operates already.

**Comment by blablatros** [comment]
What about `)` motion? That moves te cursor to the end of the sentance.

**Comment by jonasws** [comment]
Cl
