### ISSUE TITLE
Ctrl+w to work on tree view

### ISSUE THREAD

**Issue by franleplant** [atom/vim-mode#894]
Hi! I'd like to move to and from the tree view window with `Ctrl+w`, the same I use to move between file windows (splits)

**Comment by nathansobo** [comment]
Hi @franleplant, just bind `ctrl-w` to `tree-view:toggle-focus` in your keymap under the `atom-workspace` selector. You can learn more about keybindings here: https://atom.io/docs/latest/behind-atom-keymaps-in-depth.

**Comment by franleplant** [comment]
Thanks! Ill try!
