### ISSUE TITLE
Atom doesn't respect :qa

### ISSUE THREAD

**Issue by matthewjosephtaylor** [atom/vim-mode#896]
What I do:

command mode type :qa

What I expect:

atom to quit all open tabs and exit if no unsaved changes (same as cmd+q)

What actually happens:

Error popup: Command error: Not an editor command qa

It would be nice if Atom also learned about xa and qa!

http://vim.wikia.com/wiki/Save_all_open_buffers_at_once

**Comment by thedaniel** [comment]
Thanks for the feature request! I believe this is a duplicate of #50 so I'm closing this one.
