### ISSUE TITLE
activate-normal-mode inserts latin letters on cyrillic keyboard

### ISSUE THREAD

**Issue by denysdovhan** [atom/vim-mode#898]
There was a problem with remapping ESC https://github.com/atom/vim-mode/issues/334, it was fixed, so now I can remap that using only `keymap.cson`, like this:

```
# Vim normal mode
'atom-text-editor.vim-mode.insert-mode':
  'j j': 'vim-mode:activate-normal-mode'
  'k k': 'vim-mode:activate-normal-mode' # bcoz I always confuse this
  'k j': 'vim-mode:activate-normal-mode' # bcoz I always confuse this
```

Now, there is a **new problem**:

When I use cyrillic keyboad and type `о` or `л` (match to `j` and `k` on latin keyboar), I get `j` and `k` instead of `о` or `л`. For example, if I try to type `орел`, I'll get `jреk` instead.

Is there way to fix this?

---

My `init.coffee` is clean.

**Comment by thedaniel** [comment]
@maxbrunsfeld do you know if this is specific to vim-mode, or if it's likely to be a general keymap issue?

**Comment by maxbrunsfeld** [comment]
I think this is a general keymap issue. It was probably introduced by https://github.com/atom/atom-keymap/pull/94, which fixed the handling of multi-key printable character bindings like `j j`.

Basically, when a multi-key binding like that fails to match after one or more characters, we attempt to figure out which characters would have been inserted, and fire text insertion events for those characters. Our [logic for determining the characters](https://github.com/atom/atom-keymap/blob/master/src/helpers.coffee#L224) must not work for these cyrillic characters.

@denysdovhan Could you run this code in the Atom javascript console, and report its output after typing `о` and `л`? You'll need to click on the `KeyboardEvent` object to expand it.

```js
window.addEventListener('keydown', function(event) {
  console.log(event, atom.keymaps.keystrokeForKeyboardEvent(event));
}, true);
```

**Comment by denysdovhan** [comment]
After typing `о`:

![image](https://cloud.githubusercontent.com/assets/3459374/10818851/4d9fc612-7e4d-11e5-86c0-ae2daf53ce73.png)

After typing `л`:

![image](https://cloud.githubusercontent.com/assets/3459374/10818868/71388046-7e4d-11e5-9b6f-b179310df4e0.png)

**Comment by denysdovhan** [comment]
So, will it be fixed?

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
