### ISSUE TITLE
ctrl-u and ctrl-d don't work at the top and bottom of the page

### ISSUE THREAD

**Issue by prismatica** [atom/vim-mode#902]
In vim, ctrl-u will jump up a half page, keeping the cursor position the same, until it can no longer do so, at which point, it will continue to jump half a page, but moving the cursor. Some for ctrl-d, except heading down.

vim-mode will jump as expected until the cursor position is forced to change, at which point it will jump no longer.

Looks like the code is here:
https://github.com/atom/vim-mode/blob/4a9604a85fde94ac09da476d4bfe98e2be7df926/lib/motions/general-motions.coffee#L485

I think all the Scroll(Half|Full)(Up|Down)KeepCursor functions need this change

**Comment by averrin** [comment]
+1

**Comment by maxbrunsfeld** [comment]
I believe this is fixed via #906.

**Comment by prismatica** [comment]
Looks like the cursor no longer updates its position after #906.

**Comment by maxbrunsfeld** [comment]
> Looks like the cursor no longer updates its position after #906.

I think #906 fixed this problem. What version of Atom are you using?

**Comment by prismatica** [comment]
1.1.0

**Comment by maxbrunsfeld** [comment]
Can maybe record a GIF of the problem you're seeing, and a GIF of what vim does on the same file? I'm not sure I'm understanding the problem you're describing.

**Comment by prismatica** [comment]
http://recordit.co/g1SuNRwOLh
In this recording of vi, using ctrl-d and ctrl-u moves the cursor half a page up, keeping the position on the viewport the same, except when it hits the top or bottom. When the cursor hits the top or bottom, it still moves up half a page, but moves position in the viewport.

http://recordit.co/kwFEAjflxn
In vim-mode, the cursor is now left behind while the screen scrolls half a screen. Once any navigation commands are used (hjkl or arrow keys), the screen position hops back to the cursor. In 0.62.0, the cursor at least would change its position when it could jump without changing the location in the viewport, but failed to move once it hit the top or bottom.

**Comment by maxbrunsfeld** [comment]
Weird, that looks like the behavior of 0.62, prior to #906. For me, both the commands work perfectly now. Can you double check that you have the latest version? Not sure what could be going on here. Can you report the contents of your `config.cson`, and your list of installed packages?

**Comment by prismatica** [comment]
```
"*":
  "exception-reporting":
    userId: "e3b7043b-3200-7d2a-51cd-5685a1a7378f"
  welcome:
    showOnStartup: false
  core:
    audioBeep: false
  "vim-mode": {}
  editor:
    invisibles: {}
    fontSize: 13
  react: {}
  linter: {}
  "linter-eslint": {}
  "linter-rubocop": {}
```

**Comment by prismatica** [comment]
Ok, I've got it working now--restarted again and it works perfectly. Sorry for the trouble, and thank you for the fix! It's much appreciated.

**Comment by prismatica** [comment]
(definitely feels a lot more like vim to me now)

**Comment by maxbrunsfeld** [comment]
Yeah, even though you can update a package with Atom running, we don't currently have a way of actually unloading the old code, so you often have to reload your window or restart Atom. Thanks for the update!
