### ISSUE TITLE
Cursor does not follow ctrl+f and ctrl+b after upgrade to Atom 1.1

### ISSUE THREAD

**Issue by damassi** [atom/vim-mode#903]

**Comment by thomasjo** [comment]
Please provide more details about your setup; OS, installed packages, etc.

**Comment by damassi** [comment]
Sure thing -- OSX El Capitan (pretty standard setup) and here's a dump of my plugins. Downgrading fixed the issue.

atom-alignment@0.12.1
atom-beautify@0.28.16
atom-jade@0.3.0
atom-pair@2.0.10
atom-runner@2.4.6
autocomplete-php@0.3.7
base16-eighties-dark-syntax@0.1.0
black-and-white-ui@0.1.15
bottom-dock@0.3.5
close-other-tabs@0.1.0
color-picker@2.0.13
cursor-history@0.5.5
docblockr@0.7.3
git-plus@5.4.7
highlight-selected@0.10.1
ide-flow@0.8.0
indent-guide-improved@1.4.3
language-ejs@0.2.0
language-elm@1.2.0
language-haml@0.23.4
language-haskell@1.4.12
language-javascript-jsx@0.3.7
linter@1.9.1
linter-elm-make@0.3.0
linter-eslint@3.2.0
linter-php@1.0.5
markdown-scroll-sync@0.4.2
merge-conflicts@1.3.6
nuclide-click-to-symbol@0.0.22
one-dark-ui@1.1.5
open-terminal-here@2.1.0
painless-panes@0.1.0
react-snippets@0.2.0
script@3.0.1
solo-one-dark-ui@0.1.1
symbol-gen@1.0.0
sync-settings@0.6.0
tabs-to-spaces@0.11.1
term2@0.9.21
todo-manager@0.2.6
todo-show@0.16.0
trailing-semicolon@1.1.0
turbo-javascript@1.1.5
vim-mode@0.62.0
vim-mode-visual-block@0.2.13
zentabs@0.8.6

**Comment by thedaniel** [comment]
@damassi can you reproduce with safe mode? You can launch Atom in safe mode with `atom --safe` in the terminal or `Application: Open Safe` in the command panel.

**Comment by thomasjo** [comment]
I was going to propose the same, but vim-mode is not a core package, so it'll be disabled when running in safe mode.

**Comment by thedaniel** [comment]
Whoops!

**Comment by damassi** [comment]
Yeah, my setup is nothing special. Could someone please see if paging works with 1.1?

**Comment by maxbrunsfeld** [comment]
I'm seeing that the editor scrolls correctly, but the cursor doesn't move correctly as you scroll. Is that what you're seeing @damassi?

**Comment by damassi** [comment]
Exactly. Like if you page down or up the cursor will stay behind

**Comment by ingshtrom** [comment]
+1

**Comment by mlynch** [comment]
Also seeing this with Ctrl+D, Ctrl+U on Atom 1.1.0 and atom-vim 0.62.0. The cursor doesn't follow the paging which it should.

**Comment by mitchellwrosen** [comment]
+1, seeing this as well

**Comment by maxbrunsfeld** [comment]
Hey everyone, sorry for not noticing this before we shipped v1.1.0. I believe this is fixed in vim-mode 0.63. Thanks for the reports.

**Comment by mlynch** [comment]
Thanks for the fix!
