### ISSUE TITLE
Ctrl+F and Ctrl+B should move the cursor on-screen if it is currently off-screen

### ISSUE THREAD

**Issue by Valve** [atom/vim-mode#907]
In Vim Ctrl+F and Ctrl+B move the cursor to the beginning/end of page correspondingly.
In Vim if I'm scrolling with 2 above commands, the scroll position will stay on the current page.

In current plugin cursor stays on the original position (hidden far above or below), which I believe is a bug.
Current behavior makes Ctrl+F/B useless, because it forces me to grab a mouse and click in order to move the cursor to the current page.

**Comment by maxbrunsfeld** [comment]
What version of vim-mode are you using? I thought I fixed this in 0.63.

**Comment by vigneshm** [comment]
I can repro this issue with version 0.63

**Comment by maxbrunsfeld** [comment]
Oh, I see; this is if you type `ctrl-f` while the cursor is offscreen. It sounds like that needs to be added as a special case. Thanks for the reports.

**Comment by vigneshm** [comment]
Just to be clear, when the cursor is **on-screen** and you do `ctrl+f`, the page scrolls forward but the cursor remains in its previous position (which becomes off-screen now).

**Comment by maxbrunsfeld** [comment]
@vigneshm What version of Atom are you using? I believe the bug you're describing has been fixed.

**Comment by vigneshm** [comment]
v1.1.0

**Comment by maxbrunsfeld** [comment]
And you're sure you're using `vim-mode@0.63`? I can't reproduce this.

**Comment by vigneshm** [comment]
Yep that is the version. Not sure what messed it up. Let me try re-installing vim-mode.

**Comment by erktime** [comment]
I too think i had this issue, but a full quick and relaunch of atom fixed.

**Comment by Valve** [comment]
OK, just woke up. So my Atom version is `1.1.0` and vim plugin version is `0.63`. OSX 10.10.5.

I'm opening a large Ruby file (2000 lines of code). The cursor is on line 1. Then I press `Ctrl+F`.  The page is scrolled and the cursor jumps to the first line of the current screen on line 31. Then I press `Ctrl+F` again, the cursor jumps to the first line of the new page and becomes situated on line 61.
 *This works as expected*.

What is not working as expected:

1. When I did the scroll with `Ctrl+F` and the cursor is on the first line of the current page (line 31) and then I press `j` to move one line down, the page shifts up one line to reveal the line 30, while the cursor goes one line down simultaneously to line 32. This is now how Vim works. What is should do is to not shift the page and move the cursor down.
2.  When the cursor is off-screen and I do Ctrl+F, the cursor will not jump to the first line of the current page (same for Ctrl+B). It should, however.

Please let me know if I should create a GIF to demo the issue.

**Comment by maxbrunsfeld** [comment]
@Valve, Yeah, I changed the issue title to reflect your 2nd item. Does vim actually do that though? In my version of vim, it is impossible to scroll the editor such that the cursor goes offscreen; the cursor always follows the visible area. I'd be interested to see a GIF of the behavior you're describing in vim.

**Comment by Valve** [comment]
Yes, you're right. Closing it now, but we should implement the cursor following the scroll behavior then. Please let me know if there is no such ticket already.
