### ISSUE TITLE
Pressing Ctrl while the page is being inertially scrolled decreases the font size.

### ISSUE THREAD

**Issue by Valve** [atom/vim-mode#908]
I think it maybe only reproducible on a Mac. I'm using two-finger scroll on MBP, which has this 'inertia' effect, causing the page to slowly decelerate scrolling after two fingers were already lifted from the touch pad surface.  So if I press `Ctrl` during the inertia scrolling (after I physically stopped dragging fingers onto the touch pad surface), - the font becomes tiny as if I pressed `Ctrl + <minus>` multiple times.

I'm using Atom 1.1.0 on OSX 10.10.5.

**Comment by 50Wliu** [comment]
This also happens whether or not vim-mode is installed - can you please re-open this on atom/atom?  Thanks.

**Comment by Valve** [comment]
sure, thanks
