### ISSUE TITLE
escape is also mapped by find-and-replace

### ISSUE THREAD

**Issue by zenhob** [atom/vim-mode#91]
https://github.com/atom/find-and-replace/issues/134#issuecomment-36373021

So it turns out that find-and-replace allows you to dismiss the dialog by hitting escape from the text editor, but I didn't know this was the case because I use vim-mode. Not sure whose bug this is yet, but it's worth knowing about.

**Comment by bronson** [comment]
For others who are bugged by this, hitting Cmd-F Esc works.  That focuses the Find window then dismisses it.  Not elegant but I can live with it.

**Comment by ip2k** [comment]
Just wanted to comment on this because none of the solutions listed were working for me, and escape still wasn't closing find. My issue was that I was using Karabiner to remap escape to eject. Once I sorted this, everything works as expected. Hope this helps someone else looking for the answer!

**Comment by smeggingsmegger** [comment]
For anyone else still struggling with this, the following keybinding actually seems to completely fix the issue for me:

```
'atom-text-editor.vim-mode:not(.normal-mode)':
  'escape': 'vim-mode:reset-normal-mode'

'atom-workspace':
  'escape': 'core:cancel'
```

**Comment by kundansingh1** [comment]
@smeggingsmegger Your solution worked for me. Thanks!
