### ISSUE TITLE
read $HOME/.vimrc to setting up vim-mode

### ISSUE THREAD

**Issue by xbeta** [atom/vim-mode#914]
I found that Intellij's [IdeaVIM](https://github.com/JetBrains/ideavim) plugin has 1 unique but awesome feature that it [reads `.vimrc`](https://github.com/JetBrains/ideavim#files)   to setting up binding.  I would love to have this feature on Atom too.

**Comment by dusenberrymw** [comment]
+1 This would be really useful.

**Comment by jazzpi** [comment]
The `.vimrc` is written in vimscript, so reading that file would require being able to parse Vimscript, i.e. a fully-featured [ex-mode](https://github.com/lloeki/ex-mode). IdeaVIM [also has this issue](https://youtrack.jetbrains.com/issue/VIM-669), but it's probably possible to do a similar implementation (i.e. parse `map` through pattern matching). Still, some things simply work differently in vim and Atom though, so things like recursive mappings would probably be difficult to implement.

**Comment by maxbrunsfeld** [comment]
I don't want to do this as part of vim-mode. As @jazzpi said, it's very complicated to parse vim-script correctly and convert between vim's configuration concepts and Atom's I think this would make a great separate package though, @xbeta, if you're interested in creating it!

**Comment by hurkatolto** [comment]
Why don't you run a vim or nvim server in the background? With that you just need to communicate with the server instance then you don't need to simulate vim's behaviour...

**Comment by jazzpi** [comment]
1) If you're looking for that, check out https://github.com/carlosdcastillo/vim-mode
2) That won't happen in this package since it's dead.
