### ISSUE TITLE
implement pipe (|) to move to the start of the line (position 1)

### ISSUE THREAD

**Issue by globau** [atom/vim-mode#915]
in vim pressing pipe moves the cursor to position 1 of the current line (as opposed to ^ which moves to the first non-whitespace character).  this appears to be not implemented in vim-mode.

evidently my muscle memory has this action etched into it :(

**Comment by sknoslo** [comment]
I believe the "correct" way to move to the beginning of a line in vim (and in vim-mode) is to hit `0`.

See [here](http://vim.wikia.com/wiki/Moving_around).

**Comment by maxbrunsfeld** [comment]
Fixed by #917.
