### ISSUE TITLE
win8.1 Ctrl+V block choose not like the vim

### ISSUE THREAD

**Issue by zwfy1** [atom/vim-mode#923]
In the vim, I can choose one or multi-rows use CTRL+V,but in vim-mode,CTRL+V only choose multi-lines, I like this plugin, wish this bug could be fixed! Thank you !

**Comment by denqxotl** [comment]
Same trouble. Mac OS

**Comment by shadowwalkersb** [comment]
Confirmed on Mac, Windows and Linux.

**Comment by jamesgecko** [comment]
Duplicate of #468.

**Comment by 50Wliu** [comment]
Thanks @jamesgecko.
