### ISSUE TITLE
Open file in vim mode

### ISSUE THREAD

**Issue by carlisia** [atom/vim-mode#925]
I did a quick search and didn't find another request for this.

It is such a pain to open a file and have to put the file in vim mode *every single time*. Could we please have a setting that lets people make it a default that new files or newly open files will be set to vim mode automatically?

**Comment by maxbrunsfeld** [comment]
I'm not sure what you mean by 'put the file in vim mode'. When you enable this package it's enabled for all files, all of the time. Are you talking about Normal Mode vs Insert Mode? There is a setting that controls whether you start in insert mode or not: `vim-mode.startInInsertMode`.

**Comment by carlisia** [comment]
That's exactly what I meant. And looking at the settings (again) I now see the checkbox starring at me. Perfect, thanks.

**Comment by maxbrunsfeld** [comment]
:+1: Great! Thanks for the update.
