### ISSUE TITLE
selecting with shift+v jumps strangely when scrolling with j/k when more than one screens worth of lines is selected

### ISSUE THREAD

**Issue by phorust** [atom/vim-mode#930]
Doesn't happen with selecting with v
Here's what the behavior looks like: [gfy](http://gfycat.com/DevotedEmptyAracari)
![gif](http://giant.gfycat.com/DevotedEmptyAracari.gif)

**Comment by t9md** [comment]
@maxbrunsfeld Maybe same issue I tackled in my vim-mode-plus, hope this info helps.
 https://github.com/t9md/atom-vim-mode-plus/issues/23

**Comment by kcaze** [comment]
The offending line is here: https://github.com/atom/vim-mode/blob/master/lib/motions/general-motions.coffee#L63

Atom now has an `autoscroll` option that defaults to `true` for `setBufferRange()`. Setting the `autoscroll` option to `false` fixes this.

**Comment by ssfrr** [comment]
Thanks @kcaze. I just submitted a PR that followed your advice and it seems to work for me
