### ISSUE TITLE
Repeat command does not work with fold commands

### ISSUE THREAD

**Issue by KarlPurk** [atom/vim-mode#947]
The repeat command does not work with fold commands.  Steps to reproduce:

1. Move to a block that can be folded
2. Fold the block with z c
3. Move to another block that can be folded
4. Fold the block with .

Step 4 does not fold the block.  Instead it repeats the last repeatable command that was entered before the fold command.

**Comment by maxbrunsfeld** [comment]
I believe this is the correct behavior. Vim also has folding, and `.` does not repeat folds; it repeats the last buffer change.
