### ISSUE TITLE
Ability to add custom shortcuts?

### ISSUE THREAD

**Issue by sunjay** [atom/vim-mode#948]
I don't see this documented anywhere. Is there an equivalent to vim's map?

For example in my .vimrc I have the following for quickly switching between views:

    map <C-j> <C-W>j
    map <C-k> <C-W>k
    map <C-h> <C-W>h
    map <C-l> <C-W>l

**Comment by maxbrunsfeld** [comment]
Yeah, see [the docs](https://atom.io/docs/latest/behind-atom-keymaps-in-depth) for defining key bindings. To find the name of a command that you want to add a keyboard shortcut for, you can search for it in the Command Palette (`cmd-p` on Mac) or use the Key-binding resolver (`cmd-.` on Mac).

In your case, I believe this is what you're looking for:

```coffee
'atom-text-editor.vim-mode:not(.insert-mode)':
  'ctrl-j': 'window:focus-pane-above'
  'ctrl-k': 'window:focus-pane-above'
  'ctrl-h': 'window:focus-pane-on-left'
  'ctrl-l': 'window:focus-pane-on-right'
```

Let me know if you have any further questions!

**Comment by sunjay** [comment]
Thank you!
