### ISSUE TITLE
added vim mode but i (insert not working)

### ISSUE THREAD

**Issue by chocolatekitkat** [atom/vim-mode#954]
Hi,
this might be a newbie problem, but it looks like vim is installed and the keybindings are there, but
when I try to hit i it doesnt go into insert mode, shift a doesnt work either? jkl are working but thats all.
:\

**Comment by maxbrunsfeld** [comment]
Could you report your Atom version, OS, and keyboard layout? Does this problem persist when restarting Atom?

**Comment by chocolatekitkat** [comment]
Hi Max,

I restarted Atom and vim works now. I was installing new themes at the time.
I should have thought of that.  Always restart... ;) I just started using Atom.

Thanks!
