### ISSUE TITLE
Soft Wrap impacts page down command

### ISSUE THREAD

**Issue by dcalhoun** [atom/vim-mode#961]
The [half page down](http://vimhelp.appspot.com/scroll.txt.html#CTRL-D) and [page down](http://vimhelp.appspot.com/scroll.txt.html#CTRL-F) appear to be impacted negatively by the Atom "Soft Wrap" preference. I originally reported this issue in [#941](https://github.com/atom/vim-mode/issues/941#issuecomment-170930772), but I'm not sure it's related in actuality. [This is the file](https://gist.github.com/dcalhoun/ff4984e06fa4d4f40d00) I've been using for testing.

#### Behavior
As a user, I press and hold <kbd>ctrl</kbd> + <kbd>f</kbd> or <kbd>ctrl</kbd> + <kbd>d</kbd>.

#### Expected Outcome
The editor scrolls for as long as I hold the keys, until reaching the end of the document. The line numbers update accordingly. The cursor is visible throughout.

#### Current Outcome
The editor scrolls two pages. The line numbers update accordingly for the first two pages. The cursor disappears immediately.

#### Environment
- Mac OS X 10.11.3 (15D21)
- Atom v.1.4.3
- Preferred Line Length (100)
- Soft Wrap (enabled)
- Soft Wrap At Preferred Line Length (enabled)

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
+1
I'm also suffering from the same problem.

My Environment is
- Mac OS X 10.11.2
- Atom 1.5.0 ( Also I did test 1.5.3, the problem still occurs )
- vim-mode 0.64.0

Without softwrap, all thing is ok.
But with softwrap, if my document has wrapped part as a long column,
 `ctrl-e`, `ctrl-d` and `ctrl-f` can not reach to the end of document.

I think it is the one of most big problem in vim-mode.

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
I figured out a bit.

`@editor.setFirstVisibleScreenRow()` use `getLineCount()` not `getScreenLineCount()`.
That method return a real line count not based on screen.

To avoid, I change `setFirstVisibleScreenRow()` to `@editorElement.setScrollTop()`,
and change `getLastVisibleScreenRow()` (also use `getLineCount()`) to a other way.

I will PR soon.

**Comment by maxbrunsfeld** [comment]
I believe this is fixed in Atom 1.5.4, thanks to a PR by @b6pzeusbc54tvhw5jgpyw8pwz2x6gs.
