### ISSUE TITLE
dd/yy sometimes inserts characters/deletes lines

### ISSUE THREAD

**Issue by tepf** [atom/vim-mode#964]
Unfortunately I can't find a way to reproduce it. But it happens every couple minutes. I've caught `dd` inserting characters here:

![bug](https://cloud.githubusercontent.com/assets/14161807/12984046/51150a04-d0ec-11e5-9761-8349938a8461.gif)

This recording is on Atom 1.5.1, but it happened before as well.

**Comment by jazzpi** [comment]
Looks like #657... Does it happen with those steps?

**Comment by tepf** [comment]
> Looks like #657... Does it happen with those steps?

Indeed, it does.

**Comment by 50Wliu** [comment]
Thanks for the update @tepf!  Closing this in favor of #657.
