### ISSUE TITLE
Ctrl+H and Ctrl+L navigation between all window panes (including tree view)

### ISSUE THREAD

**Issue by jontonsoup** [atom/vim-mode#980]
@lee-dohm I'd love to be able to use Ctrl+H and Ctrl+L to navigate between the tree and the windows. I think this is standard with nerd-tree, but I'm not sure.

The square vim distro is an example of this: https://github.com/square/maximum-awesome

**Comment by BinaryMuse** [comment]
Hey @jontonsoup, would you be happy with some custom keymaps for this functionality or do you think it should come built-in with the package?

For the custom functionality, you could add something like the following to your [Keymap](https://atom.io/docs/latest/behind-atom-keymaps-in-depth):

```cson
'atom-text-editor.vim-mode':
  'ctrl-h': 'tree-view:toggle-focus'
'.tree-view':
  'ctrl-l': 'tree-view:toggle-focus'
```

**Comment by jontonsoup** [comment]
@BinaryMuse thanks for the suggestion -- I just realized that I meant HJKL to work between all window panes, including the tree view. I now realize this is a default in maximum awesome, and not in nerd-tree.

As to whether it should come with the built in is up to the maintainers -- I would support it :).

**Comment by BinaryMuse** [comment]
Ah, got it. Yeah, it looks like they have `Ctrl+[hjkl]` as an alias for `Ctrl-W [hjkl]`, so it'd probably be preferable to have that part of it in custom keybindings if you like the shorter versions. However, there *is* the part where the tree in normal vim is simply a buffer, and so you can move to it using the same keyboard shortcuts as any other buffers; perhaps vim-mode could offer a version of the `window.focus-pane-on-left` command that moves to the tree view if the left-most pane is already focused.

**Comment by jontonsoup** [comment]
That would be awesome!

**Comment by lee-dohm** [comment]
As stated in [the README](https://github.com/atom/vim-mode), this package is no longer maintained and is deprecated. We recommend that people use the [vim-mode-plus package](https://atom.io/packages/vim-mode-plus) instead. Because of this, we are [archiving this repository](https://help.github.com/articles/about-archiving-repositories/) and closing all issues and pull requests. Thanks very much for your support and contributions!
