### ISSUE TITLE
`ciw`, `dd`, etc. overwrite clipboard.

### ISSUE THREAD

**Issue by azoerb** [atom/vim-mode#982]
I used to be able to copy some code via `Cmd C`, delete a line via `dd` and then paste the copied code via `Cmd V`.  One of the recent changes now overwrites the clipboard, so that pasting after a `dd` pastes the line I just deleted.

Same goes for `ciw`, and I'm sure others as well.

OSX 10.11.2
Atom 1.5.4
vim-mode 0.65.0

**Comment by JesseLeite** [comment]
@azoerb Check the settings view for vim-mode package, and disable this checkbox: 

<img width="306" alt="screen shot 2016-03-17 at 11 02 31 pm" src="https://cloud.githubusercontent.com/assets/5187394/13867339/69c1e234-ec94-11e5-9000-c2042d5a4308.png">

**Comment by azoerb** [comment]
Awesome, thanks!  Was this a new addition?  I just realized this happening a few days ago.

**Comment by JesseLeite** [comment]
Not sure, I think the option has always been there.  They did recently changed default behaviour though.
